### ISSUE TITLE
关于增量字段

### ISSUE THREAD

**Issue by fantasticKe** [WeiYe-Jing/datax-web#10]
您好，由于有些数据表中不包含时间戳字段。在做数据增量时，需要根据自增主键进行脚本替换。我准备支持该功能并向仓库提交PR，您觉得这个主意怎么样？可能会涉及到修改一些表结构及相关代码。

**Comment by WeiYe-Jing** [comment]
您好，这个功能也在我们的开发计划中，能由您来提供，非常感谢，期待。
