### ISSUE TITLE
Hive 生成执行脚本数据源转换失败

### ISSUE THREAD

**Issue by leigao-dev** [WeiYe-Jing/datax-web#101]
![image](https://user-images.githubusercontent.com/61639526/79182736-201e0100-7e42-11ea-9978-11199a11df6c.png)

datax 在执行是针对hive本身的字段类型  Bigint等会统一识别为long进行处理，如果执行脚本写为自身的类型，就会无法识别

**Comment by WeiYe-Jing** [comment]
数据类型的支持需要修改datax,datax web目前主要专注web方面的功能。
