### ISSUE TITLE
连接池问题

### ISSUE THREAD

**Issue by liruimin1988** [WeiYe-Jing/datax-web#109]
1、当前的连接池不支支持db2数据库，如果使用db2必须修改连接池
2、当前本地代码使用的是阿里的德鲁伊连接池，db2和mysql连接正常
3、其它的数据库我这边没有，需要测试对原有数据库的兼容性
4、数据库类型目前是写完在前端业务的，希望数据库类型配置表可以用的上

**Comment by WeiYe-Jing** [comment]
合并到 #222
