### ISSUE TITLE
选择数据源表下拉框属性更改

### ISSUE THREAD

**Issue by jiaheweiwei** [WeiYe-Jing/datax-web#118]
源代码中的表的下拉框只有可选属性,建议改为可选可输入,解决Oracle的用户名在权限内可查其他表空间下的表  filterable----> allow-create default-first-option filterable

**Comment by jiaheweiwei** [comment]
源代码中的表的下拉框只有可选属性,建议改为可选可输入,解决Oracle的用户名在权限内可查其他表空间下的表    前端代码src/views/datax/jsonbuild/reader/RDBMSReader.vue   15行  filterable----> allow-create default-first-option filterable

**Comment by WeiYe-Jing** [comment]
已完成
