### ISSUE TITLE
相关配置信息是否可以单独做成配置文件形式

### ISSUE THREAD

**Issue by goodryb** [WeiYe-Jing/datax-web#119]
目前都是在编译前修改好yml文件，但有时候比如要部署到不同的地方，数据库地址、日志存储的地址都会不一样，每次都要重新修改和编译。

建议做成配置文件修改比较灵活，主程序启动时读取对应的配置文件。

**Comment by WeiYe-Jing** [comment]
可以通过配置文件外置的方式启动，例如：
java -jar demo.jar --spring.config.location=file:/config.yml
