### ISSUE TITLE
i18n 是必选字段吗？删除后无法启动

### ISSUE THREAD

**Issue by geekyouth** [WeiYe-Jing/datax-web#120]
IllegalArgumentException: Could not resolve placeholder 'datax.job.i18n' in value "${datax.job.i18n}"

能不能支持打包后自动生成配置文件？

**Comment by WeiYe-Jing** [comment]
可以通过配置文件外置的方式启动，例如：
java -jar demo.jar --spring.config.location=file:/config.yml
