### ISSUE TITLE
能不能开通微信沟通群

### ISSUE THREAD

**Issue by weipengffk** [WeiYe-Jing/datax-web#121]
微信使用后，已经很少用qq了。有的公司禁止使用qq，比如我的。
用微信的话，受众群体会飙升的

**Comment by WeiYe-Jing** [comment]
建微信群，用户进群之前是不是需要加我好友，我只有一个微信号

**Comment by weipengffk** [comment]
不用啊。就像家庭群一样。只要能扫就能进去。不用加好友。
