### ISSUE TITLE
建议添加对Greenplum的支持

### ISSUE THREAD

**Issue by yyz940922** [WeiYe-Jing/datax-web#124]
默认的postgresqlwriter没有用到copy_from()方法, 性能很差, 建议提供HashData家的gpdbwriter。https://github.com/HashDataInc/DataX

**Comment by WeiYe-Jing** [comment]
谢谢建议，后续会加到迭代计划中，也欢迎PR，有什么困难我们可以协助。

**Comment by prismcore** [comment]
目前可以通过直接连接postgres的方式连接GP 注意端口2345

**Comment by sealdust** [comment]
我们数仓也是GP，准备使用https://github.com/HashDataInc/DataX，恳请大佬支持使用gpdbwriter啊

**Comment by WeiYe-Jing** [comment]
> 我们数仓也是GP，准备使用[https://github.com/HashDataInc/DataX，恳请大佬支持使用gpdbwriter啊](https://github.com/HashDataInc/DataX%EF%BC%8C%E6%81%B3%E8%AF%B7%E5%A4%A7%E4%BD%AC%E6%94%AF%E6%8C%81%E4%BD%BF%E7%94%A8gpdbwriter%E5%95%8A)

这个需求可以放到2.1.4版本，如果你这边比较急可以参与到项目中，这块的集成很简单，在pg的基础上修改就行了，我们也会提供帮助，非常欢迎参与。

**Comment by sealdust** [comment]
OK，谢谢！我部署完成后会尝试一下。

**Comment by WeiYe-Jing** [comment]
> OK，谢谢！我部署完成后会尝试一下。

好的，有问题随时交流。

**Comment by sealdust** [comment]
我们准备今天开始动工，要下载dev分支么？

**Comment by WeiYe-Jing** [comment]
> 我们准备今天开始动工，要下载dev分支么？

是的，先fork项目到自己github，然后从自己github拉取代码，切到dev开发

**Comment by huangzhengshun** [comment]
对于greenplum数据库，这个版本已经支撑了https://github.com/huangzhengshun/datax-web

**Comment by WeiYe-Jing** [comment]
> 对于greenplum数据库，这个版本已经支撑了https://github.com/huangzhengshun/datax-web

这块功能可以提交到社区dev分支吗，包括前端的修改，谢谢！

**Comment by sealdust** [comment]
哇，我下载这个试试

**Comment by WeiYe-Jing** [comment]
已完成

**Comment by Zhushatianxia** [comment]
请问现在哪个版本实现了gpdbwriter这个功能

**Comment by huangzhengshun** [comment]
> 请问现在哪个版本实现了gpdbwriter这个功能

你可以试试dev分支，

**Comment by huangzhengshun** [comment]
@Zhushatianxia
你可以试试dev分支，目前这里已经重构好了，
