### ISSUE TITLE
datax-registry包名有问题

### ISSUE THREAD

**Issue by 552301** [WeiYe-Jing/datax-web#127]
项目中datax-registry里面包名有问题，本来应该是com/wugui/datax/registry写成了com.wugui.datax.registry

main/java/com.wugui.datax.registry

虽然不影响使用，但是在idea和eclipse里面会导致相关项目报错

**Comment by WeiYe-Jing** [comment]
新版中datax-registry模块已经合并到datax-rpc中了，新版dev分支功能预计明天开发结束，欢迎试用。
