### ISSUE TITLE
连接hive数据源的问题

### ISSUE THREAD

**Issue by dykw** [WeiYe-Jing/datax-web#128]
Code:[DBUtilErrorCode-10], Description:[连接数据库失败. 请检查您的 账号、密码、数据库名称、IP、Port或者向 DBA 寻求帮助(注意网络环境).]. - 具体错误信息为：java.sql.SQLException: Could not establish connection to jdbc:hive2://localhost:10028: Required field 'client_protocol' is unset! Struct:TOpenSessionReq(client_protocol:null, configuration:{use:database=default})
我把datax-all的hive-jdbc的版本调整到1.1.0和我本地一样 还是报错连接不上

**Comment by WeiYe-Jing** [comment]
这个问题用户群反馈较多，原因是datax web依赖的hive-jdbc版本和用户环境hive版本不兼容导致，先检查下本地的hive版本确定是否与hive-jdbc的1.1.0兼容。

**Comment by WeiYe-Jing** [comment]
你好，问题解决了吗

**Comment by anqingliang** [comment]
> Code:[DBUtilErrorCode-10], Description:[连接数据库失败. 请检查您的 账号、密码、数据库名称、IP、Port或者向 DBA 寻求帮助(注意网络环境).]. - 具体错误信息为：java.sql.SQLException: Could not establish connection to jdbc:hive2://localhost:10028: Required field 'client_protocol' is unset! Struct:TOpenSessionReq(client_protocol:null, configuration:{use:database=default})
> 我把datax-all的hive-jdbc的版本调整到1.1.0和我本地一样 还是报错连接不上

1可以下载一个hive客户端连接工具看是否连接正常，工具的话可以使用dbeaver，连接方法和普通mysql数据库一样简单
2如果问题还没有解决先将hiveserver2、beeline升级到相应版本，再使用相应的jdbc连接测试

**Comment by zhanghaicheng1** [comment]
可参考项目：https://github.com/timveil/hive-jdbc-driver
打个包连接即可。

**Comment by dykw** [comment]
hive的版本保持和本地一致就好了 虽然我不是这个项目解决了这个问题，另一个项目我是把项目依赖的hive相关的jar全部替换成我本地hive版本适配的jar 就可以了

**Comment by Mryst** [comment]
> 可参考项目：https://github.com/timveil/hive-jdbc-driver
> 打个包连接即可。

能说下具体怎么操作的嘛 感谢

**Comment by guguoyu** [comment]
你们怎么解决的呀，我们用的cdh 5.16.2的，拷贝了感觉还是没用
