### ISSUE TITLE
一个调度任务正常执行一段时间后会报错，比如执行成功50次后，报错信息如下：

### ISSUE THREAD

**Issue by qinqinnb** [WeiYe-Jing/datax-web#131]
![image](https://user-images.githubusercontent.com/52516672/84222397-19420080-ab0a-11ea-8b98-2addfe0cd9e3.png)
![image](https://user-images.githubusercontent.com/52516672/84222435-26f78600-ab0a-11ea-9fbb-349eb8c398dc.png)

**Comment by WeiYe-Jing** [comment]
麻烦描述下任务类型及配置截图，脚本信息。
