### ISSUE TITLE
配置时间增量无法增量同步

### ISSUE THREAD

**Issue by 306495389li** [WeiYe-Jing/datax-web#133]
表结构如：
CREATE TABLE `student` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `age` int(11) DEFAULT NULL,
  `gender` bit(1) DEFAULT NULL,
  `updateTime` datetime DEFAULT NULL,
  `createTime` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

要以createTime增量
现在进行下去，每次执行都是全量同步

**Comment by WeiYe-Jing** [comment]
请截图展示下任务配置信息

**Comment by 306495389li** [comment]
> 请截图展示下任务配置信息

![image](https://user-images.githubusercontent.com/15187323/84224025-12b58800-ab0e-11ea-9953-6946a3844bd0.png)

**Comment by WeiYe-Jing** [comment]
json配置中reader部分的querysql也截图下

**Comment by WeiYe-Jing** [comment]
[可以参数文档：](https://github.com/WeiYe-Jing/datax-web/blob/master/doc/datax-web/%E5%8A%A8%E6%80%81%E5%8F%82%E6%95%B0%E5%AE%8C%E6%88%90%E5%A2%9E%E9%87%8F%E6%8A%BD%E5%8F%96.md)
按照文档上面的说明，首先增量时间字段配置不正确，应该配置为：`-DlastTime='%s' -DcurrentTime='%s'`
其中lastTime和currentTime是你querySql中的where条件，配置如下：`"querySql": [
        "select * from test_list where operationDate >= FROM_UNIXTIME(${lastTime}) and operationDate < FROM_UNIXTIME(${currentTime})"
                                ]`

**Comment by 306495389li** [comment]
"querySql": [
        "select * from test_list where operationDate >= FROM_UNIXTIME(${lastTime}) and operationDate < FROM_UNIXTIME(${currentTime})"
                                ]这个是需要在构建任务时手动拼进去的吗？这个界面配置吗

**Comment by WeiYe-Jing** [comment]
是的，querySql需要自己在任务配置页面添加或者在json构建中的querySql中提前添加

**Comment by 306495389li** [comment]
现在这么配的，执行报错
![image](https://user-images.githubusercontent.com/15187323/84230840-75634f80-ab1f-11ea-9343-0d011ba4cebd.png)
![image](https://user-images.githubusercontent.com/15187323/84230867-82803e80-ab1f-11ea-8af1-fa4a7b52b34f.png)

**Comment by WeiYe-Jing** [comment]
怎么不把报错信息贴出来

**Comment by 306495389li** [comment]
com.alibaba.datax.common.exception.DataXException: Code:[DBUtilErrorCode-07], Description:[读取数据库数据失败. 请检查您的配置的 column/table/where/querySql或者向 DBA 寻求帮助.].  - 执行的SQL为: select * from student where createTime >= FROM_UNIXTIME(${lastTime}) and createTime < FROM_UNIXTIME(${currentTime}) 具体错误信息为：com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '{lastTime}) and createTime < FROM_UNIXTIME(${currentTime})' at line 1

**Comment by WeiYe-Jing** [comment]
问题已修复

**Comment by yinwenzhi** [comment]
请问，使用时间增量模式时 ${currentTime} 参数可以在 postsql的where条件中使用吗？
我的postsql： ... where creatTime <  ${currentTime}  and creatTime >= ${lastTime},
执行后发现postsql语句没有执行效果。
查看后日志发现执行的postsql语句为：
![DL` VVNL $BT%L83H}ORQ2M](https://user-images.githubusercontent.com/11879864/174273900-101dab0e-1d48-4d94-a969-88457f897dcf.png)
在参数替换时，日期与时间中间多出一个百分号
请问是什么原因？ 谢谢

**Comment by yinwenzhi** [comment]
> 请问，使用时间增量模式时 ${currentTime} 参数可以在 postsql的where条件中使用吗？ 我的postsql： ... where creatTime < currentTimeandcreatTime>={lastTime}, 执行后发现postsql语句没有执行效果。 查看后日志发现执行的postsql语句为： ![DL` VVNL $BT%L83H}ORQ2M](https://user-images.githubusercontent.com/11879864/174273900-101dab0e-1d48-4d94-a969-88457f897dcf.png) 在参数替换时，日期与时间中间多出一个百分号 请问是什么原因？ 谢谢

经过验证认真排查数据，postsql中是可以使用lastTime参数的，执行语句中出现百分号是正常的。请忽略上述提问。

**Comment by canyuan0801** [comment]
`2022-06-27 17:02:30 [AnalysisStatistics.analysisStatisticsLog-53] com.alibaba.datax.common.exception.DataXException: Code:[DBUtilErrorCode-06], Description:[执行数据库 Sql 失败, 请检查您的配置的 column/table/where/querySql或者向 DBA 寻求帮助.].  - 执行的SQL为: select [STCD],[STINDEX],[TM],[ENDTM],[WARNVAL],[STVAL],[WARNINFO],[STNM],[YBFBTM] from dbo.ST_WARN_INFO where (TM >= '2010-01-01%16:21:44' and TM < '2022-06-27%17:02:29') 具体错误信息为：com.microsoft.sqlserver.jdbc.SQLServerException: 从字符串转换日期和/或时间时，转换失败。
`
你好，在SQLServer也会出现这个百分号，但是报错，请问怎么解决？谢谢
