### ISSUE TITLE
添加Oracle数据源，没有字段选择，导致无法构建

### ISSUE THREAD

**Issue by dudefu** [WeiYe-Jing/datax-web#136]
![image](https://user-images.githubusercontent.com/5269023/84488006-29a4d780-acd2-11ea-8bb8-e7b4008bf1b0.png)
注：该表确定是有字段的

**Comment by WeiYe-Jing** [comment]
#135 已经记录这个问题了，新版下周上线前会修复这个问题，谢谢！

**Comment by dudefu** [comment]
辛苦了
