### ISSUE TITLE
任务执行成功 但是获取不到日志，无法返回成功或者失败的状态

### ISSUE THREAD

**Issue by AvengerZH** [WeiYe-Jing/datax-web#138]
oracle读取数据写到mysql的时候，日志显示成功，但是状态栏一直为空，无法更新状态。yml配置如图。
![PP_S71V@K1%F@2QVJ9A4XTA](https://user-images.githubusercontent.com/46047849/84683648-1c097f00-af6a-11ea-9e94-b22341d4083d.png)
![`}(NW{N%7SVE6%N~~$V2JCY](https://user-images.githubusercontent.com/46047849/84683656-20ce3300-af6a-11ea-8443-bca5edfbaf1a.png)
![VUO)O$B4J9T`P3}3A2)FDX9](https://user-images.githubusercontent.com/46047849/84683672-26c41400-af6a-11ea-94f5-fbf902051df7.png)
![`}(NW{N%7SVE6%N~~$V2JCY](https://user-images.githubusercontent.com/46047849/84683795-58d57600-af6a-11ea-8a1e-490a24265b25.png)

**Comment by WeiYe-Jing** [comment]
检查下dev分支代码是否更新，此问题已修复。如果代码更新到最新了，请检查下admin的日志，将异常信息贴出来看看，谢谢！

**Comment by WeiYe-Jing** [comment]
问题已解决，增量类型字段不能为空
