### ISSUE TITLE
批量构建任务时的问题

### ISSUE THREAD

**Issue by AvengerZH** [WeiYe-Jing/datax-web#139]
批量构建任务时，选择oracle没反应，无法选择schema提供同步所需要的表。MySQL数据库却可以弹出数据库下的所有表名
![image](https://user-images.githubusercontent.com/46047849/84684122-cb465600-af6a-11ea-8b5a-55c430302ebe.png)
![image](https://user-images.githubusercontent.com/46047849/84684152-d600eb00-af6a-11ea-89a8-cbd776a533df.png)

**Comment by WeiYe-Jing** [comment]
从github dev获取的代码吗,最新的页面截图如下：
![image](https://user-images.githubusercontent.com/33245094/84717360-2cd8e580-afa8-11ea-99ac-900d21da3f2e.png)

**Comment by AvengerZH** [comment]
大佬辛苦了。
