### ISSUE TITLE
mongodb空表无法映射列

### ISSUE THREAD

**Issue by NicDou** [WeiYe-Jing/datax-web#143]
mongodb空表无法映射列

**Comment by WeiYe-Jing** [comment]
可以详细描述下问题吗，那个版本，空表是指没数据吗，admin日志有报错吗，页面有报错吗

**Comment by NicDou** [comment]
版本是我clone的master，是的,没数据的时候,没有报错
![image](https://user-images.githubusercontent.com/8869069/84851834-e493f300-b08d-11ea-92bf-d2c3f42c30d4.png)

**Comment by WeiYe-Jing** [comment]
有数据正常吗，admin的日志看过了吗

**Comment by NicDou** [comment]
有数据的正常
![{B5E54F7E-6627-486E-A9E0-65C4EAD80995}_20200617113336](https://user-images.githubusercontent.com/8869069/84852125-96cbba80-b08e-11ea-9c80-7128b658c791.jpg)

**Comment by NicDou** [comment]
这个好像还真不行，没数据压根不知道mongodb里要存啥？现在是我想从mysql读写入mongo，是不是mong的列就定位mysql勾选的列

**Comment by WeiYe-Jing** [comment]
是的，没数据获取不到列信息。mysql读写入mongo，按构建步骤选择数据源，选择列，构建就可以了。

**Comment by czetao** [comment]
@WeiYe-Jing 请问能否没有列信息的时候，自动创建列呢

**Comment by WeiYe-Jing** [comment]
> @WeiYe-Jing 请问能否没有列信息的时候，自动创建列呢

先检查下是什么问题导致查询失败，可以看下日志，安装文档有日志路径。也可以自己写json。

**Comment by sunshibiao** [comment]
mongodb空表无法映射列
![image](https://user-images.githubusercontent.com/5415813/105283785-1fde3d80-5bec-11eb-9db3-004db4157ece.png)
