### ISSUE TITLE
callback 出错

### ISSUE THREAD

**Issue by NicDou** [WeiYe-Jing/datax-web#144]
![F2726861-1918-4cb7-8EA1-D6E3057D8DFA](https://user-images.githubusercontent.com/8869069/84852877-8583ad80-b090-11ea-9e18-7211f41b7c31.png)
![249B802F-2588-438c-892E-FD88DB50C997](https://user-images.githubusercontent.com/8869069/84852880-86b4da80-b090-11ea-9e2a-707b653d4af0.png)
任务管理那边辅助参数不选会有问题

**Comment by WeiYe-Jing** [comment]
百度网盘的代码没及时更新，问题已修复
