### ISSUE TITLE
mongodb 不用用户名和密码会存一个用户名和密码 导致后面使用该数据源出错

### ISSUE THREAD

**Issue by NicDou** [WeiYe-Jing/datax-web#145]
![44](https://user-images.githubusercontent.com/8869069/84853397-b44e5380-b091-11ea-88de-6e0431b3b6c0.jpg)

**Comment by NicDou** [comment]
地址格式:
mongodb://127.0.0.1:27017/credit

**Comment by WeiYe-Jing** [comment]
数据源出什么错呢？

**Comment by NicDou** [comment]
会用这个生成的用户名和密码与连mongo 我没传用户名和密码 为啥数据库里会有值 我看代码有个判断分支如果有用户名和密码会用他们连mongo

**Comment by NicDou** [comment]
![密码](https://user-images.githubusercontent.com/8869069/84859596-0eeeac00-b0a0-11ea-9a10-d0ca3cc01ced.jpg)

**Comment by WeiYe-Jing** [comment]
已修复

**Comment by WeiYe-Jing** [comment]
问题解决了吗

**Comment by NicDou** [comment]
可以了

**Comment by WeiYe-Jing** [comment]
好
