### ISSUE TITLE
怎么建立前置任务

### ISSUE THREAD

**Issue by 306495389li** [WeiYe-Jing/datax-web#146]
我现在有个需求是，每天固定时间建立hive分区，然后执行mysqlToHive数据同步，应该怎么弄

**Comment by WeiYe-Jing** [comment]
可以通过shell任务每天定时建立分区或者批量创建一段时间内的分区

**Comment by 306495389li** [comment]
这2个任务单独都会使用，现在应该怎么把两个任务串起来，能给个例子吗

**Comment by WeiYe-Jing** [comment]
任务配置页面有子任务选项，父任务执行结束会触发子任务

**Comment by 306495389li** [comment]
我现在是需要shell任务启动定时，然后设置mysqlToHive的任务作为子任务，不定时启动，然后每天会定时在执行了shell后执行mysqlToHive任务吗

**Comment by WeiYe-Jing** [comment]
会的，你可以试下

**Comment by 306495389li** [comment]
@WeiYe-Jing 好的，谢了，我试一下

**Comment by 306495389li** [comment]
shell任务不能通过页面生成是吧？要自己建好贴进去吧

**Comment by WeiYe-Jing** [comment]
shell任务需要手写复制到任务中
