### ISSUE TITLE
路由策略的多个机器是指执行器吗

### ISSUE THREAD

**Issue by prismcore** [WeiYe-Jing/datax-web#147]
路由策略选择某一个机器跑job，这里的机器是执行器吗，如果是，上面为什么还需要选执行器呢？
是要建立多个执行器用路由策略来实现分布式吗？

**Comment by WeiYe-Jing** [comment]
路由策略是指一个执行器下多个节点的执行策略。

**Comment by prismcore** [comment]
> 路由策略是指一个执行器下多个节点的执行策略。启动多个executor，appname配置相同，那这些executor归属同一个执行器。

有什么好办法创建多个执行器节点，datax-executor是一个执行器还是一个执行器节点

**Comment by WeiYe-Jing** [comment]
datax-executor是一个执行器.可以这样理解:你可以启动多个executor,appname都为datax-executor，那这多个executor就是datax-executor执行器的节点.
