### ISSUE TITLE
PostGreqSQL 任务构建时无法显示表字段的bug

### ISSUE THREAD

**Issue by liufyi** [WeiYe-Jing/datax-web#148]
在任务构建中，数据源选数据库类型为PostGreqSQL ，表能显示出来 ，但选表后字段却无法显示
问题分析：
postgresql,有schema的概念，但显示出来的表是不带schema，需要把schema拼接上表名，才可以

查询表及schema的sql如下 
select concat_ws('.',schemaname,tablename) from pg_tables

**Comment by WeiYe-Jing** [comment]
是哪个版本，2.1.2版本吗

**Comment by liufyi** [comment]
> 是哪个版本，2.1.2版本吗

我用的是master支持。

**Comment by WeiYe-Jing** [comment]
什么时候获取的代码

**Comment by liufyi** [comment]
> 什么时候获取的代码

上周

**Comment by WeiYe-Jing** [comment]
> > 什么时候获取的代码
> 
> 上周

新版本周二已经发布，修复了这个问题，可以看看
