### ISSUE TITLE
hbase导入数据时三个bug

### ISSUE THREAD

**Issue by dudefu** [WeiYe-Jing/datax-web#149]
前提：集群坏境下
### **bug1 表名格式问题**
![image](https://user-images.githubusercontent.com/5269023/84977865-09579b80-b15e-11ea-8308-0388d866f193.png)
原因：table名称格式不对，构建json自动生成模板为：["dataxtest"]，导致报错，应改为："dataxtest"。
### **bug2 配置问题**
![image](https://user-images.githubusercontent.com/5269023/84979398-f646ca80-b161-11ea-92ef-34e905525866.png)
需要添加配置："zookeeper.znode.parent":"/hbase-unsecure" 
### **bug 3  column index问题**
![image](https://user-images.githubusercontent.com/5269023/84979744-c5b36080-b162-11ea-9096-7f3d6644bd3a.png)

修改前的配置：
![image](https://user-images.githubusercontent.com/5269023/84979964-525e1e80-b163-11ea-8c86-4aa795271f0c.png)

修改后的配置：
![image](https://user-images.githubusercontent.com/5269023/84979836-01e6c100-b163-11ea-9b1b-f10cf96d7f7f.png)

**Comment by WeiYe-Jing** [comment]
感谢提供详细的问题描述，如果方便能将修复后的代码贡献出来吗，感谢！如果不方便我这边来完成。

**Comment by dudefu** [comment]
可以的，等改好了提交代码

**Comment by dudefu** [comment]
> 感谢提供详细的问题描述，如果方便能将修复后的代码贡献出来吗，感谢！如果不方便我这边来完成。

我看了下代码，改动也很简单，但可能需要你那边综合考虑下要不要改，所以我贴出需要改的地方：
![image](https://user-images.githubusercontent.com/5269023/85001271-07093780-b186-11ea-8063-44c9dba1de63.png)
![image](https://user-images.githubusercontent.com/5269023/85001295-0c668200-b186-11ea-81f3-4777ce893ca0.png)
![image](https://user-images.githubusercontent.com/5269023/85001309-112b3600-b186-11ea-84fb-af8aa0c5d458.png)
“List<String> writerTable” 这个参考官方应该是string，你这为啥是数组，数组会报错。

**Comment by dudefu** [comment]
> > 感谢提供详细的问题描述，如果方便能将修复后的代码贡献出来吗，感谢！如果不方便我这边来完成。
> 
> 我看了下代码，改动也很简单，但可能需要你那边综合考虑下要不要改，所以我贴出需要改的地方：
![image](https://user-images.githubusercontent.com/5269023/85001819-b940ff00-b186-11ea-8bc7-9e5c51ea9c09.png)
![image](https://user-images.githubusercontent.com/5269023/85001837-be9e4980-b186-11ea-8ca7-afe9a503c513.png)
![image](https://user-images.githubusercontent.com/5269023/85001851-c3fb9400-b186-11ea-8ab5-b93a85a6b72d.png)

> “List writerTable” 这个参考官方应该是string，你这为啥是数组，数组会报错。

**Comment by WeiYe-Jing** [comment]
感谢指正!
1.conf.set("zookeeper.znode.parent","/hbase-unsecure");
#134 已经提出这个配置，计划是前端页面增加参数配置，由于数据源这块下个版本要重构，暂时没改。
2.writer index+1考虑的是rowkeyColumn index默认0.
3.readerTable和writerTable用数组是个bug我修复下
