### ISSUE TITLE
datax集群部署，多个节点上的datax怎么加入datax-web的执行器

### ISSUE THREAD

**Issue by JennyZhang-bd** [WeiYe-Jing/datax-web#150]
直接在界面手动加入失败，报错无法连接。
目前的准备的做法是，所有executor配同一个web地址，在每个datax安装节点上都放上executor的jar，每个节点都启动executor，最后启动web程序。

**Comment by WeiYe-Jing** [comment]
执行器的配置可以截图看看。
删掉手动配置的执行器。executor如果配置正确，启动完成后会自动注册，没有自动注册说明配置有问题或者网络不通，对比下项目说明文档仔细检查下。

**Comment by JennyZhang-bd** [comment]
配置如下：105机器和100机器都有datax，都布上executor的jar，都启动了executor，105机器还有布admin的jar，启动admin，但是结果100的执行器还是没有自动注册。100和105之间是可以ping通的
![image](https://user-images.githubusercontent.com/61449031/85218348-0661e280-b3cc-11ea-92c8-f01dbdac5812.png)
![image](https://user-images.githubusercontent.com/61449031/85218330-e7fbe700-b3cb-11ea-8886-537946c9b01c.png)
![image](https://user-images.githubusercontent.com/61449031/85218339-f944f380-b3cb-11ea-8c1b-f40a6ca79947.png)
![image](https://user-images.githubusercontent.com/61449031/85218379-593b9a00-b3cc-11ea-9dde-7d87baea0be7.png)
![image](https://user-images.githubusercontent.com/61449031/85218393-7c664980-b3cc-11ea-892e-3446c7422316.png)

**Comment by JennyZhang-bd** [comment]
问题已经解决，就是自己粗心没有加http:// 协议，成功后自动注册
![image](https://user-images.githubusercontent.com/61449031/85251763-b565f300-b48c-11ea-9563-f62106d1f946.png)
![image](https://user-images.githubusercontent.com/61449031/85251812-ddeded00-b48c-11ea-98c9-37e92a2024a9.png)
