### ISSUE TITLE
datax-execturo 启动一断时间后自动掉线，查看日志显示注册失败，调用datax-admin注册超时

### ISSUE THREAD

**Issue by liufyi** [WeiYe-Jing/datax-web#151]
datax-execturo 启动一断时间后自动掉线（吃个饭回来2小时左右）
查看日志显示注册失败，调用datax-admin的registry接口返回500，显示ReadTimeout ,但它们是在同一台机器上部署的。此时访问datax-admin的页面，能正常访问。但执行器管理列表里，datax-executor的OnLine机器地址是空的。

使用分支：
master ,上周clone（当前时间2020.06.18）

**Comment by WeiYe-Jing** [comment]
项目部署的环境可以描述下吗，admin的日志也可以贴出来看看，我本地项目也一直在运行，还没遇到过这个问题。

**Comment by liufyi** [comment]
我是在内网部linux上部署。只能拍照，不能复制出错信息出来。
下面是一些关键信息（纯手打，单词有可能拼错）
[JobRemotingUtil.java : 106 ]Read Time out
datax-web registry fail,registryParam:RegistryParam{registryGroup:'Executor',RegistryKey='datax-execturo',registryValue='服务器的IP:端口'，cpuUsage='1.0',memoryUsage='32.0',loadAverage='0.57'},registryResult:ReturnT [code=500,msg=xxl-rpc remoting error(Read timed out)],for url : http://127.0.0.1:8822/api/registry, content=null]

当时情况是，有数据同步任务有executor上跑，1000多万的数据。最是数据跑成功了，这上点可以证明executor是没死掉的，它还在跑数据，只是注册不到admin上面，注册的时候出现了超时。但admin的页面此时是能正常访问的

**Comment by WeiYe-Jing** [comment]
需要看下admin当时的日志，executor注册admin 状态500，说明admin此时运行出现了异常。

**Comment by WeiYe-Jing** [comment]
问题解决了吗

**Comment by liufyi** [comment]
> 需要看下admin当时的日志，executor注册admin 状态500，说明admin此时运行出现了异常。

但是admin的页面并没有问题。能正常访问的。如果异常是不是应该页面应该不了

**Comment by WeiYe-Jing** [comment]
执行器注册是心跳请求admin接口，页面一般也不会一直去操作，执行器注册失败无非就是admin接口请求不通，一般原因网络问题或者数据库资源问题导致请求超时
