### ISSUE TITLE
StackOverflowError when getLogger

### ISSUE THREAD

**Issue by Simbafa** [WeiYe-Jing/datax-web#154]
cat modules/datax-admin/bin/console.out 
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/datax-web-2.1.2/modules/datax-admin/lib/log4j-slf4j-impl-2.11.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/datax-web-2.1.2/modules/datax-admin/lib/logback-classic-1.2.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/datax-web-2.1.2/modules/datax-admin/lib/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
Exception in thread "main" java.lang.StackOverflowError
        at org.apache.logging.log4j.util.StackLocator.getCallerClass(StackLocator.java:121)
        at org.apache.logging.log4j.util.StackLocatorUtil.getCallerClass(StackLocatorUtil.java:55)
        at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:42)
        at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:46)
        at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:29)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:358)
        at org.apache.logging.slf4j.SLF4JLoggerContext.getLogger(SLF4JLoggerContext.java:39)

**Comment by Simbafa** [comment]
Only in centos. In Ubuntu is OK.

**Comment by WeiYe-Jing** [comment]
This problem has been fixed. Please update the code and try again.

**Comment by Simbafa** [comment]
I tried the latest version. StackOverfloeError disappear, but has following issue:

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
07:29:17.199 admin [main] ERROR o.s.b.d.LoggingFailureAnalysisReporter - 

***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    org.apache.catalina.authenticator.AuthenticatorBase.startInternal(AuthenticatorBase.java:1178)

The following method did not exist:

    javax.servlet.ServletContext.getVirtualServerName()Ljava/lang/String;

The method's class, javax.servlet.ServletContext, is available from the following locations:

    jar:file:/datax-web-2.1.2/modules/datax-admin/lib/javax.servlet-3.0.0.v201112011016.jar!/javax/servlet/ServletContext.class
    jar:file:/datax-web-2.1.2/modules/datax-admin/lib/servlet-api-2.5.jar!/javax/servlet/ServletContext.class
    jar:file:/datax-web-2.1.2/modules/datax-admin/lib/tomcat-embed-core-9.0.17.jar!/javax/servlet/ServletContext.class

**Comment by WeiYe-Jing** [comment]
This problem was fixed once before the 2.1.2 release because of the Phoenix slf4j jar conflict. Today, I have deleted the Phoenix jar, which is a strange problem. There may be other log jar conflicts. Can you tell me about your CentOS environment configuration?

**Comment by Simbafa** [comment]
I have reproduced this issue in ubuntu.
It's strange. 
Same tar package uncompressed to different folders, the running state is different.
In NFS folders, it's ok. 
But in local machine folders, it's failed.
