### ISSUE TITLE
已添加项目名称 任务添加时项目id未加载出来

### ISSUE THREAD

**Issue by jon-qj** [WeiYe-Jing/datax-web#159]

**Comment by jon-qj** [comment]
![image](https://user-images.githubusercontent.com/39773194/85195707-57f46980-b307-11ea-9927-7eee4c95aefd.png)
选择自增主键时 reader源没有出现

**Comment by jon-qj** [comment]
![image](https://user-images.githubusercontent.com/39773194/85195746-a86bc700-b307-11ea-8f9f-a09632fb115a.png)
增量字段是id吗？可以自选吗？

**Comment by WeiYe-Jing** [comment]
刷新
