### ISSUE TITLE
yml文件那些地址参数什么意思，异如何配置不太明白。

### ISSUE THREAD

**Issue by 7hong** [WeiYe-Jing/datax-web#16]

**Comment by WeiYe-Jing** [comment]
datax-executor下application.yml的四个配置
1、datax.job.admin.addresses(调度中心地址，多个以逗号分隔)
2、datax.job.executor.logpath(数据抽取日志文件保存路径)
3、datax.executor.jsonpath(datax json临时文件保存路径)
4、datax.pypath(datax/bin/datax.py)DataX启动文件的地址
