### ISSUE TITLE
从sqlserver增量数据更新到hdfs

### ISSUE THREAD

**Issue by jon-qj** [WeiYe-Jing/datax-web#162]
1、每天脚本执行一次
2、通过增量字段rowversion进行增量数据查询
3、将增量查询的数据保存在hdfs当天分区表中

**Comment by WeiYe-Jing** [comment]
项目目前的功能不能完整支持你的需求，
目前是任务创建页面辅助参数可以选择id增量同步，每次运行时根据maxid作为起始id查询数据。
目前单任务中只能选择id增量或者分区中的一种。

**Comment by jon-qj** [comment]
好的 谢谢解惑
