### ISSUE TITLE
vue打包好的项目如何整合到Springboot下运行

### ISSUE THREAD

**Issue by enzowu1992** [WeiYe-Jing/datax-web#165]
vue打包好的项目如何整合到Springboot下运行,vue.config.js 的proxy 需要改什么吗

**Comment by WeiYe-Jing** [comment]
![image](https://user-images.githubusercontent.com/33245094/85261960-9e7ccc00-b49f-11ea-95c4-8f570ddf25a7.png)
不需要修改vue.config.js，只需要将截图中的文件复制到datax-admin\src\main\resources\static文件下，替换掉原文件。

**Comment by enzowu1992** [comment]
好使了,谢谢

**Comment by WeiYe-Jing** [comment]
有什么需要优化的或者好的功能及建议欢迎提交到社区，保持和社区同步。
