### ISSUE TITLE
2.1.2版本中，任务构建的时候，该用户没有ORACLE的dba权限，获取不到Schema

### ISSUE THREAD

**Issue by WeiYe-Jing** [WeiYe-Jing/datax-web#166]
报错信息：
13:25:55.733 admin [http-nio-8700-exec-7] ERROR c.w.d.a.t.q.BaseQueryTool - [getTableNames Exception] --> the exception message is:ORA-00942: 表或视图不存在
因为执行获取schema的SQL（select username from sys.dba_users）的时候 发现其实该用户没有ORACLE的dba权限，所以报错表或视图不存在

**Comment by King-Star-Queen** [comment]
图形化任务构建中源库为Oracle，reader时数据库表名、writer时Schema和数据库表名都显示无数据，在datax-executor下的日志并没有报错。赋权给用户，还是没有显示

**Comment by WeiYe-Jing** [comment]
select username from sys.dba_users执行这个sql看下，Schema是通过这个sql获取的

**Comment by King-Star-Queen** [comment]
好了   已经搞定   因为页面没有全部刷新
