### ISSUE TITLE
querySQL中有order by或者group by解析字段报错

### ISSUE THREAD

**Issue by zhenxin77520** [WeiYe-Jing/datax-web#173]
在getColumnsByQuerySql方法中会在sql末尾添加“where 1=0”，导致有order by或者group by的sql错误。

**Comment by xiaosong0112** [comment]
+1

**Comment by xiaosong0112** [comment]
并且where那个字段的内容在最后生成的sql中没有体现呢。

**Comment by WeiYe-Jing** [comment]
> 并且where那个字段的内容在最后生成的sql中没有体现呢。

![image](https://user-images.githubusercontent.com/33245094/90612755-10248c80-e23b-11ea-8234-af5eacd23459.png)
检查下是不是违背了这条使用规则呢

**Comment by xiaosong0112** [comment]
嗯，确实是违背了~

**Comment by WeiYe-Jing** [comment]
此功能计划引入sql解析工具来完成

**Comment by WeiYe-Jing** [comment]
已完成 #284
