### ISSUE TITLE
可否支持批量同步一个数据库下所有表同步到另一个环境的同名库的所有同名表

### ISSUE THREAD

**Issue by JennyZhang-bd** [WeiYe-Jing/datax-web#174]
同步大量表的情况下，不停构建任务过于繁琐，可否支持批量同步一个数据库下所有表同步到另一个环境的同名库的所有同名表

**Comment by WeiYe-Jing** [comment]
2.1.2版本已经开发了对RDBMS的批量同步功能，可以试用下

**Comment by JennyZhang-bd** [comment]
用2.1.2替换2.1.1，更改mysql表结构，保留过往mysql数据记录，是否可以衔接使用，还是说任务配置等都需要重建

**Comment by JennyZhang-bd** [comment]
抱歉已看到备注：
2.1.1版本不建议升级，数据源信息加密方式变更会导致之前已加密的数据源解密失败，任务运行失败。 如果需要升级请重建数据源，任务。
谢谢。
