### ISSUE TITLE
postgre数据库必须有schema才能展示字段

### ISSUE THREAD

**Issue by qin-su** [WeiYe-Jing/datax-web#175]
配置postgre的构建时候，无论reader或writer构建，选择postgre源，表都是没有schema的，不能显示表字段。

**Comment by nightxing** [comment]
oracle数据库同样会出现这样的问题,后台代码中使用的是从dba库查询的。好多公司是不会给dba权限的。查询schema信息，可以从all_tab_comments表进行distinct，这样应该能查到该用户的所有schema，但是要将一些系统的schema过滤掉。我只有了oracle，没有用过postgre

**Comment by WeiYe-Jing** [comment]
> oracle数据库同样会出现这样的问题,后台代码中使用的是从dba库查询的。好多公司是不会给dba权限的。查询schema信息，可以从all_tab_comments表进行distinct，这样应该能查到该用户的所有schema，但是要将一些系统的schema过滤掉。我只有了oracle，没有用过postgre

目前schema是从table_schema中查询的，这个问题和oracle页面无法选择用户是一样的，我会在页面加个schema非必选的控制，如果没有就用当前用户查询

**Comment by WeiYe-Jing** [comment]
问题已修复并上传到2.1.2分支（注意是分支），方便可以帮忙测试下，谢谢！

**Comment by nightxing** [comment]
现在修复完成之后是可以不选择schema了，但是使用过程中还是能够选择schema的比较好。之前查不到schema都是权限不够的问题，我觉得可以从不同的角度去获取当前用户可读的schema信息，比如oracle可以这么获取：
SELECT DISTINCT(owner) FROM all_tab_comments WHERE owner NOT IN ('SYS','SYSTEM','ANONYMOUS','APEX_030200','APEX_PUBLIC_USER','APPQOSSYS','BI','CTXSYS','DBSNMP','DIP','EXFSYS','FLOWS_FILES','HR','IX','MDDATA','MDSYS','MGMT_VIEW','OE','OLAPSYS','ORACLE_OCM','ORDDATA','ORDPLUGINS','ORDSYS','OUTLN','OWBSYS','OWBSYS_AUDIT','PM','SCOTT','SH','SI_INFORMTN_SCHEMA','SPATIAL_CSW_ADMIN_USR','SPATIAL_WFS_ADMIN_USR','SYSMAN','WMSYS','XDB','XS$NULL');
后面过滤的都是oracle系统默认的系统schema。其他数据源应该也是可以的。
我是使用了第三方的数据库工具发现这个功能的，同样的用户，人家的工具可以拿到所有的schema，因为没有其他数据源，大家可以自己测试一下。

**Comment by WeiYe-Jing** [comment]
> 现在修复完成之后是可以不选择schema了，但是使用过程中还是能够选择schema的比较好。之前查不到schema都是权限不够的问题，我觉得可以从不同的角度去获取当前用户可读的schema信息，比如oracle可以这么获取：
> SELECT DISTINCT(owner) FROM all_tab_comments WHERE owner NOT IN ('SYS','SYSTEM','ANONYMOUS','APEX_030200','APEX_PUBLIC_USER','APPQOSSYS','BI','CTXSYS','DBSNMP','DIP','EXFSYS','FLOWS_FILES','HR','IX','MDDATA','MDSYS','MGMT_VIEW','OE','OLAPSYS','ORACLE_OCM','ORDDATA','ORDPLUGINS','ORDSYS','OUTLN','OWBSYS','OWBSYS_AUDIT','PM','SCOTT','SH','SI_INFORMTN_SCHEMA','SPATIAL_CSW_ADMIN_USR','SPATIAL_WFS_ADMIN_USR','SYSMAN','WMSYS','XDB','XS$NULL');
> 后面过滤的都是oracle系统默认的系统schema。其他数据源应该也是可以的。
> 我是使用了第三方的数据库工具发现这个功能的，同样的用户，人家的工具可以拿到所有的schema，因为没有其他数据源，大家可以自己测试一下。

可以直接用这个sql吗

**Comment by nightxing** [comment]
> > 现在修复完成之后是可以不选择schema了，但是使用过程中还是能够选择schema的比较好。之前查不到schema都是权限不够的问题，我觉得可以从不同的角度去获取当前用户可读的schema信息，比如oracle可以这么获取：
> > SELECT DISTINCT(owner) FROM all_tab_comments WHERE owner NOT IN ('SYS','SYSTEM','ANONYMOUS','APEX_030200','APEX_PUBLIC_USER','APPQOSSYS','BI','CTXSYS','DBSNMP','DIP','EXFSYS','FLOWS_FILES','HR','IX','MDDATA','MDSYS','MGMT_VIEW','OE','OLAPSYS','ORACLE_OCM','ORDDATA','ORDPLUGINS','ORDSYS','OUTLN','OWBSYS','OWBSYS_AUDIT','PM','SCOTT','SH','SI_INFORMTN_SCHEMA','SPATIAL_CSW_ADMIN_USR','SPATIAL_WFS_ADMIN_USR','SYSMAN','WMSYS','XDB','XS$NULL');
> > 后面过滤的都是oracle系统默认的系统schema。其他数据源应该也是可以的。
> > 我是使用了第三方的数据库工具发现这个功能的，同样的用户，人家的工具可以拿到所有的schema，因为没有其他数据源，大家可以自己测试一下。
> 
> 可以直接用这个sql吗

我的oracle部分就是这么用的，其他数据源就不清楚了。这个东西在dbeaver中应该都有类似的功能和代码吧

**Comment by WeiYe-Jing** [comment]
> > > 现在修复完成之后是可以不选择schema了，但是使用过程中还是能够选择schema的比较好。之前查不到schema都是权限不够的问题，我觉得可以从不同的角度去获取当前用户可读的schema信息，比如oracle可以这么获取：
> > > SELECT DISTINCT(owner) FROM all_tab_comments WHERE owner NOT IN ('SYS','SYSTEM','ANONYMOUS','APEX_030200','APEX_PUBLIC_USER','APPQOSSYS','BI','CTXSYS','DBSNMP','DIP','EXFSYS','FLOWS_FILES','HR','IX','MDDATA','MDSYS','MGMT_VIEW','OE','OLAPSYS','ORACLE_OCM','ORDDATA','ORDPLUGINS','ORDSYS','OUTLN','OWBSYS','OWBSYS_AUDIT','PM','SCOTT','SH','SI_INFORMTN_SCHEMA','SPATIAL_CSW_ADMIN_USR','SPATIAL_WFS_ADMIN_USR','SYSMAN','WMSYS','XDB','XS$NULL');
> > > 后面过滤的都是oracle系统默认的系统schema。其他数据源应该也是可以的。
> > > 我是使用了第三方的数据库工具发现这个功能的，同样的用户，人家的工具可以拿到所有的schema，因为没有其他数据源，大家可以自己测试一下。
> > 
> > 
> > 可以直接用这个sql吗
> 
> 我的oracle部分就是这么用的，其他数据源就不清楚了。这个东西在dbeaver中应该都有类似的功能和代码吧

我有空看看有没有更好的方式，本地没有安装oracle
