### ISSUE TITLE
hive 表无分区情况下构建任务读不出cloumns

### ISSUE THREAD

**Issue by xpcomrade** [WeiYe-Jing/datax-web#176]
hive 里面的部分表构建任务时读不出列 ？ 
目前发现一个现象是没有设置分区的情况下读不出。
是这样的嘛？

**Comment by WeiYe-Jing** [comment]
没遇到这个问题，数据源的用户名设置了吗

**Comment by WeiYe-Jing** [comment]
> hive 里面的部分表构建任务时读不出列 ？
> 目前发现一个现象是没有设置分区的情况下读不出。
> 是这样的嘛？

驱动版本检查一下，看看是不是hive版本一致的

**Comment by WeiYe-Jing** [comment]
你好，原因找到了吗？

**Comment by xpcomrade** [comment]
> > hive 里面的部分表构建任务时读不出列 ？
> > 目前发现一个现象是没有设置分区的情况下读不出。
> > 是这样的嘛？
> 
> 驱动版本检查一下，看看是不是hive版本一致的

我更改了pom中hadoop相关的jar版本 ，也无济于事

 <hadoop.version>3.0.3</hadoop.version>
 <hive.jdbc.version>2.1.1</hive.jdbc.version>
 <hbase.version>2.1.10</hbase.version>

hadoop相关版本，
`{
    "name": "hive",
    "pkg_release": "1605554",
    "pkg_version": "2.1.1+cdh6.3.2",
    "version": "2.1.1-cdh6.3.2"
}
{
    "name": "hadoop",
    "pkg_release": "1605554",
    "pkg_version": "3.0.0+cdh6.3.2",
    "version": "3.0.0-cdh6.3.2"
}
{
    "name": "hbase",
    "pkg_release": "1605554",
    "pkg_version": "2.1.0+cdh6.3.2",
    "version": "2.1.0-cdh6.3.2"
}

`

**Comment by WeiYe-Jing** [comment]
> > > hive 里面的部分表构建任务时读不出列 ？
> > > 目前发现一个现象是没有设置分区的情况下读不出。
> > > 是这样的嘛？
> > 
> > 
> > 驱动版本检查一下，看看是不是hive版本一致的
> 
> 我更改了pom中hadoop相关的jar版本 ，也无济于事
> 
> <hadoop.version>3.0.3</hadoop.version>
> <hive.jdbc.version>2.1.1</hive.jdbc.version>
> <hbase.version>2.1.10</hbase.version>
> 
> hadoop相关版本，
> `{
> "name": "hive",
> "pkg_release": "1605554",
> "pkg_version": "2.1.1+cdh6.3.2",
> "version": "2.1.1-cdh6.3.2"
> }
> {
> "name": "hadoop",
> "pkg_release": "1605554",
> "pkg_version": "3.0.0+cdh6.3.2",
> "version": "3.0.0-cdh6.3.2"
> }
> {
> "name": "hbase",
> "pkg_release": "1605554",
> "pkg_version": "2.1.0+cdh6.3.2",
> "version": "2.1.0-cdh6.3.2"
> }
> 
> `
方便的话，可以用连接中的pom替换下项目中的pom试下，麻烦了！https://github.com/WeiYe-Jing/datax-web/blob/dev/datax-admin/pom.xml

**Comment by xpcomrade** [comment]
> > > > hive 里面的部分表构建任务时读不出列 ？
> > > > 目前发现一个现象是没有设置分区的情况下读不出。
> > > > 是这样的嘛？
> > > 
> > > 
> > > 驱动版本检查一下，看看是不是hive版本一致的
> > 
> > 
> > 我更改了pom中hadoop相关的jar版本 ，也无济于事
> > <hadoop.version>3.0.3</hadoop.version>
> > <hive.jdbc.version>2.1.1</hive.jdbc.version>
> > <hbase.version>2.1.10</hbase.version>
> > hadoop相关版本，
> > `{
> > "name": "hive",
> > "pkg_release": "1605554",
> > "pkg_version": "2.1.1+cdh6.3.2",
> > "version": "2.1.1-cdh6.3.2"
> > }
> > {
> > "name": "hadoop",
> > "pkg_release": "1605554",
> > "pkg_version": "3.0.0+cdh6.3.2",
> > "version": "3.0.0-cdh6.3.2"
> > }
> > {
> > "name": "hbase",
> > "pkg_release": "1605554",
> > "pkg_version": "2.1.0+cdh6.3.2",
> > "version": "2.1.0-cdh6.3.2"
> > }
> > `
> > 方便的话，可以用连接中的pom替换下项目中的pom试下，麻烦了！https://github.com/WeiYe-Jing/datax-web/blob/dev/datax-admin/pom.xml

测试了一下，把datax-admin模块下的pom替换掉，还是不行。

**Comment by xpcomrade** [comment]
> > > > hive 里面的部分表构建任务时读不出列 ？
> > > > 目前发现一个现象是没有设置分区的情况下读不出。
> > > > 是这样的嘛？
> > > 
> > > 
> > > 驱动版本检查一下，看看是不是hive版本一致的
> > 
> > 
> > 我更改了pom中hadoop相关的jar版本 ，也无济于事
> > <hadoop.version>3.0.3</hadoop.version>
> > <hive.jdbc.version>2.1.1</hive.jdbc.version>
> > <hbase.version>2.1.10</hbase.version>
> > hadoop相关版本，
> > `{
> > "name": "hive",
> > "pkg_release": "1605554",
> > "pkg_version": "2.1.1+cdh6.3.2",
> > "version": "2.1.1-cdh6.3.2"
> > }
> > {
> > "name": "hadoop",
> > "pkg_release": "1605554",
> > "pkg_version": "3.0.0+cdh6.3.2",
> > "version": "3.0.0-cdh6.3.2"
> > }
> > {
> > "name": "hbase",
> > "pkg_release": "1605554",
> > "pkg_version": "2.1.0+cdh6.3.2",
> > "version": "2.1.0-cdh6.3.2"
> > }
> > `
> > 方便的话，可以用连接中的pom替换下项目中的pom试下，麻烦了！https://github.com/WeiYe-Jing/datax-web/blob/dev/datax-admin/pom.xml

在本地测试了一下可以了。多谢大侠。

**Comment by WeiYe-Jing** [comment]
> > > > > hive 里面的部分表构建任务时读不出列 ？
> > > > > 目前发现一个现象是没有设置分区的情况下读不出。
> > > > > 是这样的嘛？
> > > > 
> > > > 
> > > > 驱动版本检查一下，看看是不是hive版本一致的
> > > 
> > > 
> > > 我更改了pom中hadoop相关的jar版本 ，也无济于事
> > > <hadoop.version>3.0.3</hadoop.version>
> > > <hive.jdbc.version>2.1.1</hive.jdbc.version>
> > > <hbase.version>2.1.10</hbase.version>
> > > hadoop相关版本，
> > > `{ "name": "hive", "pkg_release": "1605554", "pkg_version": "2.1.1+cdh6.3.2", "version": "2.1.1-cdh6.3.2" } { "name": "hadoop", "pkg_release": "1605554", "pkg_version": "3.0.0+cdh6.3.2", "version": "3.0.0-cdh6.3.2" } { "name": "hbase", "pkg_release": "1605554", "pkg_version": "2.1.0+cdh6.3.2", "version": "2.1.0-cdh6.3.2" } `
> > > > 方便的话，可以用连接中的pom替换下项目中的pom试下，麻烦了！https://github.com/WeiYe-Jing/datax-web/blob/dev/datax-admin/pom.xml
> 
> 在本地测试了一下可以了。多谢大侠。

是将admin下的pom替换为连接中的pom之后问题解决的吗？

**Comment by xpcomrade** [comment]
> > > > > > hive 里面的部分表构建任务时读不出列 ？
> > > > > > 目前发现一个现象是没有设置分区的情况下读不出。
> > > > > > 是这样的嘛？
> > > > > 
> > > > > 
> > > > > 驱动版本检查一下，看看是不是hive版本一致的
> > > > 
> > > > 
> > > > 我更改了pom中hadoop相关的jar版本 ，也无济于事
> > > > <hadoop.version>3.0.3</hadoop.version>
> > > > <hive.jdbc.version>2.1.1</hive.jdbc.version>
> > > > <hbase.version>2.1.10</hbase.version>
> > > > hadoop相关版本，
> > > > `{ "name": "hive", "pkg_release": "1605554", "pkg_version": "2.1.1+cdh6.3.2", "version": "2.1.1-cdh6.3.2" } { "name": "hadoop", "pkg_release": "1605554", "pkg_version": "3.0.0+cdh6.3.2", "version": "3.0.0-cdh6.3.2" } { "name": "hbase", "pkg_release": "1605554", "pkg_version": "2.1.0+cdh6.3.2", "version": "2.1.0-cdh6.3.2" } `
> > > > > 方便的话，可以用连接中的pom替换下项目中的pom试下，麻烦了！https://github.com/WeiYe-Jing/datax-web/blob/dev/datax-admin/pom.xml
> > 
> > 
> > 在本地测试了一下可以了。多谢大侠。
> 
> 是将admin下的pom替换为连接中的pom之后问题解决的吗？

是的呢。

**Comment by WeiYe-Jing** [comment]
> > > > > > > hive 里面的部分表构建任务时读不出列 ？
> > > > > > > 目前发现一个现象是没有设置分区的情况下读不出。
> > > > > > > 是这样的嘛？
> > > > > > 
> > > > > > 
> > > > > > 驱动版本检查一下，看看是不是hive版本一致的
> > > > > 
> > > > > 
> > > > > 我更改了pom中hadoop相关的jar版本 ，也无济于事
> > > > > <hadoop.version>3.0.3</hadoop.version>
> > > > > <hive.jdbc.version>2.1.1</hive.jdbc.version>
> > > > > <hbase.version>2.1.10</hbase.version>
> > > > > hadoop相关版本，
> > > > > `{ "name": "hive", "pkg_release": "1605554", "pkg_version": "2.1.1+cdh6.3.2", "version": "2.1.1-cdh6.3.2" } { "name": "hadoop", "pkg_release": "1605554", "pkg_version": "3.0.0+cdh6.3.2", "version": "3.0.0-cdh6.3.2" } { "name": "hbase", "pkg_release": "1605554", "pkg_version": "2.1.0+cdh6.3.2", "version": "2.1.0-cdh6.3.2" } `
> > > > > > 方便的话，可以用连接中的pom替换下项目中的pom试下，麻烦了！https://github.com/WeiYe-Jing/datax-web/blob/dev/datax-admin/pom.xml
> > > 
> > > 
> > > 在本地测试了一下可以了。多谢大侠。
> > 
> > 
> > 是将admin下的pom替换为连接中的pom之后问题解决的吗？
> 
> 是的呢。

好的，谢谢！
