### ISSUE TITLE
2.1.2版本中不能同时设置hive分区和时间自增

### ISSUE THREAD

**Issue by nightxing** [WeiYe-Jing/datax-web#177]
当前最新的master版本同样存在这个问题，设置hive分区自增的情况下，没有办法同时设置数据库时间自增的查询，和readme中的结构不一样。执行任务时传入的参数和页面设置是一致的，不会同时传入三个参数。
这个功能还是很有必要的，希望能够恢复。另外，能够动态设置分区的话，希望能够自动创建该分区，这样就可以使用dataxweb构建一个完整的抽数过程，基本只需要页面交互了。

**Comment by WeiYe-Jing** [comment]
这个问题我尽快优化下，感谢建议！

**Comment by no-define** [comment]
+1，等待优化

**Comment by WeiYe-Jing** [comment]
> +1，等待优化

非常欢迎能参与此功能的开发，这样才能在最快时间内完成，不然只能等待下个版本，谢谢！

**Comment by WeiYe-Jing** [comment]
> 能够动态设置分区的话，希望能够自动创建该分区

动态创建分区目前需要通过脚本处理
