### ISSUE TITLE
保存的reader的where条件和writer的presql都没法在编辑画面中编辑

### ISSUE THREAD

**Issue by qin-su** [WeiYe-Jing/datax-web#179]
保存的reader的where条件和writer的presql都没法在编辑画面中编辑。任务只能删除重建。如果是保存在mysql中，是否删除也会同步？不然就有脏数据。

**Comment by WeiYe-Jing** [comment]
请描述清楚，那个版本，那个页面，什么操作

**Comment by WeiYe-Jing** [comment]
> 保存的reader的where条件和writer的presql都没法在编辑画面中编辑。任务只能删除重建。如果是保存在mysql中，是否删除也会同步？不然就有脏数据。

请先了解datax的使用规则，当用户配置querySql时，MysqlReader直接忽略table、column、where条件的配置，querySql优先级大于table、column、where选项。

**Comment by qin-su** [comment]
谢谢！看了文档，理解了。
