### ISSUE TITLE
executor服务器资源使用问题

### ISSUE THREAD

**Issue by WeiYe-Jing** [WeiYe-Jing/datax-web#18]
可以考虑一下自己写一下rpc的网关和负载均衡，如果没有将单个datax作业的executor拆分到多台执行服务器上的话，需要监控一个executor服务器上剩下的内存，不然机器上正在运行的作业会oom, 可以考虑一下把xxl的rpc改成蚂蚁开源的sofa-rpc, 然后自定义网关和负载均衡，作业推到执行器上，内存到达阀值就不再推了，延后

**Comment by waterWang** [comment]
- [ ] 执行器中收集机器内存等信息
- [ ] 自己写网关+负载，或升级xxl-rpc为sofa-rpc

**Comment by WeiYe-Jing** [comment]
计划先做admin,executor服务的内存,cpu收集

**Comment by WeiYe-Jing** [comment]
已完成监控executor服务器
