### ISSUE TITLE
源库表与目标库表字段类型映射优化

### ISSUE THREAD

**Issue by snycc15** [WeiYe-Jing/datax-web#188]
JSON任务构建中，如oracle同步到hive库，字段映射类型不能自定义或选择，一些场景下当前版本给出的类型，并不能完全适配实际生产中的数据格式，最终数据进入HIVE后会乱码或错误，建议进一步提供可选类型，用户可直接选系统给出映射类型，也可在此基础上进行部分修改。

**Comment by WeiYe-Jing** [comment]
已完成
