### ISSUE TITLE
shell任务和python任务执行无状态，终止任务无

### ISSUE THREAD

**Issue by heshan521521** [WeiYe-Jing/datax-web#199]
初次接触datax-web，部署完成后就开始配置任务。第一类datax任务很顺利执行成功。第二类shell任务一开始调试不成功，后来成功。。但是之前未成功的任务一直显示正在执行的状态，无法终止。。第三类任务是python任务，目前为止还没有成功，也无法终止 。
![image](https://user-images.githubusercontent.com/47143365/86990742-dd18c300-c1cf-11ea-96f9-4090f5c4c42a.png)

**Comment by WeiYe-Jing** [comment]
你好，帮忙看下，job_log中可以看下运行的数据，process_id有值吗？

**Comment by heshan521521** [comment]
> 你好，帮忙看下数据库表job_log中，对应的任务，process_id有值吗？

你好，process_id为空，
成功的都是有值的。

**Comment by WeiYe-Jing** [comment]
> > 你好，帮忙看下数据库表job_log中，对应的任务，process_id有值吗？
> 
> 你好，process_id为空，
> 成功的都是有值的。

好的，这个应该是个bug,我这边会加到开发计划中，也欢迎参与，谢谢！

**Comment by heshan521521** [comment]
> > > 你好，帮忙看下数据库表job_log中，对应的任务，process_id有值吗？
> > 
> > 
> > 你好，process_id为空，
> > 成功的都是有值的。
> 
> 好的，这个应该是个bug,我这边会加到开发计划中，也欢迎参与，谢谢！

谢谢！

**Comment by WeiYe-Jing** [comment]
> > > > 你好，帮忙看下数据库表job_log中，对应的任务，process_id有值吗？
> > > 
> > > 
> > > 你好，process_id为空，
> > > 成功的都是有值的。
> > 
> > 
> > 好的，这个应该是个bug,我这边会加到开发计划中，也欢迎参与，谢谢！
> 
> 谢谢！

python任务确定无法终止吗，我本地测试没遇到问题，正常终止，可以写个简单的demo试下吗。

**Comment by WeiYe-Jing** [comment]
> > > > > 你好，帮忙看下数据库表job_log中，对应的任务，process_id有值吗？
> > > > 
> > > > 
> > > > 你好，process_id为空，
> > > > 成功的都是有值的。
> > > 
> > > 
> > > 好的，这个应该是个bug,我这边会加到开发计划中，也欢迎参与，谢谢！
> > 
> > 
> > 谢谢！
> 
> python任务确定无法终止吗，我本地测试没遇到问题，正常终止，可以写个简单的demo试下吗。

我验证下来shell任务和python任务终止都是正常的，我的脚本如下
shell:
`#!/bin/bash
echo "datax-web: hello shell002"

echo "脚本位置：shell1"
sleep 30
echo "任务参数：shell2"
sleep 20
echo "Good bye!"
exit 0`

python:
`#!/usr/bin/python
# -*- coding: UTF-8 -*-
import time
import sys
print "DataX Web: hello python1111"
time.sleep(50)
print "Good bye!"
exit(0)`
