### ISSUE TITLE
任务管理页面上几个名词的解释

### ISSUE THREAD

**Issue by fxrs111** [WeiYe-Jing/datax-web#200]
任务管理的路由策略是什么意思，其中每一项(第一个、最后一个、轮询等)是什么意思呢？
![image](https://user-images.githubusercontent.com/46838109/86991929-cfdbe400-c18f-11ea-9b3b-b570d735a9c6.png)

**Comment by WeiYe-Jing** [comment]
> 任务管理的路由策略是什么意思，其中每一项(第一个、最后一个、轮询等)是什么意思呢？
> ![image](https://user-images.githubusercontent.com/46838109/86991929-cfdbe400-c18f-11ea-9b3b-b570d735a9c6.png)

#147 可以先看下这个issue,能解决你的疑惑吗？

**Comment by fxrs111** [comment]
好的，谢谢
