### ISSUE TITLE
希望可以构建一个docker-compose的安装包，方便快速构建项目[Feature]

### ISSUE THREAD

**Issue by yellowbright** [WeiYe-Jing/datax-web#202]

**Comment by WeiYe-Jing** [comment]
功能已有两位开发者提供。

1. 基于改变项目结构做的编排，目前项目打包结构是依赖包外置，通过脚本启动，此贡献是将项目整体打包为jar。
![image](https://user-images.githubusercontent.com/33245094/88457233-5f370600-ceb7-11ea-8d1b-80189ebc3fbd.png)

2.项目结构保持现有，但是没有做编排。
![image](https://user-images.githubusercontent.com/33245094/88457243-74139980-ceb7-11ea-9714-f0b5f1daf3a6.png)

希望的结果是给第二种方式添加docker-compose，感谢！

**Comment by shizeying** [comment]
功能已开发完毕
