### ISSUE TITLE
[QUESTION] 部署完成任务构建时找不到表

### ISSUE THREAD

**Issue by heshan521521** [WeiYe-Jing/datax-web#206]
你好，我部署datax-web 2.1.2时没有出现错误，但是在任务构建时无法找到数据库下的表。
提示：
13:41:39.036 admin [http-nio-9527-exec-8] ERROR c.w.d.a.t.q.BaseQueryTool - [getTableNames Exception] --> the exception message is:Can not issue NULL query
![image](https://user-images.githubusercontent.com/47143365/87120762-d4012200-c2b3-11ea-8cd6-adb8440f0fb5.png)

在数据源管理中测试连接配置是成功的：
![image](https://user-images.githubusercontent.com/47143365/87120742-c5b30600-c2b3-11ea-909a-f89e5563a7e1.png)

查看doc.html中也没有找到相应方法的说明。麻烦有空的时候指导一下如何排查问题出在哪里？

**Comment by WeiYe-Jing** [comment]
你好，是昨天下午从主分支获取的代码吗？昨天下午这个版本有这个问题，晚上已经修复了，需要更新一下代码，不好意思。

**Comment by heshan521521** [comment]
> 你好，是昨天下午从主分支获取的代码吗？昨天下午这个版本有这个问题，晚上已经修复了，需要更新一下代码，不好意思。

是的，昨天下午通过git clone的方式安装的

**Comment by WeiYe-Jing** [comment]
> > 你好，是昨天下午从主分支获取的代码吗？昨天下午这个版本有这个问题，晚上已经修复了，需要更新一下代码，不好意思。
> 
> 是的，昨天下午通过git clone的方式安装的

那需要更新一下代码，或者你可以直接使用一键部署文档中提供的安装包，安装包是打包好的。

**Comment by heshan521521** [comment]
> > > 你好，是昨天下午从主分支获取的代码吗？昨天下午这个版本有这个问题，晚上已经修复了，需要更新一下代码，不好意思。
> > 
> > 
> > 是的，昨天下午通过git clone的方式安装的
> 
> 那需要更新一下代码，或者你可以直接使用一键部署文档中提供的安装包，安装包是打包好的。

可以直接通过一键部署文档中提供的安装包进行覆盖吗？

**Comment by WeiYe-Jing** [comment]
> > > > 你好，是昨天下午从主分支获取的代码吗？昨天下午这个版本有这个问题，晚上已经修复了，需要更新一下代码，不好意思。
> > > 
> > > 
> > > 是的，昨天下午通过git clone的方式安装的
> > 
> > 
> > 那需要更新一下代码，或者你可以直接使用一键部署文档中提供的安装包，安装包是打包好的。
> 
> 可以直接通过一键部署文档中提供的安装包进行覆盖吗？

可以的

**Comment by heshan521521** [comment]
> > > > > 你好，是昨天下午从主分支获取的代码吗？昨天下午这个版本有这个问题，晚上已经修复了，需要更新一下代码，不好意思。
> > > > 
> > > > 
> > > > 是的，昨天下午通过git clone的方式安装的
> > > 
> > > 
> > > 那需要更新一下代码，或者你可以直接使用一键部署文档中提供的安装包，安装包是打包好的。
> > 
> > 
> > 可以直接通过一键部署文档中提供的安装包进行覆盖吗？
> 
> 可以的

好的，非常感谢你的答复。我先试一下。

**Comment by WeiYe-Jing** [comment]
> > > > > > 你好，是昨天下午从主分支获取的代码吗？昨天下午这个版本有这个问题，晚上已经修复了，需要更新一下代码，不好意思。
> > > > > 
> > > > > 
> > > > > 是的，昨天下午通过git clone的方式安装的
> > > > 
> > > > 
> > > > 那需要更新一下代码，或者你可以直接使用一键部署文档中提供的安装包，安装包是打包好的。
> > > 
> > > 
> > > 可以直接通过一键部署文档中提供的安装包进行覆盖吗？
> > 
> > 
> > 可以的
> 
> 好的，非常感谢你的答复。我先试一下。

问题解决了吗
