### ISSUE TITLE
pgsql获取表字段有bug

### ISSUE THREAD

**Issue by zhengsw91** [WeiYe-Jing/datax-web#207]
我有一张表名Moment,获取字段列表的sql如下
SELECT * FROM Moment where 1=0

SELECT * FROM Moment where 1=0
ERROR:  relation "moment" does not exist
LINE 1: SELECT * FROM Moment where 1=0
                      ^

时间: 0.002s

pgsql查询大写字母的表,需要带双引
SELECT * FROM “Moment” where 1=0

**Comment by liukunyuan** [comment]
啥数据库

**Comment by zhengsw91** [comment]
postgres
而且我校验了,这种写法查不出 单表的所有字段名

考虑下这种写法
select column_name from information_schema.columns
where table_name='表名'

**Comment by zhengsw91** [comment]
> 啥数据库
postgres
而且我校验了,这种写法查不出 单表的所有字段名

考虑下这种写法
select column_name from information_schema.columns
where table_name='表名'

**Comment by WeiYe-Jing** [comment]
> > 啥数据库
> 
> postgres
> 而且我校验了,这种写法查不出 单表的所有字段名
> 
> 考虑下这种写法
> select column_name from information_schema.columns
> where table_name='表名'

postgres的版本可以回复下吗，我这边试试，我用gp没遇到这个问题。

**Comment by zhengsw91** [comment]
> > > 啥数据库
> > 
> > 
> > postgres
> > 而且我校验了,这种写法查不出 单表的所有字段名
> > 考虑下这种写法
> > select column_name from information_schema.columns
> > where table_name='表名'
> 
> postgres的版本可以回复下吗，我这边试试，我用gp没遇到这个问题。


PostgreSQL 11.5, compiled by Visual C++ build 1914, 64-bit

**Comment by zhengsw91** [comment]
> > > 啥数据库
> > 
> > 
> > postgres
> > 而且我校验了,这种写法查不出 单表的所有字段名
> > 考虑下这种写法
> > select column_name from information_schema.columns
> > where table_name='表名'
> 
> postgres的版本可以回复下吗，我这边试试，我用gp没遇到这个问题。

我早上在本地机器上安装了PostgreSQL 9.5.22, compiled by Visual C++ build 1800, 64-bit
测试了下没问题。

高版本可能支持不了。

**Comment by zhengsw91** [comment]
> > > 啥数据库
> > 
> > 
> > postgres
> > 而且我校验了,这种写法查不出 单表的所有字段名
> > 考虑下这种写法
> > select column_name from information_schema.columns
> > where table_name='表名'
> 
> postgres的版本可以回复下吗，我这边试试，我用gp没遇到这个问题。

补充说明
之前我以为是版本的关系（其实不是）。我刚才自己测试了下，正好我的表名是user,跟系统表有冲突导致
select * from user where 1=0 (不通过)
select * from public.user where 1= 0 (通过)

还有一个问题不支持大写字母开头的表名
select * from Doc where 1=0 (不通过)
select * from "Doc" where 1=0(通过)
select * from  public."Doc" where 1=0 (通过)

**Comment by WeiYe-Jing** [comment]
> > > > 啥数据库
> > > 
> > > 
> > > postgres
> > > 而且我校验了,这种写法查不出 单表的所有字段名
> > > 考虑下这种写法
> > > select column_name from information_schema.columns
> > > where table_name='表名'
> > 
> > 
> > postgres的版本可以回复下吗，我这边试试，我用gp没遇到这个问题。
> 
> 补充说明
> 之前我以为是版本的关系（其实不是）。我刚才自己测试了下，正好我的表名是user,跟系统表有冲突导致
> select * from user where 1=0 (不通过)
> select * from public.user where 1= 0 (通过)
> 
> 还有一个问题不支持大写字母开头的表名
> select * from Doc where 1=0 (不通过)
> select * from "Doc" where 1=0(通过)
> select * from public."Doc" where 1=0 (通过)

非常感谢能详细的描述问题，是表名和数据库保留关键词相同的问题，下个版本我对表名加个标识符例如pg(""),sqlserver([]),mysql(``)等

**Comment by WeiYe-Jing** [comment]
#249 已完成
