### ISSUE TITLE
执行datax shell脚本失败，未捕获到HDFS HA切换异常

### ISSUE THREAD

**Issue by jon-qj** [WeiYe-Jing/datax-web#213]
异常如下：
![图片](https://user-images.githubusercontent.com/39773194/87273103-c7c2d200-c50a-11ea-8c63-36f7f3d576e2.png)
 脚本如下：
![图片](https://user-images.githubusercontent.com/39773194/87273510-e5446b80-c50b-11ea-99b5-d224859be4f9.png)
 第二个shell命令时执行失败，没有及时停止任务，导致最后任务状态提示成功

**Comment by WeiYe-Jing** [comment]
> 异常如下：
> ![图片](https://user-images.githubusercontent.com/39773194/87273103-c7c2d200-c50a-11ea-8c63-36f7f3d576e2.png)
> 脚本如下：
> ![图片](https://user-images.githubusercontent.com/39773194/87273510-e5446b80-c50b-11ea-99b5-d224859be4f9.png)
> 第二个shell命令时执行失败，没有及时停止任务，导致最后任务状态提示成功

这是完整的脚本吗

**Comment by jon-qj** [comment]
> 
> 
> > 异常如下：
> > ![图片](https://user-images.githubusercontent.com/39773194/87273103-c7c2d200-c50a-11ea-8c63-36f7f3d576e2.png)
> > 脚本如下：
> > ![图片](https://user-images.githubusercontent.com/39773194/87273510-e5446b80-c50b-11ea-99b5-d224859be4f9.png)
> > 第二个shell命令时执行失败，没有及时停止任务，导致最后任务状态提示成功
> 
> 这是完整的脚本吗,结尾有exit 0吗

![图片](https://user-images.githubusercontent.com/39773194/87273944-00fc4180-c50d-11ea-8026-9b4bb12ddd0c.png)
执行的是datax.py 的脚本 自带了一个exit 是否需要对
![图片](https://user-images.githubusercontent.com/39773194/87274000-2d17c280-c50d-11ea-98e0-d4047b309ea3.png)
该行命令进行判断呢？

**Comment by WeiYe-Jing** [comment]
> > > 异常如下：
> > > ![图片](https://user-images.githubusercontent.com/39773194/87273103-c7c2d200-c50a-11ea-8c63-36f7f3d576e2.png)
> > > 脚本如下：
> > > ![图片](https://user-images.githubusercontent.com/39773194/87273510-e5446b80-c50b-11ea-99b5-d224859be4f9.png)
> > > 第二个shell命令时执行失败，没有及时停止任务，导致最后任务状态提示成功
> > 
> > 
> > 这是完整的脚本吗,结尾有exit 0吗
> 
> ![图片](https://user-images.githubusercontent.com/39773194/87273944-00fc4180-c50d-11ea-8026-9b4bb12ddd0c.png)
> 执行的是datax.py 的脚本 自带了一个exit 是否需要对
> ![图片](https://user-images.githubusercontent.com/39773194/87274000-2d17c280-c50d-11ea-98e0-d4047b309ea3.png)
> 该行命令进行判断呢？

需要判断的，可以试试

**Comment by jon-qj** [comment]
已确认 确实需要exit 非0  方可结束当前进程

**Comment by WeiYe-Jing** [comment]
> 已确认 确实需要exit 非0 方可结束当前进程

问题解决了吗，没问题issue就关掉了
