### ISSUE TITLE
powershell输出内容乱码

### ISSUE THREAD

**Issue by DaggerBambooShoots** [WeiYe-Jing/datax-web#215]
有大佬知道怎么解决吗
![WXAAQS8EO(EZ5ZTIFZLP6UP](https://user-images.githubusercontent.com/57475908/87286221-28620700-c52b-11ea-9883-2e9e483c8725.png)

**Comment by DaggerBambooShoots** [comment]
> 有大佬知道怎么解决吗
![WXAAQS8EO(EZ5ZTIFZLP6UP](https://user-images.githubusercontent.com/57475908/87286335-51829780-c52b-11ea-82ad-397fafbd2f60.png)

**Comment by WeiYe-Jing** [comment]
> 有大佬知道怎么解决吗
> ![WXAAQS8EO(EZ5ZTIFZLP6UP](https://user-images.githubusercontent.com/57475908/87286221-28620700-c52b-11ea-9883-2e9e483c8725.png)

test\test.txt是什么，请严格按照文档配置。

**Comment by DaggerBambooShoots** [comment]
@WeiYe-Jing 后面那个是java代码里读取一个文件输出里面内容 我把他删了就报错了  那个没啥影响  前面就是单纯的输出了几句中文他就乱码了   这是是我拿来测试用的

**Comment by WeiYe-Jing** [comment]
> @WeiYe-Jing 后面那个是java代码里读取一个文件输出里面内容 我把他删了就报错了 那个没啥影响 前面就是单纯的输出了几句中文他就乱码了 这是是我拿来测试用的

我本地测试了下，没遇到这个问题，你可以先在网上查查资料看有没有解决方案

**Comment by WeiYe-Jing** [comment]
> @WeiYe-Jing 后面那个是java代码里读取一个文件输出里面内容 我把他删了就报错了 那个没啥影响 前面就是单纯的输出了几句中文他就乱码了 这是是我拿来测试用的

你好，问题解决了吗
