### ISSUE TITLE
阻塞任务的疑问

### ISSUE THREAD

**Issue by fxrs111** [WeiYe-Jing/datax-web#216]
在创建任务的时候会有一个阻塞处理的概念， 那什么时候算是达到了触发阻塞处理的峰值了呢。

举一个例子：如果存在两个任务同时使用执行器去执行任务（任务1先进 2后进），其中任务设置的阻塞处理都是丢弃后续，是否是代表任务2会被舍弃？

**Comment by WeiYe-Jing** [comment]
> 在创建任务的时候会有一个阻塞处理的概念， 那什么时候算是达到了触发阻塞处理的峰值了呢。
> 
> 举一个例子：如果存在两个任务同时使用执行器去执行任务（任务1先进 2后进），其中任务设置的阻塞处理都是丢弃后续，是否是代表任务2会被舍弃？

阻塞策略是争对单个任务而言的，例如：丢弃后续任务 A任务设置的每5秒执行一次，但是datax整个启动过程需要11秒，在任务第一次执行过程中，A任务会触发两次，当A任务第二次调度触发的时候，第一次触发还在运行中，那么第二次调度就会直接失败，这就是丢弃后续策略的原理。

**Comment by fxrs111** [comment]
那是否是我理解的这样，譬如：现在我有10个任务需要执行(默认：阻塞处理都是丢弃后续)，10个任务之间的执行间隔都是1秒，那这10个任务在使用同一个执行器去执行的时候都会正常执行，而不会被丢弃； 假如刚好这10个任务每单个任务执行的周期是5秒，是否是会把每个任务后续 的任务全部丢弃(每个任务之前的任务还都在执行)。

是否是我理解的这种说法呢，谢谢！

**Comment by WeiYe-Jing** [comment]
> 那是否是我理解的这样，譬如：现在我有10个任务需要执行(默认：阻塞处理都是丢弃后续)，10个任务之间的执行间隔都是1秒，那这10个任务在使用同一个执行器去执行的时候都会正常执行，而不会被丢弃； 假如刚好这10个任务每单个任务下一次执行是5秒后触发，每个任务的执行时间都是11秒，是否是会把每个任务后续 的任务全部丢弃(每个任务之前的任务还都在执行)。
> 
> 是否是我理解的这种说法呢，谢谢！

理解完全正确！

**Comment by fxrs111** [comment]
那如果是这种处理方式的话，还有一个问题， 假如我有两个任务(A、B设置的执行开始时间相同，且使用同一个执行器)将要执行， 那这两个任务是使用串行的方式执行并行执行；
恰好，这两个任务中都调用的子任务中同时都包含某一个任务C(阻塞处理设置的是丢弃后续)，那是否会存在A或B任务中有一个调用子任务C的会失败呢。

谢谢！

**Comment by WeiYe-Jing** [comment]
> 那如果是这种处理方式的话，还有一个问题， 假如我有两个任务(A、B设置的执行开始时间相同，且使用同一个执行器)将要执行， 那这两个任务是使用串行的方式执行并行执行；
> 恰好，这两个任务中都调用的子任务中同时都包含某一个任务C(阻塞处理设置的是丢弃后续)，那是否会存在A或B任务中有一个调用子任务C的会失败呢。
> 
> 谢谢！

会存在你说的这个问题，C可能会被执行两次，如果第一次正在执行，第二次触发会直接失败。

**Comment by fxrs111** [comment]
那如果出现了这种情况，是否有什么其他的处理方式呢

**Comment by WeiYe-Jing** [comment]
> 那如果出现了这种情况，是否有什么其他的处理方式呢
你是想怎么处理呢，A或B调用C都执行成功吗，如果都成功那C不要设置丢弃，让执行两次。

**Comment by WeiYe-Jing** [comment]
> > 那如果出现了这种情况，是否有什么其他的处理方式呢

 你是想怎么处理呢，A或B调用C都执行成功吗，如果都成功那C不要设置丢弃，让执行两次。

**Comment by fxrs111** [comment]
好的，了解了，谢谢！
