### ISSUE TITLE
请问下，从Oracle（ZHS16GBK编码）导入到mysql中的数据中文乱码怎么解决？

### ISSUE THREAD

**Issue by 773618713** [WeiYe-Jing/datax-web#219]
我在使用datax-web从Oracle（ZHS16GBK编码）导入到mysql中的数据全部乱码，变成“？？？？？”。请问有什么好的解决方法吗？

**Comment by WeiYe-Jing** [comment]
> 我在使用datax-web从Oracle（ZHS16GBK编码）导入到mysql中的数据全部乱码，变成“？？？？？”。请问有什么好的解决方法吗？

数据库中的数据中文乱码解决：在json文件中jdbcUrl项加上：?characterEncoding=utf8
或者在项目数据源jdbcUrl中加: characterEncoding=utf8即["jdbc:mysql://127.0.0.1:3306/xx?characterEncoding=utf8"]

**Comment by 773618713** [comment]
如果在jdbcUrl项加上：?characterEncoding=utf8 后，再次执行会报错
![image](https://user-images.githubusercontent.com/29975555/87422232-dd1f2580-c60a-11ea-864e-5cb7628b2638.png)
则按照以下方法，修改数据库对应字段的编码即可。
![image](https://user-images.githubusercontent.com/29975555/87422092-97faf380-c60a-11ea-9ffc-95f51a981e45.png)
