### ISSUE TITLE
执行器的疑问

### ISSUE THREAD

**Issue by fxrs111** [WeiYe-Jing/datax-web#225]
你好，由于在使用的时大部分会考虑使用集群的方式去实现，通过了解咱们Datax-Web是通过执行器集群的方式实现了Datax数据传输的集群操作，咱们的执行器集群的说明是
【
AppName: （与datax-executor中application.yml的datax.job.executor.appname保持一致）每个执行器集群的唯一标示AppName, 执行器会周期性以AppName为对象进行自动注册。可通过该配置自动发现注册成功的执行器, 供任务调度时使用;
】，其中我想咨询的什么算是执行器集群呢，我举一个例子描述下：
例如1：有两个执行器A和B，其中A和B在使用WEB页面手动创建执行器时使用了相同的appname和名称，那么A和B算是一个执行器集群吗(代表exec01执行器是有四个节点的集群还是A、B各自是独立的集群)，在任务创建后使用执行器时会动态随机的分派到A或者B吗？

![image](https://user-images.githubusercontent.com/46838109/87742044-76019c80-c7d5-11ea-8d7f-e436a930d7e9.png)
![image](https://user-images.githubusercontent.com/46838109/87742081-87e33f80-c7d5-11ea-94d1-f32493f38deb.png)

例如2：通过后台配置文件的方式，假如在执行器启动时后台多个执行器工程使用了相同的appname，服务启动之后发现一个执行器下存在多个服务节点，这种的方式是集群还是举例1的也是集群呢 ，  若任务分派时会随机或均衡的分派吗

**Comment by WeiYe-Jing** [comment]
> 你好，由于在使用的时大部分会考虑使用集群的方式去实现，通过了解咱们Datax-Web是通过执行器集群的方式实现了Datax数据传输的集群操作，咱们的执行器集群的说明是
> 【
> AppName: （与datax-executor中application.yml的datax.job.executor.appname保持一致）每个执行器集群的唯一标示AppName, 执行器会周期性以AppName为对象进行自动注册。可通过该配置自动发现注册成功的执行器, 供任务调度时使用;
> 】，其中我想咨询的什么算是执行器集群呢，我举一个例子描述下：
> 例如1：有两个执行器A和B，其中A和B在使用WEB页面手动创建执行器时使用了相同的appname和名称，那么A和B算是一个执行器集群吗(代表exec01执行器是有四个节点的集群还是A、B各自是独立的集群)，在任务创建后使用执行器时会动态随机的分派到A或者B吗？
> 
> ![image](https://user-images.githubusercontent.com/46838109/87742044-76019c80-c7d5-11ea-8d7f-e436a930d7e9.png)
> ![image](https://user-images.githubusercontent.com/46838109/87742081-87e33f80-c7d5-11ea-94d1-f32493f38deb.png)
> 
> 例如2：通过后台配置文件的方式，假如在执行器启动时后台多个执行器工程使用了相同的appname，服务启动之后发现一个执行器下存在多个服务节点，这种的方式是集群还是举例1的也是集群呢 ， 若任务分派时会随机或均衡的分派吗

例1：A和B是两个独立的执行器集群，任务在执行的时候会根据你任务中配置的路由策略从101和102两个节点中选择一个节点去执行。
例2：如果多个执行器配置了相同的appname,那这些执行器可以理解为一个集群，任务如果选择这个执行器，任务的分配还是和例1一样，由路由策略决定具体那个节点执行任务。

**Comment by fxrs111** [comment]
也就是说例1即使我两个执行器使用相同的appname，系统也是默认为是两个独立的集群(每个集群下有两个执行器节点)而不是当做是一个集群下的四个节点吗?

**Comment by WeiYe-Jing** [comment]
> 也就是说例1即使我两个执行器使用相同的appname，系统也是默认为是两个独立的集群(每个集群下有两个执行器节点)而不是当做是一个集群下的四个节点吗?

是的，是两个独立的集群，任务执行的时候先去找这个group，再获取下面的节点做路由处理

**Comment by fxrs111** [comment]
好的，了解
