### ISSUE TITLE
[Feature]增加对安装的常用软件进行校验，自动提示用户是否安装正确

### ISSUE THREAD

**Issue by liukunyuan** [WeiYe-Jing/datax-web#236]
1.目前很多用户将pypath的路径设置成了python的环境。项目应该增加智能校验模块，自动判断datax环境是否安装正确
2.目前datax的python环境是写死的python,需要增加PYTHON_HOME，用户可以自定义python路径。项目也需要判断python的版本是否是2.X
---------
判断时机：
1.在datax-web的executor启动中，需要通过log日志将判断结果打印出来
2.在页面的构建模块第一页，或者第二页进行弹窗或者其他友好提示

**Comment by wangAoqi666** [comment]
正在开发中....

**Comment by WeiYe-Jing** [comment]
已完成
