### ISSUE TITLE
选择Oracle数据源拉取不到数据表和Schema的信息

### ISSUE THREAD

**Issue by shiyinhao1** [WeiYe-Jing/datax-web#242]
*For better global communication, please give priority to using English description, thx! *

**Describe the question**
A clear and concise description of what the question is.

**Which version of DataX Web:**
 -[2.1.2]

**Additional context**

**Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by WeiYe-Jing** [comment]
> *For better global communication, please give priority to using English description, thx! *
> 
> **Describe the question**
> A clear and concise description of what the question is.
> 
> **Which version of DataX Web:**
> -[2.1.2]
> 
> **Additional context**
> Add any other context about the problem here.
> 
> **Requirement or improvement
> 
> * Please describe about your requirements or improvement suggestions.

看下这个issue，能帮到你吗？#175，或者帮忙验证下issue中的sql

**Comment by WeiYe-Jing** [comment]
合并到 #243
