### ISSUE TITLE
构建任务时，Oracle普通用户没有查询用户的权限。

### ISSUE THREAD

**Issue by 773618713** [WeiYe-Jing/datax-web#243]
构建任务时，选取数据源为Oracle数据的普通用户，查询用户（Schema）会报错：
```
ERROR c.w.d.a.t.q.BaseQueryTool - [getTableNames Exception] --> the exception message is:ORA-00942: table or view does not exist
```

是否可以更换以下方法的查询代码呢？
```java
    @Override
    public String getSQLQueryTableSchema(String... args) {
        return "select username from sys.dba_users";
    }
```
更换后的代码：
```java
    @Override
    public String getSQLQueryTableSchema(String... args) {
        return "select username  from all_users";
    }
```

**Comment by WeiYe-Jing** [comment]
> 构建任务时，选取数据源为Oracle数据的普通用户，查询用户（Schema）会报错：
> 
> ```
> ERROR c.w.d.a.t.q.BaseQueryTool - [getTableNames Exception] --> the exception message is:ORA-00942: table or view does not exist
> ```
> 
> 是否可以更换以下方法的查询代码呢？
> 
> ```java
>     @Override
>     public String getSQLQueryTableSchema(String... args) {
>         return "select username from sys.dba_users";
>     }
> ```
> 
> 更换后的代码：
> 
> ```java
>     @Override
>     public String getSQLQueryTableSchema(String... args) {
>         return "select username  from all_users";
>     }
> ```

谢谢建议，更换后的sql测试能通过吗，非常希望您能参与项目开发，提PR解决这个问题，感谢！

**Comment by WeiYe-Jing** [comment]
> > 构建任务时，选取数据源为Oracle数据的普通用户，查询用户（Schema）会报错：
> > ```
> > ERROR c.w.d.a.t.q.BaseQueryTool - [getTableNames Exception] --> the exception message is:ORA-00942: table or view does not exist
> > ```
> > 
> > 
> > 是否可以更换以下方法的查询代码呢？
> > ```java
> >     @Override
> >     public String getSQLQueryTableSchema(String... args) {
> >         return "select username from sys.dba_users";
> >     }
> > ```
> > 
> > 
> > 更换后的代码：
> > ```java
> >     @Override
> >     public String getSQLQueryTableSchema(String... args) {
> >         return "select username  from all_users";
> >     }
> > ```
> 
> 谢谢建议，更换后的sql测试能通过吗，非常希望您能参与项目开发，提PR解决这个问题，感谢！

对于user的获取你也可以参考下 #175 issue中提出的方式，做个选择。这个功能优化也在下个版本计划中，如果有好的选择也请回复下，感谢！

**Comment by WeiYe-Jing** [comment]
#247

**Comment by jiayb** [comment]
我的解决方法：OracleDatabaseMeta这个类里面修改如下 ，未注释的为修改后的代码    @Override
    public String getSQLQueryTables(String... tableSchema) {
//        return "select table_name from dba_tables where owner='" + tableSchema[0] + "'";
        return "select '" + tableSchema[0] + "'" + "||" + "'.'" + "||" + "table_name from dba_tables where owner='" + tableSchema[0] + "'";
    }
