### ISSUE TITLE
表名称大写时，PostgreSQL无法获取列名称

### ISSUE THREAD

**Issue by 773618713** [WeiYe-Jing/datax-web#244]
getColumns方法、batchAdd方法在获取列名称时，是否可以替换下表名称，如下方法所示：

```java
        if (tableName.indexOf(".") >= 0) {
            int idx = tableName.indexOf(".");
            String preStr = tableName.substring(0, idx);
            String suffixStr = tableName.substring(idx + 1);
            tableName = preStr + ".\"" + suffixStr + "\"";
        }else {
            tableName = "\"" + tableName + "\"";
        }
```

**Comment by WeiYe-Jing** [comment]
> getColumns方法、batchAdd方法在获取列名称时，是否可以替换下表名称，如下方法所示：
> 
> ```java
>         if (tableName.indexOf(".") >= 0) {
>             int idx = tableName.indexOf(".");
>             String preStr = tableName.substring(0, idx);
>             String suffixStr = tableName.substring(idx + 1);
>             tableName = preStr + ".\"" + suffixStr + "\"";
>         }else {
>             tableName = "\"" + tableName + "\"";
>         }
> ```

项目目前的实现方式看了吗，是用jdbc通用的方式getMetaData获取，建议研究下为什么大写查不出来，未找到原因之前不建议替换表名

**Comment by 773618713** [comment]
我看了下我本地的代码，jdbc通用的方式getMetaData获取字段名，这里是没有问题的。问题出现在表名称上。

下面的sql查询的并非 STUDENT 表，而是 student 表。PostgreSQL是对表名称大小写敏感的，
```
select * from STUDENT;
```

下面的sql查询的才是 STUDENT 表。
```
select * from "STUDENT";
```

也就是说在PostgreSQL中，执行SQL语句时，会把所有表名的字符串转换成小写。
这个问题在Oracle中也是存在的，而且正好相反，Oracle 会将数据库中的表名称默认转换成大写。
在个问题在mysql中不存在的，而且mysql的表名称加入“”，会有问题。
这里可能需要针对不通的数据库进行处理了。

**Comment by WeiYe-Jing** [comment]
> 我看了下我本地的代码，jdbc通用的方式getMetaData获取字段名，这里是没有问题的。问题出现在表名称上。
> 
> 下面的sql查询的并非 STUDENT 表，而是 student 表。PostgreSQL是对表名称大小写敏感的，
> 
> ```
> select * from STUDENT;
> ```
> 
> 下面的sql查询的才是 STUDENT 表。
> 
> ```
> select * from "STUDENT";
> ```
> 
> 也就是说在PostgreSQL中，执行SQL语句时，会把所有表名的字符串转换成小写。
> 这个问题在Oracle中也是存在的，而且正好相反，Oracle 会将数据库中的表名称默认转换成大写。
> 在个问题在mysql中不存在的，而且mysql的表名称加入“”，会有问题。
> 这里可能需要针对不通的数据库进行处理了。

感谢详细的描述，如果是这样getColumnNames方法可以加个转换method，对PostgreSQL和Oracle对做下处理。这块可以放到下个版本2.1.3中，也非常欢迎你能贡献这个功能。

**Comment by WeiYe-Jing** [comment]
#249 已完成
