### ISSUE TITLE
bug：找不到类型：hbase

### ISSUE THREAD

**Issue by dudefu** [WeiYe-Jing/datax-web#252]
![image](https://user-images.githubusercontent.com/5269023/88269940-7636f600-cd07-11ea-96e6-bbbf8d797837.png)

**Comment by WeiYe-Jing** [comment]
hbase-client的版本需要核对下是不是一致呢

**Comment by dudefu** [comment]
我看了代码，应该跟版本没关系，因为该错误不影响数据的导入，我的HBASE版本是2.0的。
![image](https://user-images.githubusercontent.com/5269023/88309373-cc745b00-cd40-11ea-8bbe-4cb971a7aa01.png)
构建任务，选择数据源后会进入该代码，因为没有HBASE匹配，所以报错。我觉得如果是HBASE类型的话，不应该进入该段代码，如果是Phoenix连接的话则进入该代码。
![image](https://user-images.githubusercontent.com/5269023/88309420-dd24d100-cd40-11ea-8a44-3259c3fd555c.png)
版本有要求吗？POM上面版本是1.3，如果是2.x版本的HBASE，连接的时候会报错，如果是2.x,pom文件hbase版本需要改为2.x版本的。

**Comment by WeiYe-Jing** [comment]
> 我看了代码，应该跟版本没关系，因为该错误不影响数据的导入，我的HBASE版本是2.0的。
> ![image](https://user-images.githubusercontent.com/5269023/88309373-cc745b00-cd40-11ea-8bbe-4cb971a7aa01.png)
> 构建任务，选择数据源后会进入该代码，因为没有HBASE匹配，所以报错。我觉得如果是HBASE类型的话，不应该进入该段代码，如果是Phoenix连接的话则进入该代码。
> ![image](https://user-images.githubusercontent.com/5269023/88309420-dd24d100-cd40-11ea-8a44-3259c3fd555c.png)
> 版本有要求吗？POM上面版本是1.3，如果是2.x版本的HBASE，连接的时候会报错，如果是2.x,pom文件hbase版本需要改为2.x版本的。

你这边代码是从那个分支或者版本获取的呢，对于HBase是一套单独的获取DBType方式。对于HBase数据源，你本地的代码前端页面不应该调用getDBSchema method。

**Comment by dudefu** [comment]
我获取的最新的master代码，选取数据源类型的时候，确实是发送了getDBSchema请求
![image](https://user-images.githubusercontent.com/5269023/88353013-8514bb80-cd8e-11ea-9bc1-257fd6fa2e5f.png)

**Comment by WeiYe-Jing** [comment]
> 我获取的最新的master代码，选取数据源类型的时候，确实是发送了getDBSchema请求
> ![image](https://user-images.githubusercontent.com/5269023/88353013-8514bb80-cd8e-11ea-9bc1-257fd6fa2e5f.png)

好的，我试下

**Comment by WeiYe-Jing** [comment]
> > 我获取的最新的master代码，选取数据源类型的时候，确实是发送了getDBSchema请求
> > ![image](https://user-images.githubusercontent.com/5269023/88353013-8514bb80-cd8e-11ea-9bc1-257fd6fa2e5f.png)
> 
> 好的，我试下

可以更新下代码再试下，谢谢！

**Comment by dudefu** [comment]
OK，谢谢
