### ISSUE TITLE
web界面密码报错

### ISSUE THREAD

**Issue by qinghuiguo** [WeiYe-Jing/datax-web#263]
admin/123456
通过该密码登录web界面，报用户名密码错误

**Comment by WeiYe-Jing** [comment]
> admin/123456
> 通过该密码登录web界面，报用户名密码错误

1. 首先检查下admin启动日志，看看有没有错误信息
2. 项目sql文件执行了吗，检查下项目数据库sql运行有没有失败的
3.检查下数据库连接配置的对不对

**Comment by qinghuiguo** [comment]
新部署的环境，其他未配置。
admin 中有报错信息：
15:35:28.820 admin [datax-web, admin JobScheduleHelper#scheduleThread] ERROR c.w.d.a.c.t.JobScheduleHelper - >>>>>>>>>>> datax-web, JobScheduleHelper#scheduleThread error:{}
java.sql.SQLException: Your password has expired. To log in you must change it using a client that supports expired passwords.

**Comment by WeiYe-Jing** [comment]
> 新部署的环境，其他未配置。
> admin 中有报错信息：
> 15:35:28.820 admin [datax-web, admin JobScheduleHelper#scheduleThread] ERROR c.w.d.a.c.t.JobScheduleHelper - >>>>>>>>>>> datax-web, JobScheduleHelper#scheduleThread error:{}
> java.sql.SQLException: Your password has expired. To log in you must change it using a client that supports expired passwords.

这个提示已经不能再明确了

**Comment by qinghuiguo** [comment]
mysql的密码需要重置，谢啦
