### ISSUE TITLE
JVM启动参数设置后，运行任务报错

### ISSUE THREAD

**Issue by zhaoyong1229** [WeiYe-Jing/datax-web#264]
*For better global communication, please give priority to using English description, thx! *

**Describe the bug**
JVM启动参数设置后，运行任务报错

**To Reproduce**
Steps to reproduce the behavior, for example:
1. 进入任务管理
2. 选择任务，点击编辑
3. JVM启动参数，设置-Xms1024m -Xmx1024m，点击保存
4. 这个任务运行时，报Invalid maximum heap size: -Xmx1024m

**Expected behavior**
任务应该正常运行

**Screenshots**
![image](https://user-images.githubusercontent.com/69296484/89508038-ebbebe00-d7ff-11ea-85f7-a3e396fb4332.png)
![image](https://user-images.githubusercontent.com/69296484/89508149-13ae2180-d800-11ea-9104-a01c93671674.png)

**Which version of DataX Web:**
 -[2.1.2]

**Additional context**

**Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by WeiYe-Jing** [comment]
> *For better global communication, please give priority to using English description, thx! *
> 
> **Describe the bug**
> JVM启动参数设置后，运行任务报错
> 
> **To Reproduce**
> Steps to reproduce the behavior, for example:
> 
> 1. 进入任务管理
> 2. 选择任务，点击编辑
> 3. JVM启动参数，设置-Xms1024m -Xmx1024m，点击保存
> 4. 这个任务运行时，报Invalid maximum heap size: -Xmx1024m
> 
> **Expected behavior**
> 任务应该正常运行
> 
> **Screenshots**
> ![image](https://user-images.githubusercontent.com/69296484/89508038-ebbebe00-d7ff-11ea-85f7-a3e396fb4332.png)
> ![image](https://user-images.githubusercontent.com/69296484/89508149-13ae2180-d800-11ea-9104-a01c93671674.png)
> 
> **Which version of DataX Web:**
> -[2.1.2]
> 
> **Additional context**
> Add any other context about the problem here.
> 
> **Requirement or improvement
> 
> * Please describe about your requirements or improvement suggestions.

![image](https://user-images.githubusercontent.com/33245094/89520476-7c04ff00-d810-11ea-837d-45acbcfdd147.png)
将截图中的参数拼接到python命令中，手动执行可以吗

**Comment by xugirl** [comment]
python /opt/datax/bin/datax.py ./modules/datax-executor/jsonjobTmp-20017a7a81f64f88a1d38038d2b2eaa9.conf -j "-Xms2G -Xmx2G"  这样执行是可以的

**Comment by WeiYe-Jing** [comment]
> python /opt/datax/bin/datax.py ./modules/datax-executor/jsonjobTmp-20017a7a81f64f88a1d38038d2b2eaa9.conf -j "-Xms2G -Xmx2G" 这样执行是可以的

从上面的日志中看web中拼接的参数是没问题的，这是在linux运行遇到的错误吗，我本地windows测试了下正常

**Comment by earthNoah** [comment]
![image](https://user-images.githubusercontent.com/23658298/90707949-3f82da00-e2cb-11ea-8306-b959bf999e47.png)

应该是shell启动参数的空格,或者引号有错误

**Comment by WeiYe-Jing** [comment]
> ![image](https://user-images.githubusercontent.com/23658298/90707949-3f82da00-e2cb-11ea-8306-b959bf999e47.png)
> 
> 应该是shell启动参数的空格,或者引号有错误

你的环境是linux吗，我windows测试没遇到这个问题

**Comment by earthNoah** [comment]
macos 15.1 Darwin Kernel Version 19.0.0

**Comment by WeiYe-Jing** [comment]
> macos 15.1 Darwin Kernel Version 19.0.0

这个问题如果不能复现，可以先放着，后面再看看反馈，辛苦了

**Comment by earthNoah** [comment]
这个问题在我们生产linux 服务器上, 如果同时指定增量时间和jvm参数, 也会出现这个问题
datax-web版本 2.11
CentOS Linux release 7.3.1611 (Core)  
3.10.0-514.21.1.el7.x86_6

![image](https://user-images.githubusercontent.com/23658298/90711243-cd15f800-e2d2-11ea-95e7-e50426c40442.png)

**Comment by WeiYe-Jing** [comment]
> 这个问题在我们生产linux 服务器上, 如果同时指定增量时间和jvm参数, 也会出现这个问题
> datax-web版本 2.11
> CentOS Linux release 7.3.1611 (Core)
> 3.10.0-514.21.1.el7.x86_6
> 
> ![image](https://user-images.githubusercontent.com/23658298/90711243-cd15f800-e2d2-11ea-95e7-e50426c40442.png)

那问题基本可以定位了，应该是jvm这段参数 -j"-Xms1024m -Xmx1024m"拼接的问题，不兼容linux,推测应该是中间空格的问题

**Comment by DBA-Ray** [comment]
这个什么在linux上什么时候解决啊

**Comment by WeiYe-Jing** [comment]
> 这个什么在linux上什么时候解决啊

下个版本修复，时间还没定，也欢迎贡献

**Comment by Ryancontinue** [comment]
我在Linux上运行，把cmd打印出来了，应该是linux对拼接命令解析的问题

![Uploading image.png…]()

**Comment by Ryancontinue** [comment]
我在Linux上运行，把cmd打印出来了，应该是linux对拼接命令解析的问题

![image](https://user-images.githubusercontent.com/44901710/94656802-1d04c780-0333-11eb-8f07-ddbfeb06f420.png)

**Comment by Ryancontinue** [comment]
private String buildDataXParam(TriggerParam tgParam) {
        StringBuilder doc = new StringBuilder();
        String jvmParam = tgParam.getJvmParam().trim();
        String partitionStr = tgParam.getPartitionInfo().trim();
        if (StringUtils.isNotBlank(jvmParam)) {
            // jvmParam的空格先替换点
            doc.append(DataxOption.JVM_CM)
                    .append(DataxOption.TRANSFORM_QUOTES)
                    .append(jvmParam.replaceAll(DataxOption.SPLIT_SPACE, DataxOption.TRANSFORM_SPLIT_SPACE))
                    .append(DataxOption.TRANSFORM_QUOTES)
                    .append(DataxOption.CMD_SPLIT_WORK);
        }
        long tgSecondTime = tgParam.getTriggerTime().getTime() / 1000;
        if (StringUtils.isNotBlank(tgParam.getReplaceParam())) {
            long lastTime = tgParam.getStartTime().getTime() / 1000;
//            if (doc.length() > 0) doc.append(DataxOption.SPLIT_SPACE);
            doc.append(DataxOption.PARAMS_CM).append(DataxOption.TRANSFORM_QUOTES)
                    .append(String.format(tgParam.getReplaceParam(), lastTime, tgSecondTime).trim().replaceAll(DataxOption.SPLIT_SPACE, DataxOption.TRANSFORM_SPLIT_SPACE))
                    .append(DataxOption.TRANSFORM_QUOTES);
            if (StringUtils.isNotBlank(partitionStr)) {
                doc.append(DataxOption.SPLIT_SPACE);
                List<String> partitionInfo = Arrays.asList(partitionStr.split(Constants.SPLIT_COMMA));
                doc.append(DataxOption.TRANSFORM_QUOTES)
                        .append(String.format(DataxOption.PARAMS_CM_V_PT, buildPartition(partitionInfo)))
                        .append(DataxOption.TRANSFORM_QUOTES);
            }
//            doc.append(DataxOption.TRANSFORM_QUOTES);
        } else {
            if (StringUtils.isNotBlank(partitionStr)) {
                List<String> partitionInfo = Arrays.asList(partitionStr.split(Constants.SPLIT_COMMA));
                if (doc.length() > 0) doc.append(DataxOption.SPLIT_SPACE);
                doc.append(DataxOption.PARAMS_CM).append(DataxOption.TRANSFORM_QUOTES).append(String.format(DataxOption.PARAMS_CM_V_PT, buildPartition(partitionInfo))).append(DataxOption.TRANSFORM_QUOTES);
            }
        }
        JobLogger.log("------------------命令参数: " + doc);
        JobLogger.log("------------------命令参数toString: " + doc.toString());
        return doc.toString();


    }

**Comment by Ryancontinue** [comment]
private String[] buildCmd(TriggerParam tgParam, String tmpFilePath) {
        // command process
        //"--loglevel=debug"
        List<String> cmdArr = new ArrayList<>();
        cmdArr.add("python");
        String dataXHomePath = SystemUtils.getDataXHomePath();
        if (StringUtils.isNotEmpty(dataXHomePath)) {
            dataXPyPath = dataXHomePath.contains("bin") ? dataXHomePath + DEFAULT_DATAX_PY : dataXHomePath + "bin" + File.separator + DEFAULT_DATAX_PY;
        }
        cmdArr.add(dataXPyPath);
        String doc = buildDataXParam(tgParam);
        if (StringUtils.isNotBlank(doc)) {
//            cmdArr.add(doc.replaceAll(DataxOption.SPLIT_SPACE, DataxOption.TRANSFORM_SPLIT_SPACE));
            cmdArr.addAll(Arrays.asList(doc.split(DataxOption.CMD_SPLIT_WORK)));
        }
        cmdArr.add(tmpFilePath);
        return cmdArr.toArray(new String[cmdArr.size()]);
    }

**Comment by WeiYe-Jing** [comment]
> private String[] buildCmd(TriggerParam tgParam, String tmpFilePath) {
> // command process
> //"--loglevel=debug"
> List cmdArr = new ArrayList<>();
> cmdArr.add("python");
> String dataXHomePath = SystemUtils.getDataXHomePath();
> if (StringUtils.isNotEmpty(dataXHomePath)) {
> dataXPyPath = dataXHomePath.contains("bin") ? dataXHomePath + DEFAULT_DATAX_PY : dataXHomePath + "bin" + File.separator + DEFAULT_DATAX_PY;
> }
> cmdArr.add(dataXPyPath);
> String doc = buildDataXParam(tgParam);
> if (StringUtils.isNotBlank(doc)) {
> // cmdArr.add(doc.replaceAll(DataxOption.SPLIT_SPACE, DataxOption.TRANSFORM_SPLIT_SPACE));
> cmdArr.addAll(Arrays.asList(doc.split(DataxOption.CMD_SPLIT_WORK)));
> }
> cmdArr.add(tmpFilePath);
> return cmdArr.toArray(new String[cmdArr.size()]);
> }

你好，DataxOption.CMD_SPLIT_WORK是逗号吗，只需要修改这行就可以了是吧cmdArr.addAll(Arrays.asList(doc.split(DataxOption.CMD_SPLIT_WORK)));

**Comment by sirius19** [comment]
问题出在BuildCommand.buildDataXParam(TriggerParam tgParam) 这个方法，如果同时传入-j和-p参数的话，这里应该返回一个数组，而不应是String
