### ISSUE TITLE
[Feature]希望楼主能够支持代码级别的 功能由于数据迁移较为复杂可能需要代码层面的逻辑处理若不支持的话可用性会大大降低

### ISSUE THREAD

**Issue by bambooToxic** [WeiYe-Jing/datax-web#270]
最好支持java 集成datax-web，能够支持代码层面的数据处理逻辑。希望楼主能够采纳并集成java 配置 增加等功能

**Comment by anuxs** [comment]
我持反对意见。
这个DataX 就是个能够自动执行的数据仓库工具，面对的批量化、自动化、数据搬运、异构数据库，这是他的应用场景。你说的代码级别的、非常复杂的数据迁移，这种迁移不是经常性的，很可能是一次性的，面向频繁变动的业务功能的，那这种需求本来就不是数据仓库工具的用户。你应该写定制代码去做个性化的同步。
代码级别的迁移，其实你也可以做自己的插件，按照规范写也没有多难，但是这不是做插件的目的。插件还是解决的异构系统的读写数据流。不是为了复杂业务迁移，你那种迁移都不叫迁移了，你没有描述清楚你的业务需求。
这个软件非常好用，阿里也在大规模用，你说可行性不够，那是你的需求不适合这个软件要解决的场景，不用强求。

**Comment by WeiYe-Jing** [comment]
java dev分支已支持，欢迎试用
