### ISSUE TITLE
datax-web增量数据同步

### ISSUE THREAD

**Issue by Lxq970714** [WeiYe-Jing/datax-web#276]
请问，datax-web要怎么配置才能实现数据的修改而不是insert呢？

**Comment by WeiYe-Jing** [comment]
> 请问，datax-web要怎么配置才能实现数据的修改而不是insert呢？

这个要看数据源的，mysql目前是支持的，你可以看下官方文档中writeMode配置说明
其它数据源可以参考文档：https://github.com/WeiYe-Jing/datax-web/issues/253

**Comment by Lxq970714** [comment]
已解决，非常感谢！
