### ISSUE TITLE
[BUG] 启动executor连接拒绝

### ISSUE THREAD

**Issue by deerlili** [WeiYe-Jing/datax-web#278]
09:31:44.328 exe [datax-web, executor ExecutorRegistryThread] INFO  c.w.d.c.t.ExecutorRegistryThread - >>>>>>>>>>> datax-web registry fail, registryParam:RegistryParam{registryGroup='EXECUTOR', registryKey='datax-executor', registryValue='192.168.63.1:9999', cpuUsage='12.53', memoryUsage='77.65', loadAverage='-1.0'}, registryResult:ReturnT [code=500, msg=xxl-rpc remoting error(Connection refused: connect), for url : http://127.0.0.1:8080/api/registry, content=null]
09:32:15.350 exe [datax-web, executor ExecutorRegistryThread] ERROR c.w.d.c.u.JobRemotingUtil - Connection refused: connect
java.net.ConnectException: Connection refused: connect

**Comment by WeiYe-Jing** [comment]
> 09:31:44.328 exe [datax-web, executor ExecutorRegistryThread] INFO c.w.d.c.t.ExecutorRegistryThread - >>>>>>>>>>> datax-web registry fail, registryParam:RegistryParam{registryGroup='EXECUTOR', registryKey='datax-executor', registryValue='192.168.63.1:9999', cpuUsage='12.53', memoryUsage='77.65', loadAverage='-1.0'}, registryResult:ReturnT [code=500, msg=xxl-rpc remoting error(Connection refused: connect), for url : http://127.0.0.1:8080/api/registry, content=null]
> 09:32:15.350 exe [datax-web, executor ExecutorRegistryThread] ERROR c.w.d.c.u.JobRemotingUtil - Connection refused: connect
> java.net.ConnectException: Connection refused: connect

项目启动时，如果admin晚于executor启动，executor注册是会失败的，30秒后重新注册，请注意观察。
如果还有问题请检查：
admin的地址对吗？8080端口是自己改的吗，官方提供的安装包admin默认是9527端口  http://127.0.0.1:8080/api/registry
