### ISSUE TITLE
[BUG] 文档中下载地址文件内容未更新

### ISSUE THREAD

**Issue by chaozhangpower** [WeiYe-Jing/datax-web#281]
*For better global communication, please give priority to using English description, thx! *

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior, for example:

**Expected behavior**

**Screenshots**

**Which version of DataX Web:**
 -[2.1.1]

**Additional context**

**Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by WeiYe-Jing** [comment]
> *For better global communication, please give priority to using English description, thx! *
> 
> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> **To Reproduce**
> Steps to reproduce the behavior, for example:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Which version of DataX Web:**
> -[2.1.1]
> 
> **Additional context**
> Add any other context about the problem here.
> 
> **Requirement or improvement
> 
> * Please describe about your requirements or improvement suggestions.

什么文档，什么下载地址，请描述清楚

**Comment by chaozhangpower** [comment]
https://github.com/WeiYe-Jing/datax-web/blob/master/doc/datax-web/datax-web-deploy.md

**Comment by chaozhangpower** [comment]
教程下第二部分，datax-web 
![image](https://user-images.githubusercontent.com/21254276/90749904-a5408780-e306-11ea-8488-8d7805c05ebe.png)

**Comment by chaozhangpower** [comment]
官方下载包，下载的文件中，bin 目录下 install.sh等文件内容为空

**Comment by WeiYe-Jing** [comment]
> 教程下第二部分，datax-web
> ![image](https://user-images.githubusercontent.com/21254276/90749904-a5408780-e306-11ea-8488-8d7805c05ebe

**Comment by WeiYe-Jing** [comment]
> 官方下载包，下载的文件中，bin 目录下 install.sh等文件内容为空

![image](https://user-images.githubusercontent.com/33245094/90757812-aeceed00-e310-11ea-8399-c53f38db8ca0.png)

是不是看错了，我刚下载下来检查没问题
