### ISSUE TITLE
执行普通shell命令报空指针异常

### ISSUE THREAD

**Issue by w39021384** [WeiYe-Jing/datax-web#292]
*For better global communication, please give priority to using English description, thx! *

**Describe the question**
创建普通shell任务，执行任务失败，报空指针异常
shell任务：
![image](https://user-images.githubusercontent.com/38243948/91786737-d8eeac00-ec3a-11ea-8a6b-16f7177d6277.png)

异常信息：
![image](https://user-images.githubusercontent.com/38243948/91786770-ee63d600-ec3a-11ea-9c2b-3eca245ce0db.png)

**Which version of DataX Web:**
 -[2.1.2]

**Comment by WeiYe-Jing** [comment]
> *For better global communication, please give priority to using English description, thx! *
> 
> **Describe the question**
> 创建普通shell任务，执行任务失败，报空指针异常
> shell任务：
> ![image](https://user-images.githubusercontent.com/38243948/91786737-d8eeac00-ec3a-11ea-8a6b-16f7177d6277.png)
> 
> 异常信息：
> ![image](https://user-images.githubusercontent.com/38243948/91786770-ee63d600-ec3a-11ea-9c2b-3eca245ce0db.png)
> 
> **Which version of DataX Web:**
> -[2.1.2]

方便的话可以断点调试下

**Comment by w39021384** [comment]
> > *为了更好地进行全球交流，请优先使用英文说明thx！*
> > **描述问题** 
> > 创建普通的shell任务，执行任务失败，报空指针异常
> > shell任务：
> > ![图片](https://user-images.githubusercontent.com/38243948/91786737-d8eeac00-ec3a-11ea-8a6b-16f7177d6277.png)
> > 异常信息：
> > ![图片](https://user-images.githubusercontent.com/38243948/91786770-ee63d600-ec3a-11ea-9c2b-3eca245ce0db.png)
> > **哪个版本的DataX Web：** 
> > -[2.1.2]
> 
> 方便的话可以断点调试下

datax任务此处为字符串空：
![image](https://user-images.githubusercontent.com/38243948/91799913-9ccb4380-ec5a-11ea-8ba0-74615c78c1a0.png)
shell任务：
![image](https://user-images.githubusercontent.com/38243948/91800007-cedca580-ec5a-11ea-8480-8b390cd82d44.png)
红框处空指针异常发生的位置
![image](https://user-images.githubusercontent.com/38243948/91800049-e2880c00-ec5a-11ea-83e2-4c34638b3df2.png)

**Comment by WeiYe-Jing** [comment]
> > > _为了更好地进行全球交流，请优先使用英文说明thx！_
> > > **描述问题**
> > > 创建普通的shell任务，执行任务失败，报空指针异常
> > > shell任务：
> > > ![图片](https://user-images.githubusercontent.com/38243948/91786737-d8eeac00-ec3a-11ea-8a6b-16f7177d6277.png)
> > > 异常信息：
> > > ![图片](https://user-images.githubusercontent.com/38243948/91786770-ee63d600-ec3a-11ea-9c2b-3eca245ce0db.png)
> > > **哪个版本的DataX Web：**
> > > -[2.1.2]
> > 
> > 
> > 方便的话可以断点调试下
> 
> datax任务此处为字符串空：
> ![image](https://user-images.githubusercontent.com/38243948/91799913-9ccb4380-ec5a-11ea-8ba0-74615c78c1a0.png)
> shell任务：
> ![image](https://user-images.githubusercontent.com/38243948/91800007-cedca580-ec5a-11ea-8480-8b390cd82d44.png)
> 红框处空指针异常发生的位置
> ![image](https://user-images.githubusercontent.com/38243948/91800049-e2880c00-ec5a-11ea-83e2-4c34638b3df2.png)

这是什么系统，应该是scriptParams中添加了空参造成的

**Comment by w39021384** [comment]
CentOS Linux release 7.5.1804

**Comment by w39021384** [comment]
> > > > _为了更好地进行全球交流，请优先使用英文说明thx！_
> > > > **描述问题**
> > > > 创建普通的shell任务，执行任务失败，报空指针异常
> > > > shell任务：
> > > > ![图片](https://user-images.githubusercontent.com/38243948/91786737-d8eeac00-ec3a-11ea-8a6b-16f7177d6277.png)
> > > > 异常信息：
> > > > ![图片](https://user-images.githubusercontent.com/38243948/91786770-ee63d600-ec3a-11ea-9c2b-3eca245ce0db.png)
> > > > **哪个版本的DataX Web：**
> > > > -[2.1.2]
> > > 
> > > 
> > > 方便的话可以断点调试下
> > 
> > 
> > datax任务此处为字符串空：
> > ![image](https://user-images.githubusercontent.com/38243948/91799913-9ccb4380-ec5a-11ea-8ba0-74615c78c1a0.png)
> > shell任务：
> > ![image](https://user-images.githubusercontent.com/38243948/91800007-cedca580-ec5a-11ea-8480-8b390cd82d44.png)
> > 红框处空指针异常发生的位置
> > ![image](https://user-images.githubusercontent.com/38243948/91800049-e2880c00-ec5a-11ea-83e2-4c34638b3df2.png)
> 
> 系统信息可以描述下吗，应该是scriptParams中添加了空参造成的

机器是华为鲲鹏的

**Comment by w39021384** [comment]
> > > > _为了更好地进行全球交流，请优先使用英文说明thx！_
> > > > **描述问题**
> > > > 创建普通的shell任务，执行任务失败，报空指针异常
> > > > shell任务：
> > > > ![图片](https://user-images.githubusercontent.com/38243948/91786737-d8eeac00-ec3a-11ea-8a6b-16f7177d6277.png)
> > > > 异常信息：
> > > > ![图片](https://user-images.githubusercontent.com/38243948/91786770-ee63d600-ec3a-11ea-9c2b-3eca245ce0db.png)
> > > > **哪个版本的DataX Web：**
> > > > -[2.1.2]
> > > 
> > > 
> > > 方便的话可以断点调试下
> > 
> > 
> > datax任务此处为字符串空：
> > ![image](https://user-images.githubusercontent.com/38243948/91799913-9ccb4380-ec5a-11ea-8ba0-74615c78c1a0.png)
> > shell任务：
> > ![image](https://user-images.githubusercontent.com/38243948/91800007-cedca580-ec5a-11ea-8480-8b390cd82d44.png)
> > 红框处空指针异常发生的位置
> > ![image](https://user-images.githubusercontent.com/38243948/91800049-e2880c00-ec5a-11ea-83e2-4c34638b3df2.png)
> 
> 系统信息可以描述下吗，应该是scriptParams中添加了空参造成的

CentOS Linux release 7.5.1804
机器是华为鲲鹏的

**Comment by WeiYe-Jing** [comment]
> > > > > _为了更好地进行全球交流，请优先使用英文说明thx！_
> > > > > **描述问题**
> > > > > 创建普通的shell任务，执行任务失败，报空指针异常
> > > > > shell任务：
> > > > > ![图片](https://user-images.githubusercontent.com/38243948/91786737-d8eeac00-ec3a-11ea-8a6b-16f7177d6277.png)
> > > > > 异常信息：
> > > > > ![图片](https://user-images.githubusercontent.com/38243948/91786770-ee63d600-ec3a-11ea-9c2b-3eca245ce0db.png)
> > > > > **哪个版本的DataX Web：**
> > > > > -[2.1.2]
> > > > 
> > > > 
> > > > 方便的话可以断点调试下
> > > 
> > > 
> > > datax任务此处为字符串空：
> > > ![image](https://user-images.githubusercontent.com/38243948/91799913-9ccb4380-ec5a-11ea-8ba0-74615c78c1a0.png)
> > > shell任务：
> > > ![image](https://user-images.githubusercontent.com/38243948/91800007-cedca580-ec5a-11ea-8480-8b390cd82d44.png)
> > > 红框处空指针异常发生的位置
> > > ![image](https://user-images.githubusercontent.com/38243948/91800049-e2880c00-ec5a-11ea-83e2-4c34638b3df2.png)
> > 
> > 
> > 系统信息可以描述下吗，应该是scriptParams中添加了空参造成的
> 
> CentOS Linux release 7.5.1804
> 机器是华为鲲鹏的

好的，这里你可以处理下，也欢迎提个PR

**Comment by w39021384** [comment]
> > > > > > _为了更好地进行全球交流，请优先使用英文说明thx！_
> > > > > > **描述问题**
> > > > > > 创建普通的shell任务，执行任务失败，报空指针异常
> > > > > > shell任务：
> > > > > > ![图片](https://user-images.githubusercontent.com/38243948/91786737-d8eeac00-ec3a-11ea-8a6b-16f7177d6277.png)
> > > > > > 异常信息：
> > > > > > ![图片](https://user-images.githubusercontent.com/38243948/91786770-ee63d600-ec3a-11ea-9c2b-3eca245ce0db.png)
> > > > > > **哪个版本的DataX Web：**
> > > > > > -[2.1.2]
> > > > > 
> > > > > 
> > > > > 方便的话可以断点调试下
> > > > 
> > > > 
> > > > datax任务此处为字符串空：
> > > > ![image](https://user-images.githubusercontent.com/38243948/91799913-9ccb4380-ec5a-11ea-8ba0-74615c78c1a0.png)
> > > > shell任务：
> > > > ![image](https://user-images.githubusercontent.com/38243948/91800007-cedca580-ec5a-11ea-8480-8b390cd82d44.png)
> > > > 红框处空指针异常发生的位置
> > > > ![image](https://user-images.githubusercontent.com/38243948/91800049-e2880c00-ec5a-11ea-83e2-4c34638b3df2.png)
> > > 
> > > 
> > > 系统信息可以描述下吗，应该是scriptParams中添加了空参造成的
> > 
> > 
> > CentOS Linux release 7.5.1804
> > 机器是华为鲲鹏的
> 
> 好的，这里你可以处理下，也欢迎提个PR

这个是xxl-job的问题吗

**Comment by WeiYe-Jing** [comment]
> > > > > > > _为了更好地进行全球交流，请优先使用英文说明thx！_
> > > > > > > **描述问题**
> > > > > > > 创建普通的shell任务，执行任务失败，报空指针异常
> > > > > > > shell任务：
> > > > > > > ![图片](https://user-images.githubusercontent.com/38243948/91786737-d8eeac00-ec3a-11ea-8a6b-16f7177d6277.png)
> > > > > > > 异常信息：
> > > > > > > ![图片](https://user-images.githubusercontent.com/38243948/91786770-ee63d600-ec3a-11ea-9c2b-3eca245ce0db.png)
> > > > > > > **哪个版本的DataX Web：**
> > > > > > > -[2.1.2]
> > > > > > 
> > > > > > 
> > > > > > 方便的话可以断点调试下
> > > > > 
> > > > > 
> > > > > datax任务此处为字符串空：
> > > > > ![image](https://user-images.githubusercontent.com/38243948/91799913-9ccb4380-ec5a-11ea-8ba0-74615c78c1a0.png)
> > > > > shell任务：
> > > > > ![image](https://user-images.githubusercontent.com/38243948/91800007-cedca580-ec5a-11ea-8480-8b390cd82d44.png)
> > > > > 红框处空指针异常发生的位置
> > > > > ![image](https://user-images.githubusercontent.com/38243948/91800049-e2880c00-ec5a-11ea-83e2-4c34638b3df2.png)
> > > > 
> > > > 
> > > > 系统信息可以描述下吗，应该是scriptParams中添加了空参造成的
> > > 
> > > 
> > > CentOS Linux release 7.5.1804
> > > 机器是华为鲲鹏的
> > 
> > 
> > 好的，这里你可以处理下，也欢迎提个PR
> 
> 这个是xxl-job的问题吗

xxl-job应该也会遇到这个问题，加个判断就行了

**Comment by w39021384** [comment]
> > > > > > > > _为了更好地进行全球交流，请优先使用英文说明thx！_
> > > > > > > > **描述问题**
> > > > > > > > 创建普通的shell任务，执行任务失败，报空指针异常
> > > > > > > > shell任务：
> > > > > > > > ![图片](https://user-images.githubusercontent.com/38243948/91786737-d8eeac00-ec3a-11ea-8a6b-16f7177d6277.png)
> > > > > > > > 异常信息：
> > > > > > > > ![图片](https://user-images.githubusercontent.com/38243948/91786770-ee63d600-ec3a-11ea-9c2b-3eca245ce0db.png)
> > > > > > > > **哪个版本的DataX Web：**
> > > > > > > > -[2.1.2]
> > > > > > > 
> > > > > > > 
> > > > > > > 方便的话可以断点调试下
> > > > > > 
> > > > > > 
> > > > > > datax任务此处为字符串空：
> > > > > > ![image](https://user-images.githubusercontent.com/38243948/91799913-9ccb4380-ec5a-11ea-8ba0-74615c78c1a0.png)
> > > > > > shell任务：
> > > > > > ![image](https://user-images.githubusercontent.com/38243948/91800007-cedca580-ec5a-11ea-8480-8b390cd82d44.png)
> > > > > > 红框处空指针异常发生的位置
> > > > > > ![image](https://user-images.githubusercontent.com/38243948/91800049-e2880c00-ec5a-11ea-83e2-4c34638b3df2.png)
> > > > > 
> > > > > 
> > > > > 系统信息可以描述下吗，应该是scriptParams中添加了空参造成的
> > > > 
> > > > 
> > > > CentOS Linux release 7.5.1804
> > > > 机器是华为鲲鹏的
> > > 
> > > 
> > > 好的，这里你可以处理下，也欢迎提个PR
> > 
> > 
> > 这个是xxl-job的问题吗
> 
> xxl-job应该也会遇到这个问题，加个判断就行了

![image](https://user-images.githubusercontent.com/38243948/91816416-942d3a00-ec67-11ea-91c8-9a1dc00b2280.png)
![image](https://user-images.githubusercontent.com/38243948/91816544-9f806580-ec67-11ea-826a-d44925fbe985.png)
执行成功状态没有改变，终止任务也不生效

**Comment by WeiYe-Jing** [comment]
> > > > > > > > > _为了更好地进行全球交流，请优先使用英文说明thx！_
> > > > > > > > > **描述问题**
> > > > > > > > > 创建普通的shell任务，执行任务失败，报空指针异常
> > > > > > > > > shell任务：
> > > > > > > > > ![图片](https://user-images.githubusercontent.com/38243948/91786737-d8eeac00-ec3a-11ea-8a6b-16f7177d6277.png)
> > > > > > > > > 异常信息：
> > > > > > > > > ![图片](https://user-images.githubusercontent.com/38243948/91786770-ee63d600-ec3a-11ea-9c2b-3eca245ce0db.png)
> > > > > > > > > **哪个版本的DataX Web：**
> > > > > > > > > -[2.1.2]
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 方便的话可以断点调试下
> > > > > > > 
> > > > > > > 
> > > > > > > datax任务此处为字符串空：
> > > > > > > ![image](https://user-images.githubusercontent.com/38243948/91799913-9ccb4380-ec5a-11ea-8ba0-74615c78c1a0.png)
> > > > > > > shell任务：
> > > > > > > ![image](https://user-images.githubusercontent.com/38243948/91800007-cedca580-ec5a-11ea-8480-8b390cd82d44.png)
> > > > > > > 红框处空指针异常发生的位置
> > > > > > > ![image](https://user-images.githubusercontent.com/38243948/91800049-e2880c00-ec5a-11ea-83e2-4c34638b3df2.png)
> > > > > > 
> > > > > > 
> > > > > > 系统信息可以描述下吗，应该是scriptParams中添加了空参造成的
> > > > > 
> > > > > 
> > > > > CentOS Linux release 7.5.1804
> > > > > 机器是华为鲲鹏的
> > > > 
> > > > 
> > > > 好的，这里你可以处理下，也欢迎提个PR
> > > 
> > > 
> > > 这个是xxl-job的问题吗
> > 
> > 
> > xxl-job应该也会遇到这个问题，加个判断就行了
> 
> ![image](https://user-images.githubusercontent.com/38243948/91816416-942d3a00-ec67-11ea-91c8-9a1dc00b2280.png)
> ![image](https://user-images.githubusercontent.com/38243948/91816544-9f806580-ec67-11ea-826a-d44925fbe985.png)
> 执行成功状态没有改变，终止任务也不生效

回调失败了，看下项目日志

**Comment by w39021384** [comment]
> > > > > > > > > > _为了更好地进行全球交流，请优先使用英文说明thx！_
> > > > > > > > > > **描述问题**
> > > > > > > > > > 创建普通的shell任务，执行任务失败，报空指针异常
> > > > > > > > > > shell任务：
> > > > > > > > > > ![图片](https://user-images.githubusercontent.com/38243948/91786737-d8eeac00-ec3a-11ea-8a6b-16f7177d6277.png)
> > > > > > > > > > 异常信息：
> > > > > > > > > > ![图片](https://user-images.githubusercontent.com/38243948/91786770-ee63d600-ec3a-11ea-9c2b-3eca245ce0db.png)
> > > > > > > > > > **哪个版本的DataX Web：**
> > > > > > > > > > -[2.1.2]
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 方便的话可以断点调试下
> > > > > > > > 
> > > > > > > > 
> > > > > > > > datax任务此处为字符串空：
> > > > > > > > ![image](https://user-images.githubusercontent.com/38243948/91799913-9ccb4380-ec5a-11ea-8ba0-74615c78c1a0.png)
> > > > > > > > shell任务：
> > > > > > > > ![image](https://user-images.githubusercontent.com/38243948/91800007-cedca580-ec5a-11ea-8480-8b390cd82d44.png)
> > > > > > > > 红框处空指针异常发生的位置
> > > > > > > > ![image](https://user-images.githubusercontent.com/38243948/91800049-e2880c00-ec5a-11ea-83e2-4c34638b3df2.png)
> > > > > > > 
> > > > > > > 
> > > > > > > 系统信息可以描述下吗，应该是scriptParams中添加了空参造成的
> > > > > > 
> > > > > > 
> > > > > > CentOS Linux release 7.5.1804
> > > > > > 机器是华为鲲鹏的
> > > > > 
> > > > > 
> > > > > 好的，这里你可以处理下，也欢迎提个PR
> > > > 
> > > > 
> > > > 这个是xxl-job的问题吗
> > > 
> > > 
> > > xxl-job应该也会遇到这个问题，加个判断就行了
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/38243948/91816416-942d3a00-ec67-11ea-91c8-9a1dc00b2280.png)
> > ![image](https://user-images.githubusercontent.com/38243948/91816544-9f806580-ec67-11ea-826a-d44925fbe985.png)
> > 执行成功状态没有改变，终止任务也不生效
> 
> 回调失败了，看下项目日志

![image](https://user-images.githubusercontent.com/38243948/91832157-a3b47f00-ec77-11ea-9a00-cbcf8d66790a.png)
handleMsg是空的

**Comment by WeiYe-Jing** [comment]
> > > > > > > > > > > _为了更好地进行全球交流，请优先使用英文说明thx！_
> > > > > > > > > > > **描述问题**
> > > > > > > > > > > 创建普通的shell任务，执行任务失败，报空指针异常
> > > > > > > > > > > shell任务：
> > > > > > > > > > > ![图片](https://user-images.githubusercontent.com/38243948/91786737-d8eeac00-ec3a-11ea-8a6b-16f7177d6277.png)
> > > > > > > > > > > 异常信息：
> > > > > > > > > > > ![图片](https://user-images.githubusercontent.com/38243948/91786770-ee63d600-ec3a-11ea-9c2b-3eca245ce0db.png)
> > > > > > > > > > > **哪个版本的DataX Web：**
> > > > > > > > > > > -[2.1.2]
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > 方便的话可以断点调试下
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > datax任务此处为字符串空：
> > > > > > > > > ![image](https://user-images.githubusercontent.com/38243948/91799913-9ccb4380-ec5a-11ea-8ba0-74615c78c1a0.png)
> > > > > > > > > shell任务：
> > > > > > > > > ![image](https://user-images.githubusercontent.com/38243948/91800007-cedca580-ec5a-11ea-8480-8b390cd82d44.png)
> > > > > > > > > 红框处空指针异常发生的位置
> > > > > > > > > ![image](https://user-images.githubusercontent.com/38243948/91800049-e2880c00-ec5a-11ea-83e2-4c34638b3df2.png)
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 系统信息可以描述下吗，应该是scriptParams中添加了空参造成的
> > > > > > > 
> > > > > > > 
> > > > > > > CentOS Linux release 7.5.1804
> > > > > > > 机器是华为鲲鹏的
> > > > > > 
> > > > > > 
> > > > > > 好的，这里你可以处理下，也欢迎提个PR
> > > > > 
> > > > > 
> > > > > 这个是xxl-job的问题吗
> > > > 
> > > > 
> > > > xxl-job应该也会遇到这个问题，加个判断就行了
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/38243948/91816416-942d3a00-ec67-11ea-91c8-9a1dc00b2280.png)
> > > ![image](https://user-images.githubusercontent.com/38243948/91816544-9f806580-ec67-11ea-826a-d44925fbe985.png)
> > > 执行成功状态没有改变，终止任务也不生效
> > 
> > 
> > 回调失败了，看下项目日志
> 
> ![image](https://user-images.githubusercontent.com/38243948/91832157-a3b47f00-ec77-11ea-9a00-cbcf8d66790a.png)
> handleMsg是空的

![image](https://user-images.githubusercontent.com/33245094/91833311-1f62fb80-ec79-11ea-9d95-2e467da61faf.png)
你的版本是自己二次开发的吗，怎么和发布版本不一样。

**Comment by w39021384** [comment]
> > > > > > > > > > > > _为了更好地进行全球交流，请优先使用英文说明thx！_
> > > > > > > > > > > > **描述问题**
> > > > > > > > > > > > 创建普通的shell任务，执行任务失败，报空指针异常
> > > > > > > > > > > > shell任务：
> > > > > > > > > > > > ![图片](https://user-images.githubusercontent.com/38243948/91786737-d8eeac00-ec3a-11ea-8a6b-16f7177d6277.png)
> > > > > > > > > > > > 异常信息：
> > > > > > > > > > > > ![图片](https://user-images.githubusercontent.com/38243948/91786770-ee63d600-ec3a-11ea-9c2b-3eca245ce0db.png)
> > > > > > > > > > > > **哪个版本的DataX Web：**
> > > > > > > > > > > > -[2.1.2]
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > 方便的话可以断点调试下
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > datax任务此处为字符串空：
> > > > > > > > > > ![image](https://user-images.githubusercontent.com/38243948/91799913-9ccb4380-ec5a-11ea-8ba0-74615c78c1a0.png)
> > > > > > > > > > shell任务：
> > > > > > > > > > ![image](https://user-images.githubusercontent.com/38243948/91800007-cedca580-ec5a-11ea-8480-8b390cd82d44.png)
> > > > > > > > > > 红框处空指针异常发生的位置
> > > > > > > > > > ![image](https://user-images.githubusercontent.com/38243948/91800049-e2880c00-ec5a-11ea-83e2-4c34638b3df2.png)
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 系统信息可以描述下吗，应该是scriptParams中添加了空参造成的
> > > > > > > > 
> > > > > > > > 
> > > > > > > > CentOS Linux release 7.5.1804
> > > > > > > > 机器是华为鲲鹏的
> > > > > > > 
> > > > > > > 
> > > > > > > 好的，这里你可以处理下，也欢迎提个PR
> > > > > > 
> > > > > > 
> > > > > > 这个是xxl-job的问题吗
> > > > > 
> > > > > 
> > > > > xxl-job应该也会遇到这个问题，加个判断就行了
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/38243948/91816416-942d3a00-ec67-11ea-91c8-9a1dc00b2280.png)
> > > > ![image](https://user-images.githubusercontent.com/38243948/91816544-9f806580-ec67-11ea-826a-d44925fbe985.png)
> > > > 执行成功状态没有改变，终止任务也不生效
> > > 
> > > 
> > > 回调失败了，看下项目日志
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/38243948/91832157-a3b47f00-ec77-11ea-9a00-cbcf8d66790a.png)
> > handleMsg是空的
> 
> ![image](https://user-images.githubusercontent.com/33245094/91833311-1f62fb80-ec79-11ea-9d95-2e467da61faf.png)
> 你的版本是自己二次开发的吗，怎么和发布版本不一样。

不好意思，我人晕掉了，这个功能是我自己加的。。
