### ISSUE TITLE
编译成jar后，java -jar运行报错 错误: 找不到或无法加载主类 com.wugui.datax.admin.DataXAdminApplication

### ISSUE THREAD

**Issue by fushisanlang** [WeiYe-Jing/datax-web#293]
使用v2.1.2分支的代码。
在idea中直接可以启动。
但是因为某些要求，现在想在win环境中脱离idea运行项目。

目前我通过idea编译后，使用java -jar命令无法启动。报错内容如下：
错误: 找不到或无法加载主类 com.wugui.datax.admin.DataXAdminApplication

请问是我哪里配置不对，还是代码开发时未考虑win平台。

**Comment by WeiYe-Jing** [comment]
> 使用v2.1.2分支的代码。
> 在idea中直接可以启动。
> 但是因为某些要求，现在想在win环境中脱离idea运行项目。
> 
> 目前我通过idea编译后，使用java -jar命令无法启动。报错内容如下：
> 错误: 找不到或无法加载主类 com.wugui.datax.admin.DataXAdminApplication
> 
> 请问是我哪里配置不对，还是代码开发时未考虑win平台。

因为项目涉及的数据源较多，数据源驱动的版本一直是一个困扰问题，所以我们对项目打包结构做了改造，更改驱动版本只需要lib下替换jar包即可，不用重新打包，项目通过脚本启动，目前没有windows的启动脚本。
在windows上部署可以参考这个pr，只需要改下打包插件
[PR](https://github.com/WeiYe-Jing/datax-web/pull/233/commits/666fe1d12a09d16bee6a3194d2cff9bfde594e23)

**Comment by deerlili** [comment]
可以再git上运行启动脚本，亲测可以

**Comment by fushisanlang** [comment]
> > 使用v2.1.2分支的代码。
> > 在idea中直接可以启动。
> > 但是因为某些要求，现在想在win环境中脱离idea运行项目。
> > 目前我通过idea编译后，使用java -jar命令无法启动。报错内容如下：
> > 错误: 找不到或无法加载主类 com.wugui.datax.admin.DataXAdminApplication
> > 请问是我哪里配置不对，还是代码开发时未考虑win平台。
> 
> 因为项目涉及的数据源较多，数据源驱动的版本一直是一个困扰问题，所以我们对项目打包结构做了改造，更改驱动版本只需要lib下替换jar包即可，不用重新打包，项目通过脚本启动，目前没有windows的启动脚本。
> 在windows上部署可以参考这个pr，只需要改下打包插件
> [打包插件修改PR](https://github.com/WeiYe-Jing/datax-web/pull/233/commits/666fe1d12a09d16bee6a3194d2cff9bfde594e23)

把您的答案发给我的开发同事了 应该是解决了。现在他给我了一个可以运行的jar包。

**Comment by fushisanlang** [comment]
> 可以再git上运行启动脚本，亲测可以

我试了好久 一直都提示无法加载主

**Comment by WeiYe-Jing** [comment]
> > 可以再git上运行启动脚本，亲测可以
> 
> 我试了好久 一直都提示无法加载主类

按照我的回复做的吗，如果按照这个pr修改，不可能再出错的

**Comment by fushisanlang** [comment]
> > > 可以再git上运行启动脚本，亲测可以
> > 
> > 
> > 我试了好久 一直都提示无法加载主类
> 
> 按照我的回复做的吗，如果按照这个pr修改，不可能再出错的

已经可以了。
