### ISSUE TITLE
添加sqlserver数据源报错

### ISSUE THREAD

**Issue by areswxin** [WeiYe-Jing/datax-web#297]
添加sqlserver数据源报错
09:12:15.637 admin [http-nio-9527-exec-2] ERROR c.w.d.a.e.GlobalExceptionHandler - 系统异常{0}
com.wugui.datax.admin.util.DataXException: Code:[DBUtilErrorCode-10], Description:[连接数据库失败. 请检查您的 账号、密码、数据库名称、IP、Port或者向 DBA 寻求帮助(注意网络环境).].  -  具体错误信息为：com.microsoft.sqlserver.jdbc.SQLServerException: The driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption. Error: "Server chose TLSv1, but that protocol version is not enabled or not supported by the client.". ClientConnectionId:fc539781-66b8-48a3-b5ed-3d6f52c39273

jdk用的openjdk1.8
又遇到同样问题的大佬吗

**Comment by WeiYe-Jing** [comment]
> 添加sqlserver数据源报错
> 09:12:15.637 admin [http-nio-9527-exec-2] ERROR c.w.d.a.e.GlobalExceptionHandler - 系统异常{0}
> com.wugui.datax.admin.util.DataXException: Code:[DBUtilErrorCode-10], Description:[连接数据库失败. 请检查您的 账号、密码、数据库名称、IP、Port或者向 DBA 寻求帮助(注意网络环境).]. - 具体错误信息为：com.microsoft.sqlserver.jdbc.SQLServerException: The driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption. Error: "Server chose TLSv1, but that protocol version is not enabled or not supported by the client.". ClientConnectionId:fc539781-66b8-48a3-b5ed-3d6f52c39273
> 
> jdk用的openjdk1.8
> 又遇到同样问题的大佬吗

项目下的sqlserver驱动版本和数据库版本匹配吗？

**Comment by areswxin** [comment]
之前安装的是openjdk，替换成oraclejdk之后添加sqlserver数据源成功
