### ISSUE TITLE
datax的调度问题

### ISSUE THREAD

**Issue by sunxiaolong-wyp** [WeiYe-Jing/datax-web#3]
请问一下你这边datax执行任务资源调度由什么控制的呢

**Comment by WeiYe-Jing** [comment]
datax的任务资源调度是我用开源项目xxl-job修改来的，资源调度有9个路由策略，调度过于密集执行器来不及处理时也有对应的策略，每个任务可以在配置时可以选择这些策略。

**Comment by WeiYe-Jing** [comment]
进下qq群讨论方便一点，776939467




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"sunxiaolong-wyp"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月2日(星期一) 下午3:49
收件人:&nbsp;"WeiYe-Jing/datax-web"<datax-web@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[WeiYe-Jing/datax-web] datax的调度问题 (#3)




请问一下你这边datax执行任务资源调度由什么控制的呢
