### ISSUE TITLE
[Feature]通过枚举实现工厂模式，新增数据库支持时只需增加枚举值

### ISSUE THREAD

**Issue by LockiJiang** [WeiYe-Jing/datax-web#308]
目前已对DatabaseMetaFactory和QueryToolFactory做了改造，剩余部分改造面较大，需统筹考虑
@WeiYe-Jing 
#307

**Comment by WeiYe-Jing** [comment]
> 目前已对DatabaseMetaFactory和QueryToolFactory做了改造，剩余部分改造面较大，需统筹考虑
> @WeiYe-Jing
> #307

感谢贡献，数据源重构dev分支已经在开发了，非常欢迎参与
