### ISSUE TITLE
[BUG] bug title 

### ISSUE THREAD

**Issue by liuyanji** [WeiYe-Jing/datax-web#319]
报错
**Which version of DataX Web:**
 -[2.1.1]

![image](https://user-images.githubusercontent.com/10329705/93203722-77c0ef80-f787-11ea-8d59-e696cd05ad86.png)

**Comment by WeiYe-Jing** [comment]
> 报错
> **Which version of DataX Web:**
> -[2.1.1]
> 
> ![image](https://user-images.githubusercontent.com/10329705/93203722-77c0ef80-f787-11ea-8d59-e696cd05ad86.png)

可以重新打包前端文件放到后端代码中，也可以使用最新版2.1.2
