### ISSUE TITLE
[BUG] 调度500：AnnotatedConnectException: Connection refused

### ISSUE THREAD

**Issue by CormickKneey** [WeiYe-Jing/datax-web#322]
![捕获](https://user-images.githubusercontent.com/28683577/93550570-453d0f80-f99e-11ea-8461-0a0b4420b05f.PNG)
第一次调度必失败，失败重试可以调度成功，log如下：
-----------------------------------------------------
任务触发类型：Cron触发
执行器-注册方式：手动录入
路由策略：忙碌转移
阻塞处理策略：单机串行
任务超时时间：2
失败重试次数：1
>>>>>>>>>>>触发调度<<<<<<<<<<<
空闲检测：
address：127.0.0.1:30003
code：500
msg：com.wugui.datax.rpc.util.XxlRpcException: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /xxxx:xxxx
>>>>>>>>>>>失败重试触发<<<<<<<<<<<
-------------------------------------------------------
任务触发类型：失败重试触发
执行器-注册方式：手动录入
路由策略：忙碌转移
阻塞处理策略：单机串行
任务超时时间：2
失败重试次数：0
>>>>>>>>>>>触发调度<<<<<<<<<<<
空闲检测：
address：127.0.0.1:30003
code：200
msg：null
触发调度：
address：127.0.0.1:30003
code：200
msg：null
--------------------------------------------------------
MANUAL，RETRY看起来都没问题，CORN执行有点问题，没成功过

**Comment by WeiYe-Jing** [comment]
需要检查下网络问题，cron执行和手动执行，重试 只是触发方式不同，执行完全一样。

**Comment by CormickKneey** [comment]
> 需要检查下网络问题，cron执行和手动执行，重试 只是触发方式不同，执行完全一样。

都是在docker本地跑的,admin:127.0.0.1:3000 ,executor:30001/30002/30003

调度器注册127.0.0.1:30001就会出现这种问题
注册为IP:port就行了，这是迷失在了回送路由上？

**Comment by WeiYe-Jing** [comment]
> > 需要检查下网络问题，cron执行和手动执行，重试 只是触发方式不同，执行完全一样。
> 
> 都是在docker本地跑的,admin:127.0.0.1:3000 ,executor:30001/30002/30003
> 
> 调度器注册127.0.0.1:30001就会出现这种问题
> 注册为IP:port就行了，这是迷失在了回送路由上？

没看明白，可以解释下吗
