### ISSUE TITLE
是否能创建目标库不存在的表

### ISSUE THREAD

**Issue by defineconst** [WeiYe-Jing/datax-web#327]
是否可以创建目标库不存在的数据表，比如Hive中没有表，通过DataX传入数据时候，根据数据源结构创建Hive数据表？

**Comment by WeiYe-Jing** [comment]
> 是否可以创建目标库不存在的数据表，比如Hive中没有表，通过DataX传入数据时候，根据数据源结构创建Hive数据表？

目前不能自动建表，需要提前创建或者通过脚本任务创建

**Comment by WeiYe-Jing** [comment]
合并到 #96
