### ISSUE TITLE
datax-web 新增数据源问题

### ISSUE THREAD

**Issue by LxqGit-blip** [WeiYe-Jing/datax-web#337]
我想在datax-web的后端配件里新加一个数据源要怎么配置呢？

**Comment by WeiYe-Jing** [comment]
> 我想在datax-web的后端配件里新加一个数据源要怎么配置呢？

你是要新加什么数据源，这块需要改前后端代码，不过实现起来也挺容易的，有现成的模板可以参考

**Comment by LxqGit-blip** [comment]
了解

**Comment by LxqGit-blip** [comment]
后端接口用postman联调的时候为什么不通呢？我是按照前端控制台显示的地址去调的

**Comment by WeiYe-Jing** [comment]
> 后端接口用postman联调的时候为什么不通呢？我是按照前端控制台显示的地址去调的

可以重新提个issue详细描述下遇到什么问题

**Comment by changhu2** [comment]
大佬你添加数据源成功了么
