### ISSUE TITLE
运行任务报错： Non-ASCII character '\x88' in file /usr/bin/python on line 2, but no encoding declared

### ISSUE THREAD

**Issue by shaunsyb** [WeiYe-Jing/datax-web#340]
### 环境说明
操作系统： CentOS Linux release 7.8.2003
Python：系统自带Python2.7.5
DataX Web：2.1.1

### 问题说明
配置DataX Web之后，在页面上运行任务时，出现如下报错：

![image](https://user-images.githubusercontent.com/30490351/94523390-ac42aa00-0263-11eb-8658-61044a4d8726.png)

任务配置页如下：
![image](https://user-images.githubusercontent.com/30490351/94523122-553cd500-0263-11eb-84b4-aacbf42d59f2.png)

这个是从oracle 导入数据到 clickhouse的任务，而在系统上配置json文件，通过datax去执行是没有任何问题的

**Comment by WeiYe-Jing** [comment]
> ### 环境说明
> 操作系统： CentOS Linux release 7.8.2003
> Python：系统自带Python2.7.5
> DataX Web：2.1.1
> 
> ### 问题说明
> 配置DataX Web之后，在页面上运行任务时，出现如下报错：
> 
> `2020-09-29 11:53:16 [JobThread.run-130] <br>----------- datax-web job execute start -----------<br>----------- Param: 2020-09-29 11:53:16 [BuildCommand.buildDataXParam-100] ------------------Command parameters: 2020-09-29 11:53:16 [ExecutorJobHandler.execute-57] ------------------DataX process id: 54532 2020-09-29 11:53:16 [ProcessCallbackThread.callbackLog-186] <br>----------- datax-web job callback finish. 2020-09-29 11:53:16 [AnalysisStatistics.analysisStatisticsLog-53] File "/usr/bin/python", line 1 2020-09-29 11:53:16 [AnalysisStatistics.analysisStatisticsLog-53] SyntaxError: Non-ASCII character '\x88' in file /usr/bin/python on line 2, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details 2020-09-29 11:53:16 [JobThread.run-165] <br>----------- datax-web job execute end(finish) -----------<br>----------- ReturnT:ReturnT [code=500, msg=command exit value(1) is failed, content=null] 2020-09-29 11:53:16 [TriggerCallbackThread.callbackLog-186] <br>----------- datax-web job callback finish.`
> 
> 任务配置页如下：
> ![image](https://user-images.githubusercontent.com/30490351/94523122-553cd500-0263-11eb-84b4-aacbf42d59f2.png)
> 
> 这个是从oracle 导入数据到 clickhouse的任务

先检查下这三个问题，看看是不是正确的
1.检查python环境是否正常
2.如果环境正常检查datax安装是否正常，先用python命令执行datax任务
3.如果上述两项都正常，检查executor的配置文件，检查PYTHON_PATH参数是否配置为datax.py文件的路径
env.properties文件
PYTHON脚本执行位置
PYTHON_PATH=/home/hadoop/install/datax/bin/datax.py

**Comment by shaunsyb** [comment]
重新检查发现是 PYTHON_PATH 变量配置有误
