### ISSUE TITLE
[BUG]python代码，覆盖之前的调度，无法停止任务

### ISSUE THREAD

**Issue by xiaotie-big** [WeiYe-Jing/datax-web#341]
python代码，五秒调度一次，但是脚本十秒执行完，
![image](https://user-images.githubusercontent.com/71999559/94654005-052b4480-032f-11eb-81ac-259f42aa09da.png)
然后，任务无法停止

**Comment by xiaotie-big** [comment]
![image](https://user-images.githubusercontent.com/71999559/94654203-51768480-032f-11eb-879d-cc3cf4e8b14a.png)

**Comment by WeiYe-Jing** [comment]
> python代码，五秒调度一次，但是脚本十秒执行完，
> ![image](https://user-images.githubusercontent.com/71999559/94654005-052b4480-032f-11eb-81ac-259f42aa09da.png)
> 然后，任务无法停止

任务执行的代码和具体配置也贴下，所有python任务都这样吗

**Comment by WeiYe-Jing** [comment]
> > python代码，五秒调度一次，但是脚本十秒执行完，
> > ![image](https://user-images.githubusercontent.com/71999559/94654005-052b4480-032f-11eb-81ac-259f42aa09da.png)
> > 然后，任务无法停止
> 
> #199看了吗

**Comment by WeiYe-Jing** [comment]
> > > python代码，五秒调度一次，但是脚本十秒执行完，
> > > ![image](https://user-images.githubusercontent.com/71999559/94654005-052b4480-032f-11eb-81ac-259f42aa09da.png)
> > > 然后，任务无法停止
> > 
> > 
> > #199 看了吗

**Comment by WeiYe-Jing** [comment]
> > > > python代码，五秒调度一次，但是脚本十秒执行完，
> > > > ![image](https://user-images.githubusercontent.com/71999559/94654005-052b4480-032f-11eb-81ac-259f42aa09da.png)
> > > > 然后，任务无法停止
> > > 
> > > 
> > > #199 看下，检查下脚本写的对不对

**Comment by xiaotie-big** [comment]
代码就是 time.sleep(10)

**Comment by xiaotie-big** [comment]
![image](https://user-images.githubusercontent.com/71999559/94655727-9c919700-0331-11eb-941e-6f9069de6da1.png)

**Comment by xiaotie-big** [comment]
![image](https://user-images.githubusercontent.com/71999559/94655762-a87d5900-0331-11eb-8236-4693b55041db.png)

**Comment by xiaotie-big** [comment]
![image](https://user-images.githubusercontent.com/71999559/94655805-b92dcf00-0331-11eb-8e86-00c05d594ba8.png)

**Comment by xiaotie-big** [comment]
![image](https://user-images.githubusercontent.com/71999559/94655853-cea2f900-0331-11eb-8293-d2fbaa2061a5.png)

**Comment by WeiYe-Jing** [comment]
> 代码就是 time.sleep(10)

看下上面回复或者demo，脚步不对

**Comment by WeiYe-Jing** [comment]
> > 代码就是 time.sleep(10)
> 
> 看下上面回复或者demo，脚步不对，exit(0)必须加。

**Comment by xiaotie-big** [comment]
#!/usr/bin/python
# -*- coding: utf-8 -*-
import time
print('任务')
time.sleep(10)

**Comment by WeiYe-Jing** [comment]
> #!/usr/bin/python
> 
> # -_- coding: utf-8 -_-
> import time
> print('任务')
> time.sleep(10)

什么意思？

**Comment by xiaotie-big** [comment]
> > #!/usr/bin/python
> > # -_- coding: utf-8 -_-
> > import time
> > print('任务')
> > time.sleep(10)
> 
> 什么意思？贴这个干嘛
刚刚不是让我贴上我的代码么，我加上了那个exit(0),还是 无法终止任务，我用的python3

**Comment by WeiYe-Jing** [comment]
> > > #!/usr/bin/python
> > > # -_- coding: utf-8 -_-
> > > import time
> > > print('任务')
> > > time.sleep(10)
> > 
> > 
> > 什么意思？贴这个干嘛

> > 刚刚不是让我贴上我的代码么，我加上了那个exit(0),还是 无法终止任务，我用的python3

时间加长点，kill之后，看下进程在吗

**Comment by xiaotie-big** [comment]
> > > > #!/usr/bin/python
> > > > # -_- coding: utf-8 -_-
> > > > import time
> > > > print('任务')
> > > > time.sleep(10)
> > > 
> > > 
> > > 什么意思？贴这个干嘛
> 
> > > 刚刚不是让我贴上我的代码么，我加上了那个exit(0),还是 无法终止任务，我用的python3
> 
> 时间加长点，kill之后，看下进程在吗

咋kill ,点击 终止任务 还是 kill 他的进程号

**Comment by WeiYe-Jing** [comment]
> > > > > #!/usr/bin/python
> > > > > # -_- coding: utf-8 -_-
> > > > > import time
> > > > > print('任务')
> > > > > time.sleep(10)
> > > > 
> > > > 
> > > > 什么意思？贴这个干嘛
> > 
> > 
> > > > 刚刚不是让我贴上我的代码么，我加上了那个exit(0),还是 无法终止任务，我用的python3
> > 
> > 
> > 时间加长点，kill之后，看下进程在吗
> 
> 咋kill ,点击 终止任务 还是 kill 他的进程号

终止任务就是执行kill pid

**Comment by xiaotie-big** [comment]
> > > > > > #!/usr/bin/python
> > > > > > # -_- coding: utf-8 -_-
> > > > > > import time
> > > > > > print('任务')
> > > > > > time.sleep(10)
> > > > > 
> > > > > 
> > > > > 什么意思？贴这个干嘛
> > > 
> > > 
> > > > > 刚刚不是让我贴上我的代码么，我加上了那个exit(0),还是 无法终止任务，我用的python3
> > > 
> > > 
> > > 时间加长点，kill之后，看下进程在吗
> > 
> > 
> > 咋kill ,点击 终止任务 还是 kill 他的进程号
> 
> 终止任务就是执行kill pid

不好用，有没有别的方法，重启web也不好用，任务还是接着跑，我看日志每隔30秒一条
2020-09-30 15:49:36 [TriggerCallbackThread.callbackLog-186] <br>----------- datax-web job callback fail, callbackResult:ReturnT [code=500, msg=The request data invalid., content=null]

**Comment by WeiYe-Jing** [comment]
> > > > > > > #!/usr/bin/python
> > > > > > > # -_- coding: utf-8 -_-
> > > > > > > import time
> > > > > > > print('任务')
> > > > > > > time.sleep(10)
> > > > > > 
> > > > > > 
> > > > > > 什么意思？贴这个干嘛
> > > > 
> > > > 
> > > > > > 刚刚不是让我贴上我的代码么，我加上了那个exit(0),还是 无法终止任务，我用的python3
> > > > 
> > > > 
> > > > 时间加长点，kill之后，看下进程在吗
> > > 
> > > 
> > > 咋kill ,点击 终止任务 还是 kill 他的进程号
> > 
> > 
> > 终止任务就是执行kill pid
> 
> 不好用，有没有别的方法，重启web也不好用，任务还是接着跑，我看日志每隔30秒一条
> 2020-09-30 15:49:36 [TriggerCallbackThread.callbackLog-186] 
> ----------- datax-web job callback fail, callbackResult:ReturnT [code=500, msg=The request data invalid., content=null]

进程终止了吗

**Comment by xiaotie-big** [comment]
> > > > > > > > #!/usr/bin/python
> > > > > > > > # -_- coding: utf-8 -_-
> > > > > > > > import time
> > > > > > > > print('任务')
> > > > > > > > time.sleep(10)
> > > > > > > 
> > > > > > > 
> > > > > > > 什么意思？贴这个干嘛
> > > > > 
> > > > > 
> > > > > > > 刚刚不是让我贴上我的代码么，我加上了那个exit(0),还是 无法终止任务，我用的python3
> > > > > 
> > > > > 
> > > > > 时间加长点，kill之后，看下进程在吗
> > > > 
> > > > 
> > > > 咋kill ,点击 终止任务 还是 kill 他的进程号
> > > 
> > > 
> > > 终止任务就是执行kill pid
> > 
> > 
> > 不好用，有没有别的方法，重启web也不好用，任务还是接着跑，我看日志每隔30秒一条
> > 2020-09-30 15:49:36 [TriggerCallbackThread.callbackLog-186]
> > ----------- datax-web job callback fail, callbackResult:ReturnT [code=500, msg=The request data invalid., content=null]
> 
> 进程终止了吗

你是说吧 DataXExecutorApplication 和DataXAdminApplication kill 掉么

**Comment by WeiYe-Jing** [comment]
> > > > > > > > > #!/usr/bin/python
> > > > > > > > > # -_- coding: utf-8 -_-
> > > > > > > > > import time
> > > > > > > > > print('任务')
> > > > > > > > > time.sleep(10)
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 什么意思？贴这个干嘛
> > > > > > 
> > > > > > 
> > > > > > > > 刚刚不是让我贴上我的代码么，我加上了那个exit(0),还是 无法终止任务，我用的python3
> > > > > > 
> > > > > > 
> > > > > > 时间加长点，kill之后，看下进程在吗
> > > > > 
> > > > > 
> > > > > 咋kill ,点击 终止任务 还是 kill 他的进程号
> > > > 
> > > > 
> > > > 终止任务就是执行kill pid
> > > 
> > > 
> > > 不好用，有没有别的方法，重启web也不好用，任务还是接着跑，我看日志每隔30秒一条
> > > 2020-09-30 15:49:36 [TriggerCallbackThread.callbackLog-186]
> > > ----------- datax-web job callback fail, callbackResult:ReturnT [code=500, msg=The request data invalid., content=null]
> > 
> > 
> > 进程终止了吗
> 
> 你是说吧 DataXExecutorApplication 和DataXAdminApplication kill 掉么

感觉说的都不是一件事，多看看文档学习下任务运行的基本常识，我的意思是 脚步sleep时间配置长一点，点运行，再点终止任务，再去机器上看下这个任务对应的进程id有没有被kill

**Comment by xiaotie-big** [comment]
![image](https://user-images.githubusercontent.com/71999559/94658854-fb590f80-0335-11eb-9097-0890d6964c36.png)

**Comment by WeiYe-Jing** [comment]
> > > > > > > > > > #!/usr/bin/python
> > > > > > > > > > # -_- coding: utf-8 -_-
> > > > > > > > > > import time
> > > > > > > > > > print('任务')
> > > > > > > > > > time.sleep(10)
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 什么意思？贴这个干嘛
> > > > > > > 
> > > > > > > 
> > > > > > > > > 刚刚不是让我贴上我的代码么，我加上了那个exit(0),还是 无法终止任务，我用的python3
> > > > > > > 
> > > > > > > 
> > > > > > > 时间加长点，kill之后，看下进程在吗
> > > > > > 
> > > > > > 
> > > > > > 咋kill ,点击 终止任务 还是 kill 他的进程号
> > > > > 
> > > > > 
> > > > > 终止任务就是执行kill pid
> > > > 
> > > > 
> > > > 不好用，有没有别的方法，重启web也不好用，任务还是接着跑，我看日志每隔30秒一条
> > > > 2020-09-30 15:49:36 [TriggerCallbackThread.callbackLog-186]
> > > > ----------- datax-web job callback fail, callbackResult:ReturnT [code=500, msg=The request data invalid., content=null]
> > > 
> > > 
> > > 进程终止了吗
> > 
> > 
> > 你是说吧 DataXExecutorApplication 和DataXAdminApplication kill 掉么
> 
> 感觉说的都不是一件事，多看看文档学习下任务运行的基本常识，我的意思是 脚步sleep时间配置长一点，点运行，再点终止任务，再去机器上看下这个任务对应的进程id有没有被kill

或者你直接将重试日志删除再验证这个问题。logging: level: com.wugui.datax.admin.mapper: info path: ./data/applogs 
检查下admin项目log path配置，将下面executor/jobhandler/callback文件删除掉试试

**Comment by xiaotie-big** [comment]
> > > > > > > > > > #!/usr/bin/python
> > > > > > > > > > # -_- coding: utf-8 -_-
> > > > > > > > > > import time
> > > > > > > > > > print('任务')
> > > > > > > > > > time.sleep(10)
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 什么意思？贴这个干嘛
> > > > > > > 
> > > > > > > 
> > > > > > > > > 刚刚不是让我贴上我的代码么，我加上了那个exit(0),还是 无法终止任务，我用的python3
> > > > > > > 
> > > > > > > 
> > > > > > > 时间加长点，kill之后，看下进程在吗
> > > > > > 
> > > > > > 
> > > > > > 咋kill ,点击 终止任务 还是 kill 他的进程号
> > > > > 
> > > > > 
> > > > > 终止任务就是执行kill pid
> > > > 
> > > > 
> > > > 不好用，有没有别的方法，重启web也不好用，任务还是接着跑，我看日志每隔30秒一条
> > > > 2020-09-30 15:49:36 [TriggerCallbackThread.callbackLog-186]
> > > > ----------- datax-web job callback fail, callbackResult:ReturnT [code=500, msg=The request data invalid., content=null]
> > > 
> > > 
> > > 进程终止了吗
> > 
> > 
> > 你是说吧 DataXExecutorApplication 和DataXAdminApplication kill 掉么
> 
> 感觉说的都不是一件事，多看看文档学习下任务运行的基本常识，我的意思是 脚步sleep时间配置长一点，点运行，再点终止任务，再去机器上看下这个任务对应的进程id有没有被kill

**Comment by xiaotie-big** [comment]
> > > > > > > > > > > #!/usr/bin/python
> > > > > > > > > > > # -_- coding: utf-8 -_-
> > > > > > > > > > > import time
> > > > > > > > > > > print('任务')
> > > > > > > > > > > time.sleep(10)
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > 什么意思？贴这个干嘛
> > > > > > > > 
> > > > > > > > 
> > > > > > > > > > 刚刚不是让我贴上我的代码么，我加上了那个exit(0),还是 无法终止任务，我用的python3
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 时间加长点，kill之后，看下进程在吗
> > > > > > > 
> > > > > > > 
> > > > > > > 咋kill ,点击 终止任务 还是 kill 他的进程号
> > > > > > 
> > > > > > 
> > > > > > 终止任务就是执行kill pid
> > > > > 
> > > > > 
> > > > > 不好用，有没有别的方法，重启web也不好用，任务还是接着跑，我看日志每隔30秒一条
> > > > > 2020-09-30 15:49:36 [TriggerCallbackThread.callbackLog-186]
> > > > > ----------- datax-web job callback fail, callbackResult:ReturnT [code=500, msg=The request data invalid., content=null]
> > > > 
> > > > 
> > > > 进程终止了吗
> > > 
> > > 
> > > 你是说吧 DataXExecutorApplication 和DataXAdminApplication kill 掉么
> > 
> > 
> > 感觉说的都不是一件事，多看看文档学习下任务运行的基本常识，我的意思是 脚步sleep时间配置长一点，点运行，再点终止任务，再去机器上看下这个任务对应的进程id有没有被kill

机器上这个进程不存在，我觉得是，这个任务已经被干掉了，但是web还是显示成正在运行

**Comment by WeiYe-Jing** [comment]
> > > > > > > > > > > > #!/usr/bin/python
> > > > > > > > > > > > # -_- coding: utf-8 -_-
> > > > > > > > > > > > import time
> > > > > > > > > > > > print('任务')
> > > > > > > > > > > > time.sleep(10)
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > 什么意思？贴这个干嘛
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > > > 刚刚不是让我贴上我的代码么，我加上了那个exit(0),还是 无法终止任务，我用的python3
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 时间加长点，kill之后，看下进程在吗
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 咋kill ,点击 终止任务 还是 kill 他的进程号
> > > > > > > 
> > > > > > > 
> > > > > > > 终止任务就是执行kill pid
> > > > > > 
> > > > > > 
> > > > > > 不好用，有没有别的方法，重启web也不好用，任务还是接着跑，我看日志每隔30秒一条
> > > > > > 2020-09-30 15:49:36 [TriggerCallbackThread.callbackLog-186]
> > > > > > ----------- datax-web job callback fail, callbackResult:ReturnT [code=500, msg=The request data invalid., content=null]
> > > > > 
> > > > > 
> > > > > 进程终止了吗
> > > > 
> > > > 
> > > > 你是说吧 DataXExecutorApplication 和DataXAdminApplication kill 掉么
> > > 
> > > 
> > > 感觉说的都不是一件事，多看看文档学习下任务运行的基本常识，我的意思是 脚步sleep时间配置长一点，点运行，再点终止任务，再去机器上看下这个任务对应的进程id有没有被kill
> 
> 机器上这个进程不存在，我觉得是，这个任务已经被干掉了，但是web还是显示成正在运行

可能是你第一次脚步不对，没有加exit，任务无法识别成功还是失败，导致不断重试，你可以将log下jobhandler文件中的删掉再试下

**Comment by xiaotie-big** [comment]
日志一直生成的解决办法：
删掉datax-web-master/build/datax-web-2.1.2/modules/datax-executor/data/applogs/executor/jobhandler/callbacklog
下的日志，日志不在生成，群主说还要删掉datax-web-master/build/datax-web-2.1.2/modules/datax-executor/data/applogs/executor/jobhandler/processcallbacklog
我这这歌路径下没有文件，所以没删。

但是web上的任务还是原来的那个样子，正在运行，无法终止任务
我的脚本和配置长这个样子
![image](https://user-images.githubusercontent.com/71999559/94665527-d7e69280-033e-11eb-9e40-c0c3c0c304d8.png)

**Comment by SweetCarter** [comment]
我也遇到了相同的打印问题，但我这边是一个datax的任务，也是设置的覆盖之前调度出现的打印bug，并且任务无法关闭，应该怎么解决呢？
![image](https://user-images.githubusercontent.com/44425482/180164889-43223cb1-e9be-4ad5-bac0-a1be853b0059.png)
`{
  "job": {
    "setting": {
      "speed": {
        "channel": 3,
        "byte": 1048576
      },
      "errorLimit": {
        "record": 0,
        "percentage": 0.02
      }
    },
    "content": [
      {
        "reader": {
          "name": "mysqlreader",
          "parameter": {
            "username": "etrOXf+qb7FT9XMkN+bPUQ==",
            "password": "IZabtkFfFkfpApU4gQTpHQ==",
            "splitPk": "",
            "connection": [
              {
                "querySql": [
                  "SELECT `id`, `external_id`, `code`, `external_code`, `name`, `commo_id`, `attri_val_id1`, `attri_val_id2`, `tm`, `barcode`, `inx1`, `inx2`, `plu_code` FROM adlink.ds_md_commo_sku_01 UNION ALL SELECT `id`, `external_id`, `code`, `external_code`, `name`, `commo_id`, `attri_val_id1`, `attri_val_id2`, `tm`, `barcode`, `inx1`, `inx2`, `plu_code` FROM adlink.ds_md_commo_sku_02 UNION ALL SELECT `id`, `external_id`, `code`, `external_code`, `name`, `commo_id`, `attri_val_id1`, `attri_val_id2`, `tm`, `barcode`, `inx1`, `inx2`, `plu_code` FROM adlink.ds_md_commo_sku_03"
                ],
                "jdbcUrl": [
                  "jdbc:mysql://10.0.47.202:13306/adlink?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false"
                ]
              }
            ]
          }
        },
        "writer": {
          "name": "mysqlwriter",
          "parameter": {
            "username": "etrOXf+qb7FT9XMkN+bPUQ==",
            "password": "IZabtkFfFkfpApU4gQTpHQ==",
            "column": [
              "`id`",
              "`external_id`",
              "`code`",
              "`external_code`",
              "`name`",
              "`commo_id`",
              "`attri_val_id1`",
              "`attri_val_id2`",
              "`tm`",
              "`barcode`",
              "`inx1`",
              "`inx2`",
              "`plu_code`"
            ],
            "writeMode": "update(id)",
            "connection": [
              {
                "table": [
                  "md_commo_sku"
                ],
                "jdbcUrl": "jdbc:mysql://10.0.47.202:13306/adchanl?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false"
              }
            ]
          }
        }
      }
    ]
  }
}`

**Comment by SweetCarter** [comment]
我也出现了同样的BUG。也是使用的 覆盖之前调度 的阻塞策略，出现了打印问题。
![image](https://user-images.githubusercontent.com/44425482/180181240-9462300b-6db8-4605-8998-8016d2876053.png)

脚本：
{
  "job": {
    "setting": {
      "speed": {
        "channel": 3,
        "byte": 1048576
      },
      "errorLimit": {
        "record": 0,
        "percentage": 0.02
      }
    },
    "content": [
      {
        "reader": {
          "name": "mysqlreader",
          "parameter": {
            "username": "etroxf+qb7ft9xmkn+bpuq==",
            "password": "etroxf+qb7ft9xmkn+bpuq==",
            "splitPk": "",
            "connection": [
              {
                "querySql": [
                  "SELECT `id`, `code`, `barcode`, `py_code`, `name`, `full_name`, `classification`, `unit`, `art_no`, `design_color`, `specification`, `quality_level`, `texture_content`, `uses`, `remark`, `mark_packed`, `mark_bulk`, `input_vat_rate`, `sale_vat_rate`, `consumption_tax_rate`, `type`, `day_exp`, `stats_proportion`, `input_perid`, `input_pern`, `input_date`, `update_perid`, `update_pern`, `update_date`, `audit_perid`, `audit_pern`, `audit_date`, `region_id`, `limit_min_price`, `min_price`, `decimal_quantity`, `status`, `mark_special_offer`, `brandid`, `mark_cl`, `barcode_type`, `mark_stock`, `mark_manage_stock`, `weight`, `classification_online` FROM adlink.ds_md_commodity_info_01 UNION ALL SELECT `id`, `code`, `barcode`, `py_code`, `name`, `full_name`, `classification`, `unit`, `art_no`, `design_color`, `specification`, `quality_level`, `texture_content`, `uses`, `remark`, `mark_packed`, `mark_bulk`, `input_vat_rate`, `sale_vat_rate`, `consumption_tax_rate`, `type`, `day_exp`, `stats_proportion`, `input_perid`, `input_pern`, `input_date`, `update_perid`, `update_pern`, `update_date`, `audit_perid`, `audit_pern`, `audit_date`, `region_id`, `limit_min_price`, `min_price`, `decimal_quantity`, `status`, `mark_special_offer`, `brandid`, `mark_cl`, `barcode_type`, `mark_stock`, `mark_manage_stock`, `weight`, `classification_online` FROM adlink.ds_md_commodity_info_02 UNION ALL SELECT `id`, `code`, `barcode`, `py_code`, `name`, `full_name`, `classification`, `unit`, `art_no`, `design_color`, `specification`, `quality_level`, `texture_content`, `uses`, `remark`, `mark_packed`, `mark_bulk`, `input_vat_rate`, `sale_vat_rate`, `consumption_tax_rate`, `type`, `day_exp`, `stats_proportion`, `input_perid`, `input_pern`, `input_date`, `update_perid`, `update_pern`, `update_date`, `audit_perid`, `audit_pern`, `audit_date`, `region_id`, `limit_min_price`, `min_price`, `decimal_quantity`, `status`, `mark_special_offer`, `brandid`, `mark_cl`, `barcode_type`, `mark_stock`, `mark_manage_stock`, `weight`, `classification_online` FROM adlink.ds_md_commodity_info_03"
                ],
                "jdbcUrl": [
                  "jdbc:mysql://127.0.0.1:13306/adlink?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false"
                ]
              }
            ]
          }
        },
        "writer": {
          "name": "mysqlwriter",
          "parameter": {
            "username": "etroxf+qb7ft9xmkn+bpuq==",
            "password": "etroxf+qb7ft9xmkn+bpuq==",
            "column": [
              "`id`",
              "`code`",
              "`barcode`",
              "`py_code`",
              "`name`",
              "`full_name`",
              "`classification`",
              "`unit`",
              "`art_no`",
              "`design_color`",
              "`specification`",
              "`quality_level`",
              "`texture_content`",
              "`uses`",
              "`remark`",
              "`mark_packed`",
              "`mark_bulk`",
              "`input_vat_rate`",
              "`sale_vat_rate`",
              "`consumption_tax_rate`",
              "`type`",
              "`day_exp`",
              "`stats_proportion`",
              "`input_perid`",
              "`input_pern`",
              "`input_date`",
              "`update_perid`",
              "`update_pern`",
              "`update_date`",
              "`audit_perid`",
              "`audit_pern`",
              "`audit_date`",
              "`region_id`",
              "`limit_min_price`",
              "`min_price`",
              "`decimal_quantity`",
              "`status`",
              "`mark_special_offer`",
              "`brandid`",
              "`mark_cl`",
              "`barcode_type`",
              "`mark_stock`",
              "`mark_manage_stock`",
              "`weight`",
              "`classification_online`"
            ],
            "writeMode": "update(id)",
            "connection": [
              {
                "table": [
                  "md_commodity_info"
                ],
                "jdbcUrl": "jdbc:mysql://127.0.0.1:13306/adchanl?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false"
              }
            ]
          }
        }
      }
    ]
  }
}
![image](https://user-images.githubusercontent.com/44425482/180182198-0c07d550-91d1-4286-9d34-36c10a6be0ee.png)

![image](https://user-images.githubusercontent.com/44425482/180182087-c312e9ca-897c-4925-a289-04369cd52d08.png)

这个问题能通过改 json 解决吗？能提供下解决方案吗？
