### ISSUE TITLE
关于任务的执行问题

### ISSUE THREAD

**Issue by LxqGit-blip** [WeiYe-Jing/datax-web#343]
您好，通过构建任务生成任务后，启动任务后，后台是怎么执行这些任务的呢？是由某一个具体的类执行的吗？

**Comment by WeiYe-Jing** [comment]
> 您好，通过构建任务生成任务后，启动任务后，后台是怎么执行这些任务的呢？是由某一个具体的类执行的吗？

任务启动后会根据配置的cron表达式定时触发

**Comment by LxqGit-blip** [comment]
那是在哪里触发的定时任务呢？是有一个具体的类操作的吗？

**Comment by WeiYe-Jing** [comment]
> 那是在哪里触发的定时任务呢？是有一个具体的类操作的吗？

这块要看下Trigger相关的代码
