### ISSUE TITLE
关于父子任务的问题

### ISSUE THREAD

**Issue by LxqGit-blip** [WeiYe-Jing/datax-web#344]
如果一个父任务里有两个子任务，且这两个子任务里面又有一个相同的另一个子任务，当我启动父任务的时候，执行相同子任务的时候会有一个成功，一个失败，成功和失败的任务是相同的任务，只不过分别属于不同的父任务，这是为什么？是因为有一个已经成功执行了所以另外一个就不执行了吗？

**Comment by WeiYe-Jing** [comment]
> 如果一个父任务里有两个子任务，且这两个子任务里面又有一个相同的另一个子任务，当我启动父任务的时候，执行相同子任务的时候会有一个成功，一个失败，成功和失败的任务是相同的任务，只不过分别属于不同的父任务，这是为什么？是因为有一个已经成功执行了所以另外一个就不执行了吗？

没明白是那一层有失败的任务，除了父子任务，分支节点的任务之间没什么关系
