### ISSUE TITLE
任务配置问题

### ISSUE THREAD

**Issue by LxqGit-blip** [WeiYe-Jing/datax-web#345]
是不是允许配置相同任务呢？如果存在相同的子任务时候，是不是只会执行其中一个，另外一个就不会执行了？

**Comment by WeiYe-Jing** [comment]
> 是不是允许配置相同任务呢？如果存在相同的子任务时候，是不是只会执行其中一个，另外一个就不会执行了？

不会的，没有这个处理，你可以看下失败任务执行失败的原因

**Comment by LxqGit-blip** [comment]
相同子任务中有一个子任务在执行了ExecutorBizImpl的
if (jobThread.isRunningOrHasQueue()) {
                    return new ReturnT<>(ReturnT.FAIL_CODE, "block strategy effect：" + 
                    ExecutorBlockStrategyEnum.DISCARD_LATER.getTitle());
}就停止了

**Comment by LxqGit-blip** [comment]
如果把这个判断给注释掉的话就都可以执行成功

**Comment by LxqGit-blip** [comment]
是不是跟任务配置的阻塞处理方式有关，丢弃后续调度就是如果有相同的任务，执行过之后，其他的就丢弃，所以没有执行？

**Comment by WeiYe-Jing** [comment]
> 是不是跟任务配置的阻塞处理方式有关，丢弃后续调度就是如果有相同的任务，执行过之后，其他的就丢弃，所以没有执行？

跟阻塞策略是有关的，如果你的阻塞策略配置的丢失，会这样处理

**Comment by LxqGit-blip** [comment]
好的，我明白了，所以是可以配置相同的子任务的是吗？

**Comment by WeiYe-Jing** [comment]
> 好的，我明白了，所以是可以配置相同的子任务的是吗？

可以的
