### ISSUE TITLE
关于配置任务中获取作业配置信息失败问题

### ISSUE THREAD

**Issue by LxqGit-blip** [WeiYe-Jing/datax-web#346]
在配置任务中配置了相同的子任务的时候，阻塞处理设置的是覆盖之前调度，结果就报了获取作业配置信息失败的错误，是一个临时文件找不到了，这个是什么原因导致的啊？
![image](https://user-images.githubusercontent.com/71811909/95724146-93e17f00-0ca8-11eb-8816-fa75881d452c.png)

**Comment by WeiYe-Jing** [comment]
> 在配置任务中配置了相同的子任务的时候，阻塞处理设置的是覆盖之前调度，结果就报了获取作业配置信息失败的错误，是一个临时文件找不到了，这个是什么原因导致的啊？
> ![image](https://user-images.githubusercontent.com/71811909/95724146-93e17f00-0ca8-11eb-8816-fa75881d452c.png)

任务执行过程中有删除临时json文件吗

**Comment by LxqGit-blip** [comment]
只是删错了一些日志文件

**Comment by LxqGit-blip** [comment]
那如果是误删了怎么办？

**Comment by LxqGit-blip** [comment]
我重新执行之后也还是会报这个错误

**Comment by WeiYe-Jing** [comment]
> 我重新执行之后也还是会报这个错误

检查下配置，配个存在的文件夹就行了

**Comment by LxqGit-blip** [comment]
那怎么把这些报错的给停止呢？

**Comment by LxqGit-blip** [comment]
是在执行的时候如果有相同的子任务时，会有其中一个子任务没有创建临时的json文件，所以找不到，这是为什么？

**Comment by WeiYe-Jing** [comment]
> 是在执行的时候如果有相同的子任务时，会有其中一个子任务没有创建临时的json文件，所以找不到，这是为什么？

任务状态改为停止就行了，两个相同的子任务如果策略是丢弃下一个，那第二次触发是不会执行的，不需要json文件

**Comment by LxqGit-blip** [comment]
如果想让这些子任务都执行，第二次触发的时候又没有创建json文件，json保存的文件夹是存在的，会是什么原因导致的呢？

**Comment by LxqGit-blip** [comment]
项目中日志提示[{"logId":189,"logDateTim":1602560961000,"executeResult":{"code":500,"msg":"block strategy effectCover Early [job running, killed]","content":null}}]"; line: 1, column: 99]，是不是就是因为子任务执行的时候没有创建json文件引起的报错？这些报错信息重新启动项目也还是会有，是由于某个类重复调用引起的吗？

**Comment by weichao953** [comment]
[{"logId":189,"logDateTim":1602560961000,"executeResult":{"code":500,"msg":"block strategy effect�Cover Early [job running, killed]","content":null}}]"; line: 1, column: 99]这个问题解决了么？
