### ISSUE TITLE
[BUG] [mongodbwriter] 生成的 com.alibaba.datax.common.exception.DataXException: ILLEGAL_VALUE - 不合法参数

### ISSUE THREAD

**Issue by gmywq** [WeiYe-Jing/datax-web#349]
**com.alibaba.datax.common.exception.DataXException: ILLEGAL_VALUE - 不合法参数**

**建议调整**
job_jdbc_datasource 添加 address 字段

datax 版本:  userGuid.md 里的下载地址， writer 中的 mongodbwriter-0.0.1-SNAPSHOT.jar 
其中 writer plugin 中 MongoUtil.java 有如下逻辑：

` public static MongoClient initMongoClient(Configuration conf) {

        List<Object> addressList = conf.getList(KeyConstant.MONGO_ADDRESS);
        if(addressList == null || addressList.size() <= 0) {
            throw DataXException.asDataXException(MongoDBWriterErrorCode.ILLEGAL_VALUE,"不合法参数");
        }
        try {
            return new MongoClient(parseServerAddress(addressList));
        } catch (UnknownHostException e) {
           throw DataXException.asDataXException(MongoDBWriterErrorCode.ILLEGAL_ADDRESS,"不合法的地址");
        } catch (NumberFormatException e) {
           throw DataXException.asDataXException(MongoDBWriterErrorCode.ILLEGAL_VALUE,"不合法参数");
        } catch (Exception e) {
            throw DataXException.asDataXException(MongoDBWriterErrorCode.UNEXCEPT_EXCEPTION,"未知异常");
        }
    }`

在校验 KeyConstant.MONGO_ADDRESS 字段是序列化 json 后的 "address"，而通过当前 datax-executor 中的 JobDatasourceService 生成的 JobDatasource 并没有该字段。

导致使用构建 json 的功能时，遇到 mongo 的目标数据源，会出现如下错误：

`经DataX智能分析,该任务最可能的错误原因是:
com.alibaba.datax.common.exception.DataXException: ILLEGAL_VALUE - 不合法参数
	at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:26)
	at com.alibaba.datax.plugin.writer.mongodbwriter.util.MongoUtil.initMongoClient(MongoUtil.java:22)
	at com.alibaba.datax.plugin.writer.mongodbwriter.MongoDBWriter$Task.init(MongoDBWriter.java:326)
	at com.alibaba.datax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:44)
	at java.base/java.lang.Thread.run(Thread.java:834)`。

**复现步骤**
1. 任务构建时，选择目标数据源 mongodb 类型
2. 使用默认的构建 json
3. 执行一次

**期望的 writer 段 json **
```
"writer": {
          "name": "mongodbwriter",
          "parameter": {
            "userName": "",
            "userPassword": "",
            "dbName": "test",
            "address": ["127.0.0.1:27017"], 
            "collectionName": "test_collection",
            "column": [
              {
                "name": "id",
                "type": "Integer"
              },
              {
                "name": "app_name",
                "type": "String"
              }
            ],
            "upsertInfo": {
              "isUpsert": true,
              "upsertKey": "id"
            }
          }
        }
```
**生成的 writer 段 json **

```
"writer": {
          "name": "mongodbwriter",
          "parameter": {
            "userName": "",
            "userPassword": "",
            "dbName": "test",
            "collectionName": "test_collection",
            "column": [
              {
                "name": "id",
                "type": "Integer"
              },
              {
                "name": "app_name",
                "type": "String"
              }
            ],
            "upsertInfo": {
              "isUpsert": true,
              "upsertKey": "id"
            }
          }
        }
```

**Which version of DataX Web:**
 - master 主分支的代码

**Comment by czetao** [comment]
这个bug真滴是。可恶

**Comment by WeiYe-Jing** [comment]
这是2.1.1分支吗，2.1.2版本这块已经修改了

**Comment by tarzanwill** [comment]
现在才注意到，应该没问题了。感谢~
