### ISSUE TITLE
关于任务之间的依赖关系问题

### ISSUE THREAD

**Issue by LxqGit-blip** [WeiYe-Jing/datax-web#351]
对于各个任务之间的关系，比如a任务的子任务有b任务和c任务，b任务和c任务拥有相同的子任务d，那么在启动a任务的时候后面的子任务是不是必须等前面的任务执行完以后才会继续还是说触发后同时执行？

**Comment by WeiYe-Jing** [comment]
> 对于各个任务之间的关系，比如a任务的子任务有b任务和c任务，b任务和c任务拥有相同的子任务d，那么在启动a任务的时候后面的子任务是不是必须等前面的任务执行完以后才会继续还是说触发后同时执行？

bc任务同时运行，b任务成功后运行d任务，c任务成功后也运行d任务

**Comment by LxqGit-blip** [comment]
如果想让d任务执行的时候必须前面的任务都执行完毕后再执行的话，要如何做呢？

**Comment by WeiYe-Jing** [comment]
> 如果想让d任务执行的时候必须前面的任务都执行完毕后再执行的话，要如何做呢？

你可以考虑对这块引入DAG

**Comment by LxqGit-blip** [comment]
明白了
