### ISSUE TITLE
[QUESTION] 时间增量与HIVE分区

### ISSUE THREAD

**Issue by KanaSukita** [WeiYe-Jing/datax-web#357]
Hi

根据[partition-dynamic-param](https://github.com/WeiYe-Jing/datax-web/blob/master/doc/datax-web/partition-dynamic-param.md)，可以同时设定增量时间与HIVE分区，但是在编辑任务时，发现只能编辑一个辅助参数，即时间增量和HIVE中的一个，分辨单独编辑了这两个参数，单独使用都可以生效，但是无法同时使用，请问如何同时编辑这两种辅助参数？

**Comment by KanaSukita** [comment]
如图，无法同时编辑，请问如何能像文档中一样添加一条辅助参数？
![HIVE分区](https://user-images.githubusercontent.com/32619535/96537336-96576080-12c8-11eb-8412-46f2d9d12efa.png)
![时间增量](https://user-images.githubusercontent.com/32619535/96537346-9d7e6e80-12c8-11eb-9623-bc1f39460f67.png)

**Comment by WeiYe-Jing** [comment]
下个版本会支持

**Comment by KanaSukita** [comment]
> 
> 
> 下个版本会支持

了解，可以问一下下一个版本大概什么时候出吗？

**Comment by WeiYe-Jing** [comment]
> > 下个版本会支持
> 
> 了解，可以问一下下一个版本大概什么时候出吗？

dev分支已经实现了，目前在最后收尾阶段，欢迎测试
