### ISSUE TITLE
#93

### ISSUE THREAD

**Issue by roobbin** [WeiYe-Jing/datax-web#360]
组织：新翔科技
地点：杭州研发中心
联系方式：Email：roobbin@yeah.net
场景：使用DataX做异构数据源同步，项目选择数据源即可构建json极大提升了同步效率。

**Comment by WeiYe-Jing** [comment]
> 组织：新翔科技
> 地点：杭州研发中心
> 联系方式：Email：[roobbin@yeah.net](mailto:roobbin@yeah.net)
> 场景：使用DataX做异构数据源同步，项目选择数据源即可构建json极大提升了同步效率。

麻烦登记在这里，感谢！#93

**Comment by WeiYe-Jing** [comment]
![image](https://user-images.githubusercontent.com/33245094/97127804-95657980-1775-11eb-9ed2-149680d382ac.png)
我的意思是 登记加到 #93这个issue中，你在下面直接回复就行了

**Comment by WeiYe-Jing** [comment]
> ![image](https://user-images.githubusercontent.com/33245094/97127804-95657980-1775-11eb-9ed2-149680d382ac.png)
> 我的意思是 登记加到 #93这个issue中，你在下面直接回复就行了

在连接这个页面回复就行哈 https://github.com/WeiYe-Jing/datax-web/issues/93
