### ISSUE TITLE
[BUG] 当增量时间格式为yyyy-MM-dd HH:mm:ss是，会报错，时间格式有问题

### ISSUE THREAD

**Issue by mxlib** [WeiYe-Jing/datax-web#367]
错误日志如下：
2020-10-30 11:10:36 [BuildCommand.buildDataXParam-100] ------------------Command parameters:-p"-DlastTime='2020-09-01**%**00:00:00' -DcurrentTime='2020-10-30**%**11:10:35'"
……
具体错误信息为：java.sql.SQLException: Syntax error during implicit conversion of VARCHAR value '2020-09-01%00:00:00' to a DATETIME field.

**Comment by WeiYe-Jing** [comment]
> 错误日志如下：
> 2020-10-30 11:10:36 [BuildCommand.buildDataXParam-100] ------------------Command parameters:-p"-DlastTime='2020-09-01**%**00:00:00' -DcurrentTime='2020-10-30**%**11:10:35'"
> ……
> 具体错误信息为：java.sql.SQLException: Syntax error during implicit conversion of VARCHAR value '2020-09-01%00:00:00' to a DATETIME field.

这个问题是之前对时间空格转义处理，导致部分数据源不支持该时间格式，建议使用时间戳。问题已经在dev分支解决了，新版近期会发布欢迎测试，

**Comment by mxlib** [comment]
看了你dev分支的代码，直接去掉空格转义还是有问题的，我试过，会直接报如下错误
error: Could not find or load main class 00:00:00'

**Comment by RankRao** [comment]
我下的，v-2.1.2（09 Jul 2020）的版本，还是有这个时间空格变成%的问题

**Comment by luobingit** [comment]
master 还是有这个问题  数据源为sqlserver
