### ISSUE TITLE
[QUESTION] 如何添加web界面用户和密码

### ISSUE THREAD

**Issue by KanaSukita** [WeiYe-Jing/datax-web#392]
*For better global communication, please give priority to using English description, thx! *

**Describe the question**
现在登录web界面都是用默认的admin，密码123456。尝试直接对job_user表添加用户（sql如下，但生成的密码长度好像不对），但登录失败，请问如何添加web界面的用户

添加用户的sql:
insert into job_user(username, password, role) values('test_user', password('test_password'), 'ROLE_ADMIN');

**Which version of DataX Web:**
 -[2.1.2]

**Comment by WeiYe-Jing** [comment]
用户管理菜单中可以添加
