### ISSUE TITLE
mysql8兼容有问题

### ISSUE THREAD

**Issue by CriysHot** [WeiYe-Jing/datax-web#395]
*For better global communication, please give priority to using English description, thx! *

**Describe the question**
A clear and concise description of what the question is.
用mysql8做资源库存任务会连接不上数据库，我折腾好久最终降到5.7了

**Which version of DataX Web:**
 -[2.1.1]

**Additional context**

**Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by xuze1993** [comment]
好像确实有此问题。可以看到表结构，但是执行构建任务就报错连不上数据库。

**Comment by weihebu** [comment]
你把datax关于mysql的驱动更新试试。

**Comment by luengmingbiao** [comment]
@CriysHot 我也遇到这个问题，你把datax的mysql读写插件的驱动更新到8版本即可解决
