### ISSUE TITLE
datax转换的问题

### ISSUE THREAD

**Issue by MarksMeng** [WeiYe-Jing/datax-web#4]
官方文档：dx_groovy只能调用一次。不能多次调用。（[https://github.com/alibaba/DataX/blob/master/transformer/doc/transformer.md]）
请问这个只能调用一次，当调度执行的时候怎么办？你是怎么解决的？

**Comment by WeiYe-Jing** [comment]
datax-web目前的功能主要针对datax的使用做一些可视化操作，对datax的Transformer没做修改。
