### ISSUE TITLE
[QUESTION] 任务管理报错是咋回事

### ISSUE THREAD

**Issue by czxin788** [WeiYe-Jing/datax-web#401]
*For better global communication, please give priority to using English description, thx! *

**Describe the question**
### Error querying database. Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 't.user_id' in 'field list' ### The error may exist in file [/root/czx/datax-web-2.1.2/modules/datax-admin/conf/mybatis-mapper/JobInfoMapper.xml] ### The error may involve com.wugui.datax.admin.mapper.JobInfoMapper.pageList-Inline ### The error occurred while setting parameters ### SQL: SELECT t.id, t.job_group, t.job_cron, t.job_desc, t.add_time, t.update_time, t.user_id, t.alarm_email, t.executor_route_strategy, t.executor_handler, t.executor_param, t.executor_block_strategy, t.executor_timeout, t.executor_fail_retry_count, t.glue_type, t.glue_source, t.glue_remark, t.glue_updatetime, t.child_jobid, t.trigger_status, t.trigger_last_time, t.trigger_next_time, t.job_json, t.replace_param, t.jvm_param, t.inc_start_time, t.partition_info, t.last_handle_code, t.replace_param_type, t.project_id, t.reader_table, t.primary_key, t.inc_start_id, t.increment_type, t.datasource_id , p.name as project_name, u.username FROM job_info AS t INNER JOIN job_project p on t.project_id=p.id INNER JOIN job_user u on t.user_id = u.id ORDER BY id DESC LIMIT ?, ? ### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 't.user_id' in 'field list' ; bad SQL grammar []; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 't.user_id' in 'field list

![image](https://user-images.githubusercontent.com/13861904/102760861-15dcdb00-43b1-11eb-92d7-bb031b8a6e72.png)

**Which version of DataX Web:**
 -[2.1.2]

**Requirement or improvement
-centos 7

**Comment by Robert-Qiu** [comment]
I got the same error
I seems no user_id column in job_info table

**Comment by Robert-Qiu** [comment]
> I got the same error
> I seems no user_id column in job_info table

I find the script in the development version, it solve the problem.

ALTER TABLE `job_info`
CHANGE COLUMN `author` `user_id` INT(11) NOT NULL COMMENT '修改用户' ;

an other alter script is, may be need executed too.

ALTER TABLE `job_info`
CHANGE COLUMN `increment_type` `increment_type` TINYINT(4) NULL DEFAULT 0 COMMENT '增量类型' ;

**Comment by notfresh** [comment]
ALTER TABLE job_info
CHANGE COLUMN author user_id INT(11) NOT NULL COMMENT '修改用户' ;

This works!
Thanks @Robert-Qiu

however, I reviewed the job_info table and found the increment_type is TINYINT(4) , no need to update again. (2023-05-08)


ALTER TABLE job_info
CHANGE COLUMN increment_type increment_type TINYINT(4) NULL DEFAULT 0 COMMENT '增量类型' ;

**Comment by czxin788** [comment]
good
