### ISSUE TITLE
[QUESTION]   js和css为啥没有源码啊，都是压缩的。

### ISSUE THREAD

**Issue by 2222** [WeiYe-Jing/datax-web#405]
发现都是chunk的

**Comment by LockiJiang** [comment]
**但凡是看了文档的都不会问出这样的问题**

![图片](https://user-images.githubusercontent.com/16129287/102993006-59714980-4557-11eb-810b-5077313376db.png)

https://github.com/WeiYe-Jing/datax-web-ui
