### ISSUE TITLE
点击查看日志，页面报请求超时异常

### ISSUE THREAD

**Issue by WeiYe-Jing** [WeiYe-Jing/datax-web#42]
当任务日志超过6M左右，页面点击查看日志，请求超时

**Comment by waterWang** [comment]
问题原因：
1.datax在运行时将异常数据打印到 log中导致log很大
2.netty在响应时候会读取log文件，导致Response entity too large

解决方法：
第一种：.构建datax.json 时候添加 errorLimit阈值，如果大于阈值任务自动失败
  具体操作
"errorLimit": {
        "record": 10,  //脏数据行数
        "percentage": 0.05 // 脏数据百分比
      }
第二种：将log日志格式修改
原来  2020-03-13 18:45:51 [com.wugui.datatx.core.thread.JobThread#run]-[130]-[Thread-18] <br>----------- datax-web job execute start -----------<br>----------- Param:
现在 2020-03-13 18:56:41 [JobThread.run-130] <br>----------- datax-web job execute start -----------<br>----------- Param:
具体操作：修改JobLogger中logDetail方法

第三种：增大netty response阈值（原来是5*1024*1024=5M）
具体操作 修改NettyHttpConnectClient和NettyHttpServer中HttpObjectAggregator值
