### ISSUE TITLE
[吐槽] 吐槽

### ISSUE THREAD

**Issue by kocham** [WeiYe-Jing/datax-web#433]
部署配置看不懂，各个端口分别是啥含义，整了一下午没整明白，configure.sh执行无效

admin-web页面体验反人类，编辑窗口不小心就隐藏了， 流程搞到一半搞不下去了，重开窗口再搞前面的

还有更可恶的cron设置设计，随便一个简单的编辑框都比这强，搞那么复杂干嘛啊

垃圾中的垃圾

**Comment by carlos-ouyang** [comment]
I'm afraid it's your own fault. Trying to understand more about JAVA opensource project and then you'll find out how shallow you are.

**Comment by qxl1231** [comment]
louzhu sb, you can you up, no can no bb
