### ISSUE TITLE
权限管理是不是有点弱

### ISSUE THREAD

**Issue by fan-code** [WeiYe-Jing/datax-web#450]
dataxWeb是一个非常优秀的开源工具，不过在权限管理这块是不是有点太弱了！
用户管理基本形同虚设，任何用户都有admin权限，可以操作项目编辑删除，任务编辑删除以及数据源编辑删除
有计划在权限管理方面进行优化么？

**Comment by WeiYe-Jing** [comment]
目前开发的2.1.3版本暂无计划，也欢迎提出一些权限控制的方案到社区一起讨论。
