### ISSUE TITLE
[BUG] “执行器管理页面”无法自动注册

### ISSUE THREAD

**Issue by aa-yii** [WeiYe-Jing/datax-web#454]
![image](https://user-images.githubusercontent.com/45238200/114995092-0b9a9b80-9ed0-11eb-8ae7-4ae46a8d2263.png)
![image](https://user-images.githubusercontent.com/45238200/114995320-47356580-9ed0-11eb-8774-40568f14dffa.png)
![datax-web-bug](https://user-images.githubusercontent.com/45238200/114996841-d2632b00-9ed1-11eb-8403-a559216634f5.gif)
具体参见上面的gif图，修改名称后，执行器的节点就没有了。。。

尝试了

1. 重启admin和executor，无效；

2. 直接修改job_registry中的registry_key字段，将其从datax-executor直接改为datax-executor2，过一会儿重新刷新页面，两个都有了。![image](https://user-images.githubusercontent.com/45238200/114997441-69c87e00-9ed2-11eb-8775-17f63fad6821.png)
而且在job_registry表中，除了修改的那条记录，会增加一条注册记录，registry_key为“datax-executor”
![image](https://user-images.githubusercontent.com/45238200/114997514-7f3da800-9ed2-11eb-95ad-c66c8edce0b1.png)

疑问：
所以默认executor向admin注册，默认是“datax-executor”而不能是其他的，还是在哪儿有配置，我没找到。。

**Comment by aa-yii** [comment]
而且更奇葩的是，尝试1直接修改job_registry中的registry_key字段，过了一段时间后，被修改的那条记录消失了，只有后面新加的那条。。。。
![image](https://user-images.githubusercontent.com/45238200/114998829-e90a8180-9ed3-11eb-9029-d7c581a3a101.png)

**Comment by LockiJiang** [comment]
但凡是认真把文档看完的都知道执行器是根据AppName注册的
![图片](https://user-images.githubusercontent.com/16129287/115337778-33417a80-a1d4-11eb-8e61-8ffb52a277a9.png)
https://github.com/WeiYe-Jing/datax-web
![图片](https://user-images.githubusercontent.com/16129287/115337665-fbd2ce00-a1d3-11eb-92dd-5409fc1a0c1c.png)
https://github.com/WeiYe-Jing/datax-web/blob/master/userGuid.md

**Comment by aa-yii** [comment]
> 但凡是认真把文档看完的都知道执行器是根据AppName注册的
> ![图片](https://user-images.githubusercontent.com/16129287/115337778-33417a80-a1d4-11eb-8e61-8ffb52a277a9.png)
> https://github.com/WeiYe-Jing/datax-web
> ![图片](https://user-images.githubusercontent.com/16129287/115337665-fbd2ce00-a1d3-11eb-92dd-5409fc1a0c1c.png)
> https://github.com/WeiYe-Jing/datax-web/blob/master/userGuid.md

感谢感谢！！是我太浮躁了，没看仔细 : )
