### ISSUE TITLE
下载源码启动了一下，代码bug还挺多的

### ISSUE THREAD

**Issue by ONE-JIN** [WeiYe-Jing/datax-web#462]
*For better global communication, please give priority to using English description, thx! *

**Describe the question**
A clear and concise description of what the question is.

**Which version of DataX Web:**
 -[2.1.1]

**Additional context**

**Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by WeiYe-Jing** [comment]
欢迎提出具体的问题
