### ISSUE TITLE
有人能够指导下短信功能怎么拓展吗？

### ISSUE THREAD

**Issue by weihebu** [WeiYe-Jing/datax-web#476]
我查看xxl-job项目有EmailJobAlarm这个类，但是这个项目却没有发现相似的类。或者说job那边整个类的目录都不在了，所以不知道web怎么是怎么实现邮件的，更不知道怎么拓展短信功能。。。

**Comment by LockiJiang** [comment]
https://github.com/WeiYe-Jing/datax-web/blob/dev/datax-admin/src/main/java/com/wugui/datax/admin/core/thread/JobFailMonitorHelper.java

**Comment by weihebu** [comment]
感谢。
