### ISSUE TITLE
datax.py 找不到

### ISSUE THREAD

**Issue by xiJuanZhongYuan** [WeiYe-Jing/datax-web#490]
你好 ，我从官网这个地址下载 linux datax tar包（https://pan.baidu.com/s/13yoqhGpD00I82K4lOYtQhg），但是下载下来按照官网教程，最后并未生成 datax.py 文件，目前admin界面是可以打开的，Json 模板也是可以生成的，就是执行Job 时候，因为没有 datax.py 而报错 ，这个datax.py 是怎么生成的

**Comment by xiJuanZhongYuan** [comment]
有人回复一下吗

**Comment by hydgladiator** [comment]
application.yaml或者data-executor.sh要修改对应的路径
