### ISSUE TITLE
StarRocks数据库能添加web操作吗

### ISSUE THREAD

**Issue by Phoebus888** [WeiYe-Jing/datax-web#497]
如题

**Comment by zhiguohe** [comment]
建议增加apache doris数据源

**Comment by ititchuan** [comment]
在线等

**Comment by falleafe** [comment]
![image](https://github.com/WeiYe-Jing/datax-web/assets/3815044/383b4655-fd5c-490a-972c-0bf0666b0dd0)
我加上StarRocks了

**Comment by ititchuan** [comment]
感谢您的来信，敝人已收到。敝人会尽快给您回复，谢谢。

**Comment by codegit10001** [comment]
> 如题

目前已经支持了doris和StarRocks了么
