### ISSUE TITLE
dataxjson构建的问题

### ISSUE THREAD

**Issue by ybl007** [WeiYe-Jing/datax-web#5]
在dataxjson构建第三步需要填写字段映射，但填写的数据在构建时并没有使用上，按照了第一步和第二部的勾选顺序进行了映射。
比如：我在第一步先勾选了（name,pk,age）第二步我勾选了（pk,username,userage）那么第三步我填写映射关系，[
  {
    "src": {
      "name": "name",
      "name": "pk",
      "name": "age"
    },
    "des": {
      "name": "username",
      "name": "pk",
      "name": "userage"
    }
  }
]
生成的json中对应也是错误的。

**Comment by WeiYe-Jing** [comment]
是的，第三步字段映射功能还没完成

**Comment by WeiYe-Jing** [comment]
2.1.0版本中改问题已修复，感谢！
