### ISSUE TITLE
[BUG] log4j2 0day 远程代码执行漏洞以及修复建议

### ISSUE THREAD

**Issue by myhoger** [WeiYe-Jing/datax-web#503]
https://view.inews.qq.com/a/20211210A01JXN00
https://github.com/apache/logging-log4j2/releases/tag/log4j-2.15.0-rc2

作者大大 能否帮忙升级下log4j

**Comment by qujiabin** [comment]
您的邮件我已收到，我会尽快给您回复！

**Comment by WeiYe-Jing** [comment]
dev分支已修复
