### ISSUE TITLE
[BUG] 日志管理不更新数据

### ISSUE THREAD

**Issue by acChris** [WeiYe-Jing/datax-web#526]
*For better global communication, please give priority to using English description, thx! *

**Describe the bug**
执行任务a，然后点击任务a的日志管理。回到任务管理页面，再执行任务b，可以看到日志数据未更新。

**To Reproduce**
Steps to reproduce the behavior, for example:
1. 执行任务a
2. 点击任务a的日志管理
3. 回到任务管理页面，执行任务b

期望结果：日志数据更新为任务b的
实际结果：日志数据未更新

**Comment by michael-liumh** [comment]
要手动刷新才有
