### ISSUE TITLE
[QUESTION]  我连 远程mongodb 超时3s 如图，这个怎么解决大神！？？

### ISSUE THREAD

**Issue by jeff-maweijie** [WeiYe-Jing/datax-web#575]
![image](https://user-images.githubusercontent.com/10686446/189051633-e92425a2-007d-466c-9576-4cb481fb40be.png)

**Comment by jeff-maweijie** [comment]
已解决， 配置mongo 加上authSource 即可

**Comment by FuJian1105** [comment]
直接这样加吗“?authSource=${auth_db:admin}”
