### ISSUE TITLE
项目还在维护吗

### ISSUE THREAD

**Issue by Phoebus888** [WeiYe-Jing/datax-web#580]
项目还在维护吗

**Comment by sunsikai** [comment]
这项目看着像是凉了啊，都好久没迭代了，Issues也是一大堆问题未处理。我QQ群申请了一星期了也没通过，要是凉了就可惜了，这么好的一个项目，希望作者给力点啊

**Comment by lilianglong** [comment]
个人开发者比较难，时间精力有限，生活中已经卷的不行了，没有支持很难搞，等我把作者拉起来继续写代码，大家可以持续关注
