### ISSUE TITLE
数据源是否支持mongodb6.0+呢

### ISSUE THREAD

**Issue by hyson1234567** [WeiYe-Jing/datax-web#596]
部署了datax-web-2.1.2.tar.gz版本
我的数据源为mongodb server版本为6.0+，当测试数据源连接时报错。
![f57a4c1fefdf601d7f7503888de45f8](https://user-images.githubusercontent.com/16874450/209291786-7c131a88-b1aa-4476-82f9-17085c242073.png)

**Comment by FuJian1105** [comment]
解决了吗

**Comment by Fortytwoo** [comment]
> 解决了吗

这个问题是因为mongdodb的高版本弃用了OP_QUERY方法导致的。
详见https://www.mongodb.com/zh-cn/docs/v6.0/release-notes/6.0-compatibility/#legacy-opcodes-removed

**Comment by qujiabin** [comment]
您的邮件我已收到，我会尽快给您回复！
