### ISSUE TITLE
任务中的json用户名和密码未加密时日志输出异常

### ISSUE THREAD

**Issue by WeiYe-Jing** [WeiYe-Jing/datax-web#61]
c.w.d.a.u.AESUtil - content decrypt error Input length must be multiple of 16 when decrypting with padded cipher

**Comment by waterWang** [comment]
现在添加数据源，在mysql中数据源是密文。粘贴json，在mysql中json中的账密也是密文。应该不会再出现标题bug

**Comment by WeiYe-Jing** [comment]
会存在这个问题，例如用户在点击测试数据源的时候，输入用户名密码，后端程序第一步是去解密，此时会抛出解密异常，因为用户输入的不是密文。但这个解密异常已经被捕获，日志级别我改为了警告。

**Comment by michael-liumh** [comment]
也就是说添加完数据源后，点击“测试连接”是无效的咯。
目前我添加完数据源后，点击测试，会抛出异常：
![image](https://user-images.githubusercontent.com/40595864/153796287-f9f52bbe-a4a1-419b-8c2e-c5e19c5cac3a.png)

用 Linux 的 mysql 命令连接是没问题的:
![image](https://user-images.githubusercontent.com/40595864/153796333-3ef71449-9476-4ab9-94d2-f43a6aa467e9.png)

日志如下：
![image](https://user-images.githubusercontent.com/40595864/153796360-6d32e05c-0da9-47d5-9425-2141b02254f8.png)

**Comment by michael-liumh** [comment]
关了SSL就正常：
![image](https://user-images.githubusercontent.com/40595864/153796742-7373aaec-9d71-422c-b385-c521e3cea30c.png)
