### ISSUE TITLE
read 插件不支持persql和postsql吗

### ISSUE THREAD

**Issue by coolfish-a** [WeiYe-Jing/datax-web#70]
eg.需求： 取数据前，对源库上table更改状态字段值，做完同步后，再改状态值。
如下步骤：

1.update @table set status=1 where status=0 --源表
2.执行select * from @table where status=1 -- insert目的表
3.update @table set status=2 where status=1 --postsql 源表

**Comment by WeiYe-Jing** [comment]
reader插件不支持更新操作，只有读权限。
可以通过shell或者python任务实现更新，并与datax同步任务做依赖来实现。
或者可以自己定制reader插件实现此功能。

**Comment by coolfish-a** [comment]
非常感谢！
