### ISSUE TITLE
刷新或者使用某一个功能，右上角报错，错误信息如下。 加油

### ISSUE THREAD

**Issue by zhangcl2002** [WeiYe-Jing/datax-web#81]
RangeError: Maximum call stack size exceeded at RegExp.exec (<anonymous>) at RegExp.[Symbol.match] (<anonymous>) at String.match (<anonymous>) at pt (http://127.0.0.1:8080/static/js/chunk-libs.5b2bdc2d.js:39:12763) at u (http://127.0.0.1:8080/static/js/chunk-libs.5b2bdc2d.js:39:11825) at s (http://127.0.0.1:8080/static/js/chunk-libs.5b2bdc2d.js:39:12361) at f (http://127.0.0.1:8080/static/js/chunk-libs.5b2bdc2d.js:39:12657) at u (http://127.0.0.1:8080/static/js/chunk-libs.5b2bdc2d.js:39:11860) at s (http://127.0.0.1:8080/static/js/chunk-libs.5b2bdc2d.js:39:12361) at f (http://127.0.0.1:8080/static/js/chunk-libs.5b2bdc2d.js:39:12657)

**Comment by WeiYe-Jing** [comment]
目前使用的是哪个版本，浏览器和版本帮忙提供下，我这边测试没发现这个问题。
建议更新到最新版再验证下此问题。

**Comment by zhangcl2002** [comment]
2.1.1 版本，chrome 80. 我后面用master再试试再回复。多谢啦。项目很棒，之前有用gitlab+docker+Jenkins做过一个，想要做这样一个项目，但自己做不了。恰好看到，真的是非常好。

**Comment by zhangcl2002** [comment]
代码开发完毕后，开发一个helm chart, 全部容器化部署，会极大的方便部署。 即使使用docker也会极大的提升项目的使用便利性。 仅是建议哦

**Comment by WeiYe-Jing** [comment]
感谢建议，docker下个版本会集成，helm chart我们考虑下。

**Comment by zhangcl2002** [comment]
使用master分支重新编译，未再出现最开始的问题

**Comment by zhangcl2002** [comment]
使用master分支重新编译，未再出现最开始的问题
