### ISSUE TITLE
任务构建 数据源为mysql，where条件写了后没有拼接入查询语句

### ISSUE THREAD

**Issue by huanzui** [WeiYe-Jing/datax-web#88]
任务构建 数据源为mysql，where条件写了后 构建生成的json中并没有拼接入查询语句后面

**Comment by WeiYe-Jing** [comment]
我这边测试下来没问题，请检查是否违背了datax的使用规则：
`当用户配置querySql时，MysqlReader直接忽略table、column、where条件的配置，querySql优先级大于table、column、where选项。`

**Comment by huanzui** [comment]
> 我这边测试下来没问题，请检查是否违背了datax的使用规则：
> `当用户配置querySql时，MysqlReader直接忽略table、column、where条件的配置，querySql优先级大于table、column、where选项。`

噢 好的 还以为是页面问题
