### ISSUE TITLE
任务构建 选择写入数据源为mongodb后 页面下拉框刷新，数据源和表又都要重新选择才生效

### ISSUE THREAD

**Issue by huanzui** [WeiYe-Jing/datax-web#89]
任务构建 选择写入数据源为mongodb后 页面下拉框刷新，数据源和表又都要重新选择 数据源下拉框才显示

**Comment by WeiYe-Jing** [comment]
此问题将合并到 https://github.com/WeiYe-Jing/datax-web-ui/issues/10
