### ISSUE TITLE
任务构建 两个数据源字段对应问题

### ISSUE THREAD

**Issue by huanzui** [WeiYe-Jing/datax-web#90]
源数据 与 目标源字段 无法一一调整，只能调整SQL才行，且源数据sql查询出的字段Long 类型无法调整，如带有sum() 的 默认double，无法调整为Long

**Comment by WeiYe-Jing** [comment]
#29 已提，字段映射目前正在开发中。字段类型转换需要修改datax插件，暂无计划。
