### ISSUE TITLE
创建数据源失败

### ISSUE THREAD

**Issue by WeiYe-Jing** [WeiYe-Jing/datax-web#99]
创建数据源时系统报错，用户名密码为null，发现是前端没有把数据库的用户名密码传递到后端

**Comment by WeiYe-Jing** [comment]
数据源用户名密码为null的问题解决方法
建议jdk版本切换到1.8.2xx版本以上，或者参考这篇https://www.cnblogs.com/jinloooong/p/10619353.html
连接中的jar包下载地址：
链接：https://pan.baidu.com/s/1yGcjidC7wPdKQgnTtx8Dxg 
提取码：o194

**Comment by yangxiongj** [comment]
兼容性这么差，为啥不换个加密方式呢

**Comment by WeiYe-Jing** [comment]
要换的，在计划中了

**Comment by WeiYe-Jing** [comment]
2.1.2已兼容
